*     File eu_eutt/aeu_euttkptbl.f : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aeu_euttkptbl
      implicit real*8(a-h,o-z)

      include 'incleu_eutt1.h'
      include 'inclk.h'
      include 'incleu_euttp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfeu_eutt2(i) =  + peeu_eutt1(i)
        pfeu_eutt4(i) =  + peeu_eutt2(i)
        pfeu_eutt6(i) =  + peeu_eutt1(i) + peeu_eutt2(i)
        pfeu_eutt8(i) =  - peeu_eutt3(i)
        pfeu_eutt10(i) =  + peeu_eutt1(i) - peeu_eutt3(i)
        pfeu_eutt12(i) =  + peeu_eutt2(i) - peeu_eutt3(i)
        pfeu_eutt14(i) =  + peeu_eutt1(i) + peeu_eutt2(i) - peeu_eutt3(i)
        pfeu_eutt16(i) =  - peeu_eutt4(i)
        pfeu_eutt18(i) =  + peeu_eutt1(i) - peeu_eutt4(i)
        pfeu_eutt20(i) =  + peeu_eutt2(i) - peeu_eutt4(i)
        pfeu_eutt22(i) =  + peeu_eutt1(i) + peeu_eutt2(i) - peeu_eutt4(i)
        pfeu_eutt24(i) =  - peeu_eutt3(i) - peeu_eutt4(i)
        pfeu_eutt26(i) =  + peeu_eutt1(i) - peeu_eutt3(i) - peeu_eutt4(i)
        pfeu_eutt28(i) =  + peeu_eutt2(i) - peeu_eutt3(i) - peeu_eutt4(i)
        pfeu_eutt30(i) =  + peeu_eutt5(i) + peeu_eutt6(i)
        pfeu_eutt32(i) =  - peeu_eutt5(i)
        pfeu_eutt34(i) =  + peeu_eutt1(i) - peeu_eutt5(i)
        pfeu_eutt36(i) =  + peeu_eutt2(i) - peeu_eutt5(i)
        pfeu_eutt38(i) =  + peeu_eutt1(i) + peeu_eutt2(i) - peeu_eutt5(i)
        pfeu_eutt40(i) =  - peeu_eutt3(i) - peeu_eutt5(i)
        pfeu_eutt42(i) =  + peeu_eutt1(i) - peeu_eutt3(i) - peeu_eutt5(i)
        pfeu_eutt44(i) =  + peeu_eutt2(i) - peeu_eutt3(i) - peeu_eutt5(i)
        pfeu_eutt46(i) =  + peeu_eutt4(i) + peeu_eutt6(i)
        pfeu_eutt48(i) =  - peeu_eutt4(i) - peeu_eutt5(i)
        pfeu_eutt50(i) =  + peeu_eutt1(i) - peeu_eutt4(i) - peeu_eutt5(i)
        pfeu_eutt52(i) =  + peeu_eutt2(i) - peeu_eutt4(i) - peeu_eutt5(i)
        pfeu_eutt54(i) =  + peeu_eutt3(i) + peeu_eutt6(i)
        pfeu_eutt56(i) =  - peeu_eutt3(i) - peeu_eutt4(i) - peeu_eutt5(i)
        pfeu_eutt58(i) =  - peeu_eutt2(i) + peeu_eutt6(i)
        pfeu_eutt60(i) =  - peeu_eutt1(i) + peeu_eutt6(i)
        pfeu_eutt62(i) =  + peeu_eutt6(i)

        pfeu_eutt3(i) = - pfeu_eutt2(i)
        pfeu_eutt5(i) = - pfeu_eutt4(i)
        pfeu_eutt7(i) = - pfeu_eutt6(i)
        pfeu_eutt9(i) = - pfeu_eutt8(i)
        pfeu_eutt11(i) = - pfeu_eutt10(i)
        pfeu_eutt13(i) = - pfeu_eutt12(i)
        pfeu_eutt15(i) = - pfeu_eutt14(i)
        pfeu_eutt17(i) = - pfeu_eutt16(i)
        pfeu_eutt19(i) = - pfeu_eutt18(i)
        pfeu_eutt21(i) = - pfeu_eutt20(i)
        pfeu_eutt23(i) = - pfeu_eutt22(i)
        pfeu_eutt25(i) = - pfeu_eutt24(i)
        pfeu_eutt27(i) = - pfeu_eutt26(i)
        pfeu_eutt29(i) = - pfeu_eutt28(i)
        pfeu_eutt31(i) = - pfeu_eutt30(i)
        pfeu_eutt33(i) = - pfeu_eutt32(i)
        pfeu_eutt35(i) = - pfeu_eutt34(i)
        pfeu_eutt37(i) = - pfeu_eutt36(i)
        pfeu_eutt39(i) = - pfeu_eutt38(i)
        pfeu_eutt41(i) = - pfeu_eutt40(i)
        pfeu_eutt43(i) = - pfeu_eutt42(i)
        pfeu_eutt45(i) = - pfeu_eutt44(i)
        pfeu_eutt47(i) = - pfeu_eutt46(i)
        pfeu_eutt49(i) = - pfeu_eutt48(i)
        pfeu_eutt51(i) = - pfeu_eutt50(i)
        pfeu_eutt53(i) = - pfeu_eutt52(i)
        pfeu_eutt55(i) = - pfeu_eutt54(i)
        pfeu_eutt57(i) = - pfeu_eutt56(i)
        pfeu_eutt59(i) = - pfeu_eutt58(i)
        pfeu_eutt61(i) = - pfeu_eutt60(i)
        pfeu_eutt63(i) = - pfeu_eutt62(i)
  100 continue

      vneu_eutt2 =  + amass2(1)
      vneu_eutt4 =  + amass2(2)
      vneu_eutt6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vneu_eutt8 =  + amass2(3)
      vneu_eutt10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vneu_eutt12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vneu_eutt14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vneu_eutt16 =  + amass2(4)
      vneu_eutt18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vneu_eutt20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vneu_eutt22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vneu_eutt24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vneu_eutt26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vneu_eutt28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vneu_eutt30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vneu_eutt32 =  + amass2(5)
      vneu_eutt34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vneu_eutt36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vneu_eutt38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vneu_eutt40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vneu_eutt42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vneu_eutt44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vneu_eutt46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vneu_eutt48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vneu_eutt50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vneu_eutt52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vneu_eutt54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vneu_eutt56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vneu_eutt58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vneu_eutt60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vneu_eutt62 =  + amass2(6)
      vneu_eutt3 = vneu_eutt2
      vneu_eutt5 = vneu_eutt4
      vneu_eutt7 = vneu_eutt6
      vneu_eutt9 = vneu_eutt8
      vneu_eutt11 = vneu_eutt10
      vneu_eutt13 = vneu_eutt12
      vneu_eutt15 = vneu_eutt14
      vneu_eutt17 = vneu_eutt16
      vneu_eutt19 = vneu_eutt18
      vneu_eutt21 = vneu_eutt20
      vneu_eutt23 = vneu_eutt22
      vneu_eutt25 = vneu_eutt24
      vneu_eutt27 = vneu_eutt26
      vneu_eutt29 = vneu_eutt28
      vneu_eutt31 = vneu_eutt30
      vneu_eutt33 = vneu_eutt32
      vneu_eutt35 = vneu_eutt34
      vneu_eutt37 = vneu_eutt36
      vneu_eutt39 = vneu_eutt38
      vneu_eutt41 = vneu_eutt40
      vneu_eutt43 = vneu_eutt42
      vneu_eutt45 = vneu_eutt44
      vneu_eutt47 = vneu_eutt46
      vneu_eutt49 = vneu_eutt48
      vneu_eutt51 = vneu_eutt50
      vneu_eutt53 = vneu_eutt52
      vneu_eutt55 = vneu_eutt54
      vneu_eutt57 = vneu_eutt56
      vneu_eutt59 = vneu_eutt58
      vneu_eutt61 = vneu_eutt60
      vneu_eutt63 = vneu_eutt62
      return
      end
