*     File eu_eutt/aeu_euttmptbl.f : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aeu_euttmptbl
      implicit real*8(a-h,o-z)
      include 'incleu_eutt1.h'
      include 'incl2.h'
      include 'inclk.h'
      include 'incleu_euttp.h'
*-----------------------------------------------------------------------
      jgraph = 0

* External lines
      call smextf(lincom,amuq(1),pfeu_eutt2,pteu_eutt2p,cfeu_eutt2p)
      exeu_eutt2p(1) = lprtcl
      call smextf(loutgo,amlp(1),pfeu_eutt4,pteu_eutt4m,cfeu_eutt4m)
      exeu_eutt4m(1) = lantip
      call smextf(loutgo,amuq(1),pfeu_eutt9,pteu_eutt9p,cfeu_eutt9p)
      exeu_eutt9p(1) = lprtcl
      call smextf(lincom,amlp(1),pfeu_eutt17,pteu_eutt17m,cfeu_eutt17m)
      exeu_eutt17m(1) = lantip
      call smextf(loutgo,amlp(3),pfeu_eutt33,pteu_eutt33o,cfeu_eutt33o)
      exeu_eutt33o(1) = lprtcl
      call smextf(lincom,amlp(3),pfeu_eutt62,pteu_eutt62o,cfeu_eutt62o)
      exeu_eutt62o(1) = lantip


* Buffer clear for amplitude
      do 200 ih = 0 , leu_euttag-1
         agc(ih) = (0.0d0,0.0d0)
  200 continue

      call aeu_euttmpt0

      return
      end
************************************************************************
      subroutine aeu_euttmpt0
      implicit real*8(a-h,o-z)

      include 'incleu_eutt1.h'
      include 'incl2.h'
      include 'inclk.h'
*-----------------------------------------------------------------------
      if(jselg(1) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 1
        call aeu_euttg1
      endif

      if(jselg(2) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 2
        call aeu_euttg2
      endif

      if(jselg(3) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 3
        call aeu_euttg3
      endif

      if(jselg(4) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 4
        call aeu_euttg4
      endif

      if(jselg(5) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 5
        call aeu_euttg5
      endif

      if(jselg(6) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 6
        call aeu_euttg6
      endif

      if(jselg(7) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 7
        call aeu_euttg7
      endif

      if(jselg(8) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 8
        call aeu_euttg8
      endif

      if(jselg(9) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 9
        call aeu_euttg9
      endif

      if(jselg(10) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 10
        call aeu_euttg10
      endif

      if(jselg(11) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 11
        call aeu_euttg11
      endif

      if(jselg(12) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 12
        call aeu_euttg12
      endif

      if(jselg(13) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 13
        call aeu_euttg13
      endif

      if(jselg(14) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 14
        call aeu_euttg14
      endif

      if(jselg(15) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 15
        call aeu_euttg15
      endif

      if(jselg(16) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 16
        call aeu_euttg16
      endif

      if(jhiggs .ne. 0) then
      if(jselg(17) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 17
        call aeu_euttg17
      endif
      endif

      if(jselg(18) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 18
        call aeu_euttg18
      endif

      if(jselg(19) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 19
        call aeu_euttg19
      endif

      if(jselg(20) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 20
        call aeu_euttg20
      endif

      if(jselg(21) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 21
        call aeu_euttg21
      endif

      if(jselg(22) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 22
        call aeu_euttg22
      endif

      if(jselg(23) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 23
        call aeu_euttg23
      endif

      if(jselg(24) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 24
        call aeu_euttg24
      endif

      if(jselg(25) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 25
        call aeu_euttg25
      endif

      return
      end
