*     File eub_eubtt/aeub_eubttkptbl.f : Sat Mar 18 19:45:00 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aeub_eubttkptbl
      implicit real*8(a-h,o-z)

      include 'incleub_eubtt1.h'
      include 'inclk.h'
      include 'incleub_eubttp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfeub_eubtt2(i) =  + peeub_eubtt1(i)
        pfeub_eubtt4(i) =  + peeub_eubtt2(i)
        pfeub_eubtt6(i) =  + peeub_eubtt1(i) + peeub_eubtt2(i)
        pfeub_eubtt8(i) =  - peeub_eubtt3(i)
        pfeub_eubtt10(i) =  + peeub_eubtt1(i) - peeub_eubtt3(i)
        pfeub_eubtt12(i) =  + peeub_eubtt2(i) - peeub_eubtt3(i)
        pfeub_eubtt14(i) =  + peeub_eubtt1(i) + peeub_eubtt2(i) - peeub_eubtt3(i)
        pfeub_eubtt16(i) =  - peeub_eubtt4(i)
        pfeub_eubtt18(i) =  + peeub_eubtt1(i) - peeub_eubtt4(i)
        pfeub_eubtt20(i) =  + peeub_eubtt2(i) - peeub_eubtt4(i)
        pfeub_eubtt22(i) =  + peeub_eubtt1(i) + peeub_eubtt2(i) - peeub_eubtt4(i)
        pfeub_eubtt24(i) =  - peeub_eubtt3(i) - peeub_eubtt4(i)
        pfeub_eubtt26(i) =  + peeub_eubtt1(i) - peeub_eubtt3(i) - peeub_eubtt4(i)
        pfeub_eubtt28(i) =  + peeub_eubtt2(i) - peeub_eubtt3(i) - peeub_eubtt4(i)
        pfeub_eubtt30(i) =  + peeub_eubtt5(i) + peeub_eubtt6(i)
        pfeub_eubtt32(i) =  - peeub_eubtt5(i)
        pfeub_eubtt34(i) =  + peeub_eubtt1(i) - peeub_eubtt5(i)
        pfeub_eubtt36(i) =  + peeub_eubtt2(i) - peeub_eubtt5(i)
        pfeub_eubtt38(i) =  + peeub_eubtt1(i) + peeub_eubtt2(i) - peeub_eubtt5(i)
        pfeub_eubtt40(i) =  - peeub_eubtt3(i) - peeub_eubtt5(i)
        pfeub_eubtt42(i) =  + peeub_eubtt1(i) - peeub_eubtt3(i) - peeub_eubtt5(i)
        pfeub_eubtt44(i) =  + peeub_eubtt2(i) - peeub_eubtt3(i) - peeub_eubtt5(i)
        pfeub_eubtt46(i) =  + peeub_eubtt4(i) + peeub_eubtt6(i)
        pfeub_eubtt48(i) =  - peeub_eubtt4(i) - peeub_eubtt5(i)
        pfeub_eubtt50(i) =  + peeub_eubtt1(i) - peeub_eubtt4(i) - peeub_eubtt5(i)
        pfeub_eubtt52(i) =  + peeub_eubtt2(i) - peeub_eubtt4(i) - peeub_eubtt5(i)
        pfeub_eubtt54(i) =  + peeub_eubtt3(i) + peeub_eubtt6(i)
        pfeub_eubtt56(i) =  - peeub_eubtt3(i) - peeub_eubtt4(i) - peeub_eubtt5(i)
        pfeub_eubtt58(i) =  - peeub_eubtt2(i) + peeub_eubtt6(i)
        pfeub_eubtt60(i) =  - peeub_eubtt1(i) + peeub_eubtt6(i)
        pfeub_eubtt62(i) =  + peeub_eubtt6(i)

        pfeub_eubtt3(i) = - pfeub_eubtt2(i)
        pfeub_eubtt5(i) = - pfeub_eubtt4(i)
        pfeub_eubtt7(i) = - pfeub_eubtt6(i)
        pfeub_eubtt9(i) = - pfeub_eubtt8(i)
        pfeub_eubtt11(i) = - pfeub_eubtt10(i)
        pfeub_eubtt13(i) = - pfeub_eubtt12(i)
        pfeub_eubtt15(i) = - pfeub_eubtt14(i)
        pfeub_eubtt17(i) = - pfeub_eubtt16(i)
        pfeub_eubtt19(i) = - pfeub_eubtt18(i)
        pfeub_eubtt21(i) = - pfeub_eubtt20(i)
        pfeub_eubtt23(i) = - pfeub_eubtt22(i)
        pfeub_eubtt25(i) = - pfeub_eubtt24(i)
        pfeub_eubtt27(i) = - pfeub_eubtt26(i)
        pfeub_eubtt29(i) = - pfeub_eubtt28(i)
        pfeub_eubtt31(i) = - pfeub_eubtt30(i)
        pfeub_eubtt33(i) = - pfeub_eubtt32(i)
        pfeub_eubtt35(i) = - pfeub_eubtt34(i)
        pfeub_eubtt37(i) = - pfeub_eubtt36(i)
        pfeub_eubtt39(i) = - pfeub_eubtt38(i)
        pfeub_eubtt41(i) = - pfeub_eubtt40(i)
        pfeub_eubtt43(i) = - pfeub_eubtt42(i)
        pfeub_eubtt45(i) = - pfeub_eubtt44(i)
        pfeub_eubtt47(i) = - pfeub_eubtt46(i)
        pfeub_eubtt49(i) = - pfeub_eubtt48(i)
        pfeub_eubtt51(i) = - pfeub_eubtt50(i)
        pfeub_eubtt53(i) = - pfeub_eubtt52(i)
        pfeub_eubtt55(i) = - pfeub_eubtt54(i)
        pfeub_eubtt57(i) = - pfeub_eubtt56(i)
        pfeub_eubtt59(i) = - pfeub_eubtt58(i)
        pfeub_eubtt61(i) = - pfeub_eubtt60(i)
        pfeub_eubtt63(i) = - pfeub_eubtt62(i)
  100 continue

      vneub_eubtt2 =  + amass2(1)
      vneub_eubtt4 =  + amass2(2)
      vneub_eubtt6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vneub_eubtt8 =  + amass2(3)
      vneub_eubtt10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vneub_eubtt12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vneub_eubtt14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vneub_eubtt16 =  + amass2(4)
      vneub_eubtt18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vneub_eubtt20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vneub_eubtt22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vneub_eubtt24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vneub_eubtt26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vneub_eubtt28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vneub_eubtt30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vneub_eubtt32 =  + amass2(5)
      vneub_eubtt34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vneub_eubtt36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vneub_eubtt38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vneub_eubtt40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vneub_eubtt42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vneub_eubtt44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vneub_eubtt46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vneub_eubtt48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vneub_eubtt50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vneub_eubtt52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vneub_eubtt54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vneub_eubtt56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vneub_eubtt58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vneub_eubtt60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vneub_eubtt62 =  + amass2(6)
      vneub_eubtt3 = vneub_eubtt2
      vneub_eubtt5 = vneub_eubtt4
      vneub_eubtt7 = vneub_eubtt6
      vneub_eubtt9 = vneub_eubtt8
      vneub_eubtt11 = vneub_eubtt10
      vneub_eubtt13 = vneub_eubtt12
      vneub_eubtt15 = vneub_eubtt14
      vneub_eubtt17 = vneub_eubtt16
      vneub_eubtt19 = vneub_eubtt18
      vneub_eubtt21 = vneub_eubtt20
      vneub_eubtt23 = vneub_eubtt22
      vneub_eubtt25 = vneub_eubtt24
      vneub_eubtt27 = vneub_eubtt26
      vneub_eubtt29 = vneub_eubtt28
      vneub_eubtt31 = vneub_eubtt30
      vneub_eubtt33 = vneub_eubtt32
      vneub_eubtt35 = vneub_eubtt34
      vneub_eubtt37 = vneub_eubtt36
      vneub_eubtt39 = vneub_eubtt38
      vneub_eubtt41 = vneub_eubtt40
      vneub_eubtt43 = vneub_eubtt42
      vneub_eubtt45 = vneub_eubtt44
      vneub_eubtt47 = vneub_eubtt46
      vneub_eubtt49 = vneub_eubtt48
      vneub_eubtt51 = vneub_eubtt50
      vneub_eubtt53 = vneub_eubtt52
      vneub_eubtt55 = vneub_eubtt54
      vneub_eubtt57 = vneub_eubtt56
      vneub_eubtt59 = vneub_eubtt58
      vneub_eubtt61 = vneub_eubtt60
      vneub_eubtt63 = vneub_eubtt62
      return
      end
