*     File akptbl.f : Sat Mar 18 19:45:07 2000
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
************************************************************************
      subroutine akptbl
      implicit real*8(a-h,o-z)
      common /amjprc/jproc
        if(jproc .eq. 1) then
            call aep_epeekptbl
        endif
        if(jproc .eq. 2) then
            call aep_epmmkptbl
        endif
        if(jproc .eq. 3) then
            call aep_epttkptbl
        endif
        if(jproc .eq. 4) then
            call aep_eXeekptbl
        endif
        if(jproc .eq. 5) then
            call aep_eXmmkptbl
        endif
        if(jproc .eq. 6) then
            call aep_eXttkptbl
        endif
        if(jproc .eq. 7) then
            call aeu_eueekptbl
        endif
        if(jproc .eq. 8) then
            call aeu_eummkptbl
        endif
        if(jproc .eq. 9) then
            call aeu_euttkptbl
        endif
        if(jproc .eq. 10) then
            call aeub_eubeekptbl
        endif
        if(jproc .eq. 11) then
            call aeub_eubmmkptbl
        endif
        if(jproc .eq. 12) then
            call aeub_eubttkptbl
        endif
        if(jproc .eq. 13) then
            call aed_edeekptbl
        endif
        if(jproc .eq. 14) then
            call aed_edmmkptbl
        endif
        if(jproc .eq. 15) then
            call aed_edttkptbl
        endif
        if(jproc .eq. 16) then
            call aedb_edbeekptbl
        endif
        if(jproc .eq. 17) then
            call aedb_edbmmkptbl
        endif
        if(jproc .eq. 18) then
            call aedb_edbttkptbl
        endif
        if(jproc .eq. 19) then
            call aes_eseekptbl
        endif
        if(jproc .eq. 20) then
            call aes_esmmkptbl
        endif
        if(jproc .eq. 21) then
            call aes_esttkptbl
        endif
        if(jproc .eq. 22) then
            call aesb_esbeekptbl
        endif
        if(jproc .eq. 23) then
            call aesb_esbmmkptbl
        endif
        if(jproc .eq. 24) then
            call aesb_esbttkptbl
        endif
        if(jproc .eq. 25) then
            call aec_eceekptbl
        endif
        if(jproc .eq. 26) then
            call aec_ecmmkptbl
        endif
        if(jproc .eq. 27) then
            call aec_ecttkptbl
        endif
        if(jproc .eq. 28) then
            call aecb_ecbeekptbl
        endif
        if(jproc .eq. 29) then
            call aecb_ecbmmkptbl
        endif
        if(jproc .eq. 30) then
            call aecb_ecbttkptbl
        endif
        if(jproc .eq. 31) then
            call aeb_ebeekptbl
        endif
        if(jproc .eq. 32) then
            call aeb_ebmmkptbl
        endif
        if(jproc .eq. 33) then
            call aeb_ebttkptbl
        endif
        if(jproc .eq. 34) then
            call aebb_ebbeekptbl
        endif
        if(jproc .eq. 35) then
            call aebb_ebbmmkptbl
        endif
        if(jproc .eq. 36) then
            call aebb_ebbttkptbl
        endif
        if(jproc .eq. 37) then
            call aet_eteekptbl
        endif
        if(jproc .eq. 38) then
            call aet_etmmkptbl
        endif
        if(jproc .eq. 39) then
            call aet_etttkptbl
        endif
        if(jproc .eq. 40) then
            call aetb_etbeekptbl
        endif
        if(jproc .eq. 41) then
            call aetb_etbmmkptbl
        endif
        if(jproc .eq. 42) then
            call aetb_etbttkptbl
        endif
        return
        end
