*     File usrout.f : Sat Mar 18 19:44:57 2000
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
************************************************************************
      subroutine usrout
      implicit real*8(a-h,o-z)
      common /amjprc/jproc
        if(jproc .eq. 1) then
            call usoep_epee
        endif
        if(jproc .eq. 2) then
            call usoep_epmm
        endif
        if(jproc .eq. 3) then
            call usoep_eptt
        endif
        if(jproc .eq. 4) then
            call usoep_eXee
        endif
        if(jproc .eq. 5) then
            call usoep_eXmm
        endif
        if(jproc .eq. 6) then
            call usoep_eXtt
        endif
        if(jproc .eq. 7) then
            call usoeu_euee
        endif
        if(jproc .eq. 8) then
            call usoeu_eumm
        endif
        if(jproc .eq. 9) then
            call usoeu_eutt
        endif
        if(jproc .eq. 10) then
            call usoeub_eubee
        endif
        if(jproc .eq. 11) then
            call usoeub_eubmm
        endif
        if(jproc .eq. 12) then
            call usoeub_eubtt
        endif
        if(jproc .eq. 13) then
            call usoed_edee
        endif
        if(jproc .eq. 14) then
            call usoed_edmm
        endif
        if(jproc .eq. 15) then
            call usoed_edtt
        endif
        if(jproc .eq. 16) then
            call usoedb_edbee
        endif
        if(jproc .eq. 17) then
            call usoedb_edbmm
        endif
        if(jproc .eq. 18) then
            call usoedb_edbtt
        endif
        if(jproc .eq. 19) then
            call usoes_esee
        endif
        if(jproc .eq. 20) then
            call usoes_esmm
        endif
        if(jproc .eq. 21) then
            call usoes_estt
        endif
        if(jproc .eq. 22) then
            call usoesb_esbee
        endif
        if(jproc .eq. 23) then
            call usoesb_esbmm
        endif
        if(jproc .eq. 24) then
            call usoesb_esbtt
        endif
        if(jproc .eq. 25) then
            call usoec_ecee
        endif
        if(jproc .eq. 26) then
            call usoec_ecmm
        endif
        if(jproc .eq. 27) then
            call usoec_ectt
        endif
        if(jproc .eq. 28) then
            call usoecb_ecbee
        endif
        if(jproc .eq. 29) then
            call usoecb_ecbmm
        endif
        if(jproc .eq. 30) then
            call usoecb_ecbtt
        endif
        if(jproc .eq. 31) then
            call usoeb_ebee
        endif
        if(jproc .eq. 32) then
            call usoeb_ebmm
        endif
        if(jproc .eq. 33) then
            call usoeb_ebtt
        endif
        if(jproc .eq. 34) then
            call usoebb_ebbee
        endif
        if(jproc .eq. 35) then
            call usoebb_ebbmm
        endif
        if(jproc .eq. 36) then
            call usoebb_ebbtt
        endif
        if(jproc .eq. 37) then
            call usoet_etee
        endif
        if(jproc .eq. 38) then
            call usoet_etmm
        endif
        if(jproc .eq. 39) then
            call usoet_ettt
        endif
        if(jproc .eq. 40) then
            call usoetb_etbee
        endif
        if(jproc .eq. 41) then
            call usoetb_etbmm
        endif
        if(jproc .eq. 42) then
            call usoetb_etbtt
        endif
        return
        end
