*     File usrprm.f : Sat Mar 18 19:44:57 2000
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
** defined in all.fin
      subroutine usrprm
      implicit real*8(a-h,o-z)
      include 'inclc.h'
      include 'inclk.h'
*-----------------------------------------------------------------------
* Set global parameters.
      return
      end
