*     File ed_edee/incled_edeep.h : Sat Mar 18 19:45:00 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfed_edee2(4),pfed_edee3(4),pfed_edee4(4),
     &               pfed_edee5(4),pfed_edee6(4),pfed_edee7(4),
     &               pfed_edee8(4),pfed_edee9(4),pfed_edee10(4),
     &               pfed_edee11(4),pfed_edee12(4),pfed_edee13(4),
     &               pfed_edee14(4),pfed_edee15(4),pfed_edee16(4),
     &               pfed_edee17(4),pfed_edee18(4),pfed_edee19(4),
     &               pfed_edee20(4),pfed_edee21(4),pfed_edee22(4),
     &               pfed_edee23(4),pfed_edee24(4),pfed_edee25(4),
     &               pfed_edee26(4),pfed_edee27(4),pfed_edee28(4),
     &               pfed_edee29(4),pfed_edee30(4),pfed_edee31(4),
     &               pfed_edee32(4),pfed_edee33(4),pfed_edee34(4),
     &               pfed_edee35(4),pfed_edee36(4),pfed_edee37(4),
     &               pfed_edee38(4),pfed_edee39(4),pfed_edee40(4),
     &               pfed_edee41(4),pfed_edee42(4),pfed_edee43(4),
     &               pfed_edee44(4),pfed_edee45(4),pfed_edee46(4),
     &               pfed_edee47(4),pfed_edee48(4),pfed_edee49(4)
      common /amilcd_4f/pfed_edee50(4),pfed_edee51(4),
     &               pfed_edee52(4),pfed_edee53(4),pfed_edee54(4),
     &               pfed_edee55(4),pfed_edee56(4),pfed_edee57(4),
     &               pfed_edee58(4),pfed_edee59(4),pfed_edee60(4),
     &               pfed_edee61(4),pfed_edee62(4),pfed_edee63(4)
      common /amilcp_4f/vned_edee2,vned_edee3,vned_edee4,vned_edee5,
     &               vned_edee6,vned_edee7,vned_edee8,vned_edee9,
     &               vned_edee10,vned_edee11,vned_edee12,vned_edee13,
     &               vned_edee14,vned_edee15,vned_edee16,vned_edee17,
     &               vned_edee18,vned_edee19,vned_edee20,vned_edee21,
     &               vned_edee22,vned_edee23,vned_edee24,vned_edee25,
     &               vned_edee26,vned_edee27,vned_edee28,vned_edee29,
     &               vned_edee30,vned_edee31,vned_edee32,vned_edee33,
     &               vned_edee34,vned_edee35,vned_edee36,vned_edee37,
     &               vned_edee38,vned_edee39,vned_edee40,vned_edee41,
     &               vned_edee42,vned_edee43,vned_edee44,vned_edee45,
     &               vned_edee46,vned_edee47,vned_edee48,vned_edee49,
     &               vned_edee50,vned_edee51,vned_edee52,vned_edee53,
     &               vned_edee54,vned_edee55,vned_edee56,vned_edee57,
     &               vned_edee58,vned_edee59,vned_edee60,vned_edee61,
     &               vned_edee62,vned_edee63
