*     File ed_edtt/incled_edttp.h : Sat Mar 18 19:45:00 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfed_edtt2(4),pfed_edtt3(4),pfed_edtt4(4),
     &               pfed_edtt5(4),pfed_edtt6(4),pfed_edtt7(4),
     &               pfed_edtt8(4),pfed_edtt9(4),pfed_edtt10(4),
     &               pfed_edtt11(4),pfed_edtt12(4),pfed_edtt13(4),
     &               pfed_edtt14(4),pfed_edtt15(4),pfed_edtt16(4),
     &               pfed_edtt17(4),pfed_edtt18(4),pfed_edtt19(4),
     &               pfed_edtt20(4),pfed_edtt21(4),pfed_edtt22(4),
     &               pfed_edtt23(4),pfed_edtt24(4),pfed_edtt25(4),
     &               pfed_edtt26(4),pfed_edtt27(4),pfed_edtt28(4),
     &               pfed_edtt29(4),pfed_edtt30(4),pfed_edtt31(4),
     &               pfed_edtt32(4),pfed_edtt33(4),pfed_edtt34(4),
     &               pfed_edtt35(4),pfed_edtt36(4),pfed_edtt37(4),
     &               pfed_edtt38(4),pfed_edtt39(4),pfed_edtt40(4),
     &               pfed_edtt41(4),pfed_edtt42(4),pfed_edtt43(4),
     &               pfed_edtt44(4),pfed_edtt45(4),pfed_edtt46(4),
     &               pfed_edtt47(4),pfed_edtt48(4),pfed_edtt49(4)
      common /amilcd_4f/pfed_edtt50(4),pfed_edtt51(4),
     &               pfed_edtt52(4),pfed_edtt53(4),pfed_edtt54(4),
     &               pfed_edtt55(4),pfed_edtt56(4),pfed_edtt57(4),
     &               pfed_edtt58(4),pfed_edtt59(4),pfed_edtt60(4),
     &               pfed_edtt61(4),pfed_edtt62(4),pfed_edtt63(4)
      common /amilcp_4f/vned_edtt2,vned_edtt3,vned_edtt4,vned_edtt5,
     &               vned_edtt6,vned_edtt7,vned_edtt8,vned_edtt9,
     &               vned_edtt10,vned_edtt11,vned_edtt12,vned_edtt13,
     &               vned_edtt14,vned_edtt15,vned_edtt16,vned_edtt17,
     &               vned_edtt18,vned_edtt19,vned_edtt20,vned_edtt21,
     &               vned_edtt22,vned_edtt23,vned_edtt24,vned_edtt25,
     &               vned_edtt26,vned_edtt27,vned_edtt28,vned_edtt29,
     &               vned_edtt30,vned_edtt31,vned_edtt32,vned_edtt33,
     &               vned_edtt34,vned_edtt35,vned_edtt36,vned_edtt37,
     &               vned_edtt38,vned_edtt39,vned_edtt40,vned_edtt41,
     &               vned_edtt42,vned_edtt43,vned_edtt44,vned_edtt45,
     &               vned_edtt46,vned_edtt47,vned_edtt48,vned_edtt49,
     &               vned_edtt50,vned_edtt51,vned_edtt52,vned_edtt53,
     &               vned_edtt54,vned_edtt55,vned_edtt56,vned_edtt57,
     &               vned_edtt58,vned_edtt59,vned_edtt60,vned_edtt61,
     &               vned_edtt62,vned_edtt63
