*     File ep_epee/aep_epeemptbl.f : Sat Mar 18 19:44:57 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aep_epeemptbl
      implicit real*8(a-h,o-z)
      include 'inclep_epee1.h'
      include 'incl2.h'
      include 'inclk.h'
      include 'inclep_epeep.h'
*-----------------------------------------------------------------------
      jgraph = 0

* External lines
      call smextf(lincom,amp,pfep_epee2,ptep_epee2v,cfep_epee2v)
      exep_epee2v(1) = lprtcl
      call smextf(loutgo,amlp(1),pfep_epee4,ptep_epee4m,cfep_epee4m)
      exep_epee4m(1) = lantip
      call smextf(loutgo,amp,pfep_epee9,ptep_epee9v,cfep_epee9v)
      exep_epee9v(1) = lprtcl
      call smextf(lincom,amlp(1),pfep_epee17,ptep_epee17m,cfep_epee17m)
      exep_epee17m(1) = lantip
      call smextf(loutgo,amlp(1),pfep_epee33,ptep_epee33m,cfep_epee33m)
      exep_epee33m(1) = lprtcl
      call smextf(lincom,amlp(1),pfep_epee62,ptep_epee62m,cfep_epee62m)
      exep_epee62m(1) = lantip


* Buffer clear for amplitude
      do 200 ih = 0 , lep_epeeag-1
         agc(ih) = (0.0d0,0.0d0)
  200 continue

      call aep_epeempt0

      return
      end
************************************************************************
      subroutine aep_epeempt0
      implicit real*8(a-h,o-z)

      include 'inclep_epee1.h'
      include 'incl2.h'
      include 'inclk.h'
*-----------------------------------------------------------------------
      if(jselg(1) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 1
        call aep_epeeg1
      endif

      if(jselg(2) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 2
        call aep_epeeg2
      endif

      if(jselg(3) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 3
        call aep_epeeg3
      endif

      if(jselg(4) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 4
        call aep_epeeg4
      endif

      if(jselg(5) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 5
        call aep_epeeg5
      endif

      if(jselg(6) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 6
        call aep_epeeg6
      endif

      if(jselg(7) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 7
        call aep_epeeg7
      endif

      if(jselg(8) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 8
        call aep_epeeg8
      endif

      if(jselg(9) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 9
        call aep_epeeg9
      endif

      if(jselg(10) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 10
        call aep_epeeg10
      endif

      if(jselg(11) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 11
        call aep_epeeg11
      endif

      if(jselg(12) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 12
        call aep_epeeg12
      endif

      if(jselg(13) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 13
        call aep_epeeg13
      endif

      if(jselg(14) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 14
        call aep_epeeg14
      endif

      if(jselg(15) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 15
        call aep_epeeg15
      endif

      if(jselg(16) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 16
        call aep_epeeg16
      endif

      return
      end
