*     File ecb_ecbee/inclecb_ecbeep.h : Sat Mar 18 19:45:04 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfecb_ecbee2(4),pfecb_ecbee3(4),
     &               pfecb_ecbee4(4),pfecb_ecbee5(4),pfecb_ecbee6(4),
     &               pfecb_ecbee7(4),pfecb_ecbee8(4),pfecb_ecbee9(4),
     &               pfecb_ecbee10(4),pfecb_ecbee11(4),pfecb_ecbee12(4),
     &               pfecb_ecbee13(4),pfecb_ecbee14(4),pfecb_ecbee15(4),
     &               pfecb_ecbee16(4),pfecb_ecbee17(4),pfecb_ecbee18(4),
     &               pfecb_ecbee19(4),pfecb_ecbee20(4),pfecb_ecbee21(4),
     &               pfecb_ecbee22(4),pfecb_ecbee23(4),pfecb_ecbee24(4),
     &               pfecb_ecbee25(4),pfecb_ecbee26(4),pfecb_ecbee27(4),
     &               pfecb_ecbee28(4),pfecb_ecbee29(4),pfecb_ecbee30(4),
     &               pfecb_ecbee31(4),pfecb_ecbee32(4),pfecb_ecbee33(4),
     &               pfecb_ecbee34(4),pfecb_ecbee35(4),pfecb_ecbee36(4),
     &               pfecb_ecbee37(4),pfecb_ecbee38(4),pfecb_ecbee39(4),
     &               pfecb_ecbee40(4),pfecb_ecbee41(4),pfecb_ecbee42(4),
     &               pfecb_ecbee43(4),pfecb_ecbee44(4),pfecb_ecbee45(4),
     &               pfecb_ecbee46(4),pfecb_ecbee47(4),pfecb_ecbee48(4)
      common /amilcd_4f/pfecb_ecbee49(4),pfecb_ecbee50(4),
     &               pfecb_ecbee51(4),pfecb_ecbee52(4),pfecb_ecbee53(4),
     &               pfecb_ecbee54(4),pfecb_ecbee55(4),pfecb_ecbee56(4),
     &               pfecb_ecbee57(4),pfecb_ecbee58(4),pfecb_ecbee59(4),
     &               pfecb_ecbee60(4),pfecb_ecbee61(4),pfecb_ecbee62(4),
     &               pfecb_ecbee63(4)
      common /amilcp_4f/vnecb_ecbee2,vnecb_ecbee3,vnecb_ecbee4,
     &               vnecb_ecbee5,vnecb_ecbee6,vnecb_ecbee7,
     &               vnecb_ecbee8,vnecb_ecbee9,vnecb_ecbee10,
     &               vnecb_ecbee11,vnecb_ecbee12,vnecb_ecbee13,
     &               vnecb_ecbee14,vnecb_ecbee15,vnecb_ecbee16,
     &               vnecb_ecbee17,vnecb_ecbee18,vnecb_ecbee19,
     &               vnecb_ecbee20,vnecb_ecbee21,vnecb_ecbee22,
     &               vnecb_ecbee23,vnecb_ecbee24,vnecb_ecbee25,
     &               vnecb_ecbee26,vnecb_ecbee27,vnecb_ecbee28,
     &               vnecb_ecbee29,vnecb_ecbee30,vnecb_ecbee31,
     &               vnecb_ecbee32,vnecb_ecbee33,vnecb_ecbee34,
     &               vnecb_ecbee35,vnecb_ecbee36,vnecb_ecbee37,
     &               vnecb_ecbee38,vnecb_ecbee39,vnecb_ecbee40,
     &               vnecb_ecbee41,vnecb_ecbee42,vnecb_ecbee43,
     &               vnecb_ecbee44,vnecb_ecbee45,vnecb_ecbee46,
     &               vnecb_ecbee47,vnecb_ecbee48,vnecb_ecbee49
      common /amilcp_4f/vnecb_ecbee50,vnecb_ecbee51,vnecb_ecbee52,
     &               vnecb_ecbee53,vnecb_ecbee54,vnecb_ecbee55,
     &               vnecb_ecbee56,vnecb_ecbee57,vnecb_ecbee58,
     &               vnecb_ecbee59,vnecb_ecbee60,vnecb_ecbee61,
     &               vnecb_ecbee62,vnecb_ecbee63
