*     File et_ettt/inclet_etttp.h : Sat Mar 18 19:45:07 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfet_ettt2(4),pfet_ettt3(4),pfet_ettt4(4),
     &               pfet_ettt5(4),pfet_ettt6(4),pfet_ettt7(4),
     &               pfet_ettt8(4),pfet_ettt9(4),pfet_ettt10(4),
     &               pfet_ettt11(4),pfet_ettt12(4),pfet_ettt13(4),
     &               pfet_ettt14(4),pfet_ettt15(4),pfet_ettt16(4),
     &               pfet_ettt17(4),pfet_ettt18(4),pfet_ettt19(4),
     &               pfet_ettt20(4),pfet_ettt21(4),pfet_ettt22(4),
     &               pfet_ettt23(4),pfet_ettt24(4),pfet_ettt25(4),
     &               pfet_ettt26(4),pfet_ettt27(4),pfet_ettt28(4),
     &               pfet_ettt29(4),pfet_ettt30(4),pfet_ettt31(4),
     &               pfet_ettt32(4),pfet_ettt33(4),pfet_ettt34(4),
     &               pfet_ettt35(4),pfet_ettt36(4),pfet_ettt37(4),
     &               pfet_ettt38(4),pfet_ettt39(4),pfet_ettt40(4),
     &               pfet_ettt41(4),pfet_ettt42(4),pfet_ettt43(4),
     &               pfet_ettt44(4),pfet_ettt45(4),pfet_ettt46(4),
     &               pfet_ettt47(4),pfet_ettt48(4),pfet_ettt49(4)
      common /amilcd_4f/pfet_ettt50(4),pfet_ettt51(4),
     &               pfet_ettt52(4),pfet_ettt53(4),pfet_ettt54(4),
     &               pfet_ettt55(4),pfet_ettt56(4),pfet_ettt57(4),
     &               pfet_ettt58(4),pfet_ettt59(4),pfet_ettt60(4),
     &               pfet_ettt61(4),pfet_ettt62(4),pfet_ettt63(4)
      common /amilcp_4f/vnet_ettt2,vnet_ettt3,vnet_ettt4,vnet_ettt5,
     &               vnet_ettt6,vnet_ettt7,vnet_ettt8,vnet_ettt9,
     &               vnet_ettt10,vnet_ettt11,vnet_ettt12,vnet_ettt13,
     &               vnet_ettt14,vnet_ettt15,vnet_ettt16,vnet_ettt17,
     &               vnet_ettt18,vnet_ettt19,vnet_ettt20,vnet_ettt21,
     &               vnet_ettt22,vnet_ettt23,vnet_ettt24,vnet_ettt25,
     &               vnet_ettt26,vnet_ettt27,vnet_ettt28,vnet_ettt29,
     &               vnet_ettt30,vnet_ettt31,vnet_ettt32,vnet_ettt33,
     &               vnet_ettt34,vnet_ettt35,vnet_ettt36,vnet_ettt37,
     &               vnet_ettt38,vnet_ettt39,vnet_ettt40,vnet_ettt41,
     &               vnet_ettt42,vnet_ettt43,vnet_ettt44,vnet_ettt45,
     &               vnet_ettt46,vnet_ettt47,vnet_ettt48,vnet_ettt49,
     &               vnet_ettt50,vnet_ettt51,vnet_ettt52,vnet_ettt53,
     &               vnet_ettt54,vnet_ettt55,vnet_ettt56,vnet_ettt57,
     &               vnet_ettt58,vnet_ettt59,vnet_ettt60,vnet_ettt61,
     &               vnet_ettt62,vnet_ettt63
