*     File eb_ebmm/incleb_ebmm1.h : Sat Mar 18 19:45:05 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (neb_ebmmgraph =35)
      parameter (neb_ebmmextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (leb_ebmmag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (neb_ebmmgrpsq = neb_ebmmgraph*neb_ebmmgraph)
      common /aeb_ebmmmslct/jselg(neb_ebmmgraph),jgraph,jgluon,jhiggs

* Color string information
      common /aeb_ebmmmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aeb_ebmmmgrph/agcwrk(0:leb_ebmmag-1),agc(0:leb_ebmmag-1),
     &              aprop,ancp(neb_ebmmgraph),ansp(0:neb_ebmmgraph)
     &             ,cfmtx
      common /aeb_ebmmmgrpi/igraph(neb_ebmmgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aeb_ebmmmextr/peeb_ebmm1(4),peeb_ebmm2(4),peeb_ebmm3(4),
     &               peeb_ebmm4(4),peeb_ebmm5(4),peeb_ebmm6(4),
     &               prod(neb_ebmmextn, neb_ebmmextn)

      common /aeb_ebmmmextp/pteb_ebmm2u,exeb_ebmm2u,cfeb_ebmm2u,
     &               pteb_ebmm4m,exeb_ebmm4m,cfeb_ebmm4m,pteb_ebmm9u,
     &               exeb_ebmm9u,cfeb_ebmm9u,pteb_ebmm17m,exeb_ebmm17m,
     &               cfeb_ebmm17m,pteb_ebmm33n,exeb_ebmm33n,
     &               cfeb_ebmm33n,pteb_ebmm62n,exeb_ebmm62n,
     &               cfeb_ebmm62n

      real*8     pteb_ebmm2u(4,2), exeb_ebmm2u(1)
      complex*16 cfeb_ebmm2u(2,2)
      real*8     pteb_ebmm4m(4,2), exeb_ebmm4m(1)
      complex*16 cfeb_ebmm4m(2,2)
      real*8     pteb_ebmm9u(4,2), exeb_ebmm9u(1)
      complex*16 cfeb_ebmm9u(2,2)
      real*8     pteb_ebmm17m(4,2), exeb_ebmm17m(1)
      complex*16 cfeb_ebmm17m(2,2)
      real*8     pteb_ebmm33n(4,2), exeb_ebmm33n(1)
      complex*16 cfeb_ebmm33n(2,2)
      real*8     pteb_ebmm62n(4,2), exeb_ebmm62n(1)
      complex*16 cfeb_ebmm62n(2,2)

* Normalization
      common /aeb_ebmmmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aeb_ebmmmatbl/av, lt, indexg
      complex*16 av(0:leb_ebmmag-1)
      integer    lt(0:neb_ebmmextn), indexg(neb_ebmmextn)

* Spin average
      common/aeb_ebmmmspin/aspin,aident,jhs(neb_ebmmextn),
     &               jhe(neb_ebmmextn),jcpol(neb_ebmmextn),
     &               kperm(neb_ebmmextn)
