*     File eu_eutt/incleu_eutt1.h : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (neu_euttgraph =25)
      parameter (neu_euttextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (leu_euttag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (neu_euttgrpsq = neu_euttgraph*neu_euttgraph)
      common /aeu_euttmslct/jselg(neu_euttgraph),jgraph,jgluon,jhiggs

* Color string information
      common /aeu_euttmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aeu_euttmgrph/agcwrk(0:leu_euttag-1),agc(0:leu_euttag-1),
     &              aprop,ancp(neu_euttgraph),ansp(0:neu_euttgraph)
     &             ,cfmtx
      common /aeu_euttmgrpi/igraph(neu_euttgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aeu_euttmextr/peeu_eutt1(4),peeu_eutt2(4),peeu_eutt3(4),
     &               peeu_eutt4(4),peeu_eutt5(4),peeu_eutt6(4),
     &               prod(neu_euttextn, neu_euttextn)

      common /aeu_euttmextp/pteu_eutt2p,exeu_eutt2p,cfeu_eutt2p,
     &               pteu_eutt4m,exeu_eutt4m,cfeu_eutt4m,pteu_eutt9p,
     &               exeu_eutt9p,cfeu_eutt9p,pteu_eutt17m,exeu_eutt17m,
     &               cfeu_eutt17m,pteu_eutt33o,exeu_eutt33o,
     &               cfeu_eutt33o,pteu_eutt62o,exeu_eutt62o,
     &               cfeu_eutt62o

      real*8     pteu_eutt2p(4,2), exeu_eutt2p(1)
      complex*16 cfeu_eutt2p(2,2)
      real*8     pteu_eutt4m(4,2), exeu_eutt4m(1)
      complex*16 cfeu_eutt4m(2,2)
      real*8     pteu_eutt9p(4,2), exeu_eutt9p(1)
      complex*16 cfeu_eutt9p(2,2)
      real*8     pteu_eutt17m(4,2), exeu_eutt17m(1)
      complex*16 cfeu_eutt17m(2,2)
      real*8     pteu_eutt33o(4,2), exeu_eutt33o(1)
      complex*16 cfeu_eutt33o(2,2)
      real*8     pteu_eutt62o(4,2), exeu_eutt62o(1)
      complex*16 cfeu_eutt62o(2,2)

* Normalization
      common /aeu_euttmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aeu_euttmatbl/av, lt, indexg
      complex*16 av(0:leu_euttag-1)
      integer    lt(0:neu_euttextn), indexg(neu_euttextn)

* Spin average
      common/aeu_euttmspin/aspin,aident,jhs(neu_euttextn),
     &               jhe(neu_euttextn),jcpol(neu_euttextn),
     &               kperm(neu_euttextn)
