*     File et_etee/aet_eteekptbl.f : Sat Mar 18 19:45:06 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aet_eteekptbl
      implicit real*8(a-h,o-z)

      include 'inclet_etee1.h'
      include 'inclk.h'
      include 'inclet_eteep.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfet_etee2(i) =  + peet_etee1(i)
        pfet_etee4(i) =  + peet_etee2(i)
        pfet_etee6(i) =  + peet_etee1(i) + peet_etee2(i)
        pfet_etee8(i) =  - peet_etee3(i)
        pfet_etee10(i) =  + peet_etee1(i) - peet_etee3(i)
        pfet_etee12(i) =  + peet_etee2(i) - peet_etee3(i)
        pfet_etee14(i) =  + peet_etee1(i) + peet_etee2(i) - peet_etee3(i)
        pfet_etee16(i) =  - peet_etee4(i)
        pfet_etee18(i) =  + peet_etee1(i) - peet_etee4(i)
        pfet_etee20(i) =  + peet_etee2(i) - peet_etee4(i)
        pfet_etee22(i) =  + peet_etee1(i) + peet_etee2(i) - peet_etee4(i)
        pfet_etee24(i) =  - peet_etee3(i) - peet_etee4(i)
        pfet_etee26(i) =  + peet_etee1(i) - peet_etee3(i) - peet_etee4(i)
        pfet_etee28(i) =  + peet_etee2(i) - peet_etee3(i) - peet_etee4(i)
        pfet_etee30(i) =  + peet_etee5(i) + peet_etee6(i)
        pfet_etee32(i) =  - peet_etee5(i)
        pfet_etee34(i) =  + peet_etee1(i) - peet_etee5(i)
        pfet_etee36(i) =  + peet_etee2(i) - peet_etee5(i)
        pfet_etee38(i) =  + peet_etee1(i) + peet_etee2(i) - peet_etee5(i)
        pfet_etee40(i) =  - peet_etee3(i) - peet_etee5(i)
        pfet_etee42(i) =  + peet_etee1(i) - peet_etee3(i) - peet_etee5(i)
        pfet_etee44(i) =  + peet_etee2(i) - peet_etee3(i) - peet_etee5(i)
        pfet_etee46(i) =  + peet_etee4(i) + peet_etee6(i)
        pfet_etee48(i) =  - peet_etee4(i) - peet_etee5(i)
        pfet_etee50(i) =  + peet_etee1(i) - peet_etee4(i) - peet_etee5(i)
        pfet_etee52(i) =  + peet_etee2(i) - peet_etee4(i) - peet_etee5(i)
        pfet_etee54(i) =  + peet_etee3(i) + peet_etee6(i)
        pfet_etee56(i) =  - peet_etee3(i) - peet_etee4(i) - peet_etee5(i)
        pfet_etee58(i) =  - peet_etee2(i) + peet_etee6(i)
        pfet_etee60(i) =  - peet_etee1(i) + peet_etee6(i)
        pfet_etee62(i) =  + peet_etee6(i)

        pfet_etee3(i) = - pfet_etee2(i)
        pfet_etee5(i) = - pfet_etee4(i)
        pfet_etee7(i) = - pfet_etee6(i)
        pfet_etee9(i) = - pfet_etee8(i)
        pfet_etee11(i) = - pfet_etee10(i)
        pfet_etee13(i) = - pfet_etee12(i)
        pfet_etee15(i) = - pfet_etee14(i)
        pfet_etee17(i) = - pfet_etee16(i)
        pfet_etee19(i) = - pfet_etee18(i)
        pfet_etee21(i) = - pfet_etee20(i)
        pfet_etee23(i) = - pfet_etee22(i)
        pfet_etee25(i) = - pfet_etee24(i)
        pfet_etee27(i) = - pfet_etee26(i)
        pfet_etee29(i) = - pfet_etee28(i)
        pfet_etee31(i) = - pfet_etee30(i)
        pfet_etee33(i) = - pfet_etee32(i)
        pfet_etee35(i) = - pfet_etee34(i)
        pfet_etee37(i) = - pfet_etee36(i)
        pfet_etee39(i) = - pfet_etee38(i)
        pfet_etee41(i) = - pfet_etee40(i)
        pfet_etee43(i) = - pfet_etee42(i)
        pfet_etee45(i) = - pfet_etee44(i)
        pfet_etee47(i) = - pfet_etee46(i)
        pfet_etee49(i) = - pfet_etee48(i)
        pfet_etee51(i) = - pfet_etee50(i)
        pfet_etee53(i) = - pfet_etee52(i)
        pfet_etee55(i) = - pfet_etee54(i)
        pfet_etee57(i) = - pfet_etee56(i)
        pfet_etee59(i) = - pfet_etee58(i)
        pfet_etee61(i) = - pfet_etee60(i)
        pfet_etee63(i) = - pfet_etee62(i)
  100 continue

      vnet_etee2 =  + amass2(1)
      vnet_etee4 =  + amass2(2)
      vnet_etee6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vnet_etee8 =  + amass2(3)
      vnet_etee10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vnet_etee12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vnet_etee14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vnet_etee16 =  + amass2(4)
      vnet_etee18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vnet_etee20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vnet_etee22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vnet_etee24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vnet_etee26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vnet_etee28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vnet_etee30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vnet_etee32 =  + amass2(5)
      vnet_etee34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vnet_etee36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vnet_etee38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vnet_etee40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vnet_etee42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vnet_etee44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vnet_etee46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vnet_etee48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vnet_etee50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vnet_etee52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vnet_etee54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vnet_etee56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vnet_etee58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vnet_etee60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vnet_etee62 =  + amass2(6)
      vnet_etee3 = vnet_etee2
      vnet_etee5 = vnet_etee4
      vnet_etee7 = vnet_etee6
      vnet_etee9 = vnet_etee8
      vnet_etee11 = vnet_etee10
      vnet_etee13 = vnet_etee12
      vnet_etee15 = vnet_etee14
      vnet_etee17 = vnet_etee16
      vnet_etee19 = vnet_etee18
      vnet_etee21 = vnet_etee20
      vnet_etee23 = vnet_etee22
      vnet_etee25 = vnet_etee24
      vnet_etee27 = vnet_etee26
      vnet_etee29 = vnet_etee28
      vnet_etee31 = vnet_etee30
      vnet_etee33 = vnet_etee32
      vnet_etee35 = vnet_etee34
      vnet_etee37 = vnet_etee36
      vnet_etee39 = vnet_etee38
      vnet_etee41 = vnet_etee40
      vnet_etee43 = vnet_etee42
      vnet_etee45 = vnet_etee44
      vnet_etee47 = vnet_etee46
      vnet_etee49 = vnet_etee48
      vnet_etee51 = vnet_etee50
      vnet_etee53 = vnet_etee52
      vnet_etee55 = vnet_etee54
      vnet_etee57 = vnet_etee56
      vnet_etee59 = vnet_etee58
      vnet_etee61 = vnet_etee60
      vnet_etee63 = vnet_etee62
      return
      end
