*     File etb_etbee/aetb_etbeekptbl.f : Sat Mar 18 19:45:07 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aetb_etbeekptbl
      implicit real*8(a-h,o-z)

      include 'incletb_etbee1.h'
      include 'inclk.h'
      include 'incletb_etbeep.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfetb_etbee2(i) =  + peetb_etbee1(i)
        pfetb_etbee4(i) =  + peetb_etbee2(i)
        pfetb_etbee6(i) =  + peetb_etbee1(i) + peetb_etbee2(i)
        pfetb_etbee8(i) =  - peetb_etbee3(i)
        pfetb_etbee10(i) =  + peetb_etbee1(i) - peetb_etbee3(i)
        pfetb_etbee12(i) =  + peetb_etbee2(i) - peetb_etbee3(i)
        pfetb_etbee14(i) =  + peetb_etbee1(i) + peetb_etbee2(i) - peetb_etbee3(i)
        pfetb_etbee16(i) =  - peetb_etbee4(i)
        pfetb_etbee18(i) =  + peetb_etbee1(i) - peetb_etbee4(i)
        pfetb_etbee20(i) =  + peetb_etbee2(i) - peetb_etbee4(i)
        pfetb_etbee22(i) =  + peetb_etbee1(i) + peetb_etbee2(i) - peetb_etbee4(i)
        pfetb_etbee24(i) =  - peetb_etbee3(i) - peetb_etbee4(i)
        pfetb_etbee26(i) =  + peetb_etbee1(i) - peetb_etbee3(i) - peetb_etbee4(i)
        pfetb_etbee28(i) =  + peetb_etbee2(i) - peetb_etbee3(i) - peetb_etbee4(i)
        pfetb_etbee30(i) =  + peetb_etbee5(i) + peetb_etbee6(i)
        pfetb_etbee32(i) =  - peetb_etbee5(i)
        pfetb_etbee34(i) =  + peetb_etbee1(i) - peetb_etbee5(i)
        pfetb_etbee36(i) =  + peetb_etbee2(i) - peetb_etbee5(i)
        pfetb_etbee38(i) =  + peetb_etbee1(i) + peetb_etbee2(i) - peetb_etbee5(i)
        pfetb_etbee40(i) =  - peetb_etbee3(i) - peetb_etbee5(i)
        pfetb_etbee42(i) =  + peetb_etbee1(i) - peetb_etbee3(i) - peetb_etbee5(i)
        pfetb_etbee44(i) =  + peetb_etbee2(i) - peetb_etbee3(i) - peetb_etbee5(i)
        pfetb_etbee46(i) =  + peetb_etbee4(i) + peetb_etbee6(i)
        pfetb_etbee48(i) =  - peetb_etbee4(i) - peetb_etbee5(i)
        pfetb_etbee50(i) =  + peetb_etbee1(i) - peetb_etbee4(i) - peetb_etbee5(i)
        pfetb_etbee52(i) =  + peetb_etbee2(i) - peetb_etbee4(i) - peetb_etbee5(i)
        pfetb_etbee54(i) =  + peetb_etbee3(i) + peetb_etbee6(i)
        pfetb_etbee56(i) =  - peetb_etbee3(i) - peetb_etbee4(i) - peetb_etbee5(i)
        pfetb_etbee58(i) =  - peetb_etbee2(i) + peetb_etbee6(i)
        pfetb_etbee60(i) =  - peetb_etbee1(i) + peetb_etbee6(i)
        pfetb_etbee62(i) =  + peetb_etbee6(i)

        pfetb_etbee3(i) = - pfetb_etbee2(i)
        pfetb_etbee5(i) = - pfetb_etbee4(i)
        pfetb_etbee7(i) = - pfetb_etbee6(i)
        pfetb_etbee9(i) = - pfetb_etbee8(i)
        pfetb_etbee11(i) = - pfetb_etbee10(i)
        pfetb_etbee13(i) = - pfetb_etbee12(i)
        pfetb_etbee15(i) = - pfetb_etbee14(i)
        pfetb_etbee17(i) = - pfetb_etbee16(i)
        pfetb_etbee19(i) = - pfetb_etbee18(i)
        pfetb_etbee21(i) = - pfetb_etbee20(i)
        pfetb_etbee23(i) = - pfetb_etbee22(i)
        pfetb_etbee25(i) = - pfetb_etbee24(i)
        pfetb_etbee27(i) = - pfetb_etbee26(i)
        pfetb_etbee29(i) = - pfetb_etbee28(i)
        pfetb_etbee31(i) = - pfetb_etbee30(i)
        pfetb_etbee33(i) = - pfetb_etbee32(i)
        pfetb_etbee35(i) = - pfetb_etbee34(i)
        pfetb_etbee37(i) = - pfetb_etbee36(i)
        pfetb_etbee39(i) = - pfetb_etbee38(i)
        pfetb_etbee41(i) = - pfetb_etbee40(i)
        pfetb_etbee43(i) = - pfetb_etbee42(i)
        pfetb_etbee45(i) = - pfetb_etbee44(i)
        pfetb_etbee47(i) = - pfetb_etbee46(i)
        pfetb_etbee49(i) = - pfetb_etbee48(i)
        pfetb_etbee51(i) = - pfetb_etbee50(i)
        pfetb_etbee53(i) = - pfetb_etbee52(i)
        pfetb_etbee55(i) = - pfetb_etbee54(i)
        pfetb_etbee57(i) = - pfetb_etbee56(i)
        pfetb_etbee59(i) = - pfetb_etbee58(i)
        pfetb_etbee61(i) = - pfetb_etbee60(i)
        pfetb_etbee63(i) = - pfetb_etbee62(i)
  100 continue

      vnetb_etbee2 =  + amass2(1)
      vnetb_etbee4 =  + amass2(2)
      vnetb_etbee6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vnetb_etbee8 =  + amass2(3)
      vnetb_etbee10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vnetb_etbee12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vnetb_etbee14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vnetb_etbee16 =  + amass2(4)
      vnetb_etbee18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vnetb_etbee20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vnetb_etbee22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vnetb_etbee24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vnetb_etbee26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vnetb_etbee28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vnetb_etbee30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vnetb_etbee32 =  + amass2(5)
      vnetb_etbee34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vnetb_etbee36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vnetb_etbee38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vnetb_etbee40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vnetb_etbee42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vnetb_etbee44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vnetb_etbee46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vnetb_etbee48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vnetb_etbee50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vnetb_etbee52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vnetb_etbee54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vnetb_etbee56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vnetb_etbee58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vnetb_etbee60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vnetb_etbee62 =  + amass2(6)
      vnetb_etbee3 = vnetb_etbee2
      vnetb_etbee5 = vnetb_etbee4
      vnetb_etbee7 = vnetb_etbee6
      vnetb_etbee9 = vnetb_etbee8
      vnetb_etbee11 = vnetb_etbee10
      vnetb_etbee13 = vnetb_etbee12
      vnetb_etbee15 = vnetb_etbee14
      vnetb_etbee17 = vnetb_etbee16
      vnetb_etbee19 = vnetb_etbee18
      vnetb_etbee21 = vnetb_etbee20
      vnetb_etbee23 = vnetb_etbee22
      vnetb_etbee25 = vnetb_etbee24
      vnetb_etbee27 = vnetb_etbee26
      vnetb_etbee29 = vnetb_etbee28
      vnetb_etbee31 = vnetb_etbee30
      vnetb_etbee33 = vnetb_etbee32
      vnetb_etbee35 = vnetb_etbee34
      vnetb_etbee37 = vnetb_etbee36
      vnetb_etbee39 = vnetb_etbee38
      vnetb_etbee41 = vnetb_etbee40
      vnetb_etbee43 = vnetb_etbee42
      vnetb_etbee45 = vnetb_etbee44
      vnetb_etbee47 = vnetb_etbee46
      vnetb_etbee49 = vnetb_etbee48
      vnetb_etbee51 = vnetb_etbee50
      vnetb_etbee53 = vnetb_etbee52
      vnetb_etbee55 = vnetb_etbee54
      vnetb_etbee57 = vnetb_etbee56
      vnetb_etbee59 = vnetb_etbee58
      vnetb_etbee61 = vnetb_etbee60
      vnetb_etbee63 = vnetb_etbee62
      return
      end
