*     File etb_etbee/incletb_etbee1.h : Sat Mar 18 19:45:07 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (netb_etbeegraph =50)
      parameter (netb_etbeeextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (letb_etbeeag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (netb_etbeegrpsq = netb_etbeegraph*netb_etbeegraph)
      common /aetb_etbeemslct/jselg(netb_etbeegraph),jgraph,jgluon,
     &               jhiggs

* Color string information
      common /aetb_etbeemcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aetb_etbeemgrph/agcwrk(0:letb_etbeeag-1),agc(0:letb_etbeeag-1),
     &              aprop,ancp(netb_etbeegraph),ansp(0:netb_etbeegraph)
     &             ,cfmtx
      common /aetb_etbeemgrpi/igraph(netb_etbeegraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aetb_etbeemextr/peetb_etbee1(4),peetb_etbee2(4),
     &               peetb_etbee3(4),peetb_etbee4(4),peetb_etbee5(4),
     &               peetb_etbee6(4),
     &               prod(netb_etbeeextn, netb_etbeeextn)

      common /aetb_etbeemextp/ptetb_etbee2r,exetb_etbee2r,cfetb_etbee2r,
     &               ptetb_etbee4m,exetb_etbee4m,cfetb_etbee4m,
     &               ptetb_etbee9r,exetb_etbee9r,cfetb_etbee9r,
     &               ptetb_etbee17m,exetb_etbee17m,cfetb_etbee17m,
     &               ptetb_etbee33m,exetb_etbee33m,cfetb_etbee33m,
     &               ptetb_etbee62m,exetb_etbee62m,cfetb_etbee62m

      real*8     ptetb_etbee2r(4,2), exetb_etbee2r(1)
      complex*16 cfetb_etbee2r(2,2)
      real*8     ptetb_etbee4m(4,2), exetb_etbee4m(1)
      complex*16 cfetb_etbee4m(2,2)
      real*8     ptetb_etbee9r(4,2), exetb_etbee9r(1)
      complex*16 cfetb_etbee9r(2,2)
      real*8     ptetb_etbee17m(4,2), exetb_etbee17m(1)
      complex*16 cfetb_etbee17m(2,2)
      real*8     ptetb_etbee33m(4,2), exetb_etbee33m(1)
      complex*16 cfetb_etbee33m(2,2)
      real*8     ptetb_etbee62m(4,2), exetb_etbee62m(1)
      complex*16 cfetb_etbee62m(2,2)

* Normalization
      common /aetb_etbeemdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aetb_etbeematbl/av, lt, indexg
      complex*16 av(0:letb_etbeeag-1)
      integer    lt(0:netb_etbeeextn), indexg(netb_etbeeextn)

* Spin average
      common/aetb_etbeemspin/aspin,aident,jhs(netb_etbeeextn),
     &               jhe(netb_etbeeextn),jcpol(netb_etbeeextn),
     &               kperm(netb_etbeeextn)
