*     File ebb_ebbee/inclebb_ebbeep.h : Sat Mar 18 19:45:05 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfebb_ebbee2(4),pfebb_ebbee3(4),
     &               pfebb_ebbee4(4),pfebb_ebbee5(4),pfebb_ebbee6(4),
     &               pfebb_ebbee7(4),pfebb_ebbee8(4),pfebb_ebbee9(4),
     &               pfebb_ebbee10(4),pfebb_ebbee11(4),pfebb_ebbee12(4),
     &               pfebb_ebbee13(4),pfebb_ebbee14(4),pfebb_ebbee15(4),
     &               pfebb_ebbee16(4),pfebb_ebbee17(4),pfebb_ebbee18(4),
     &               pfebb_ebbee19(4),pfebb_ebbee20(4),pfebb_ebbee21(4),
     &               pfebb_ebbee22(4),pfebb_ebbee23(4),pfebb_ebbee24(4),
     &               pfebb_ebbee25(4),pfebb_ebbee26(4),pfebb_ebbee27(4),
     &               pfebb_ebbee28(4),pfebb_ebbee29(4),pfebb_ebbee30(4),
     &               pfebb_ebbee31(4),pfebb_ebbee32(4),pfebb_ebbee33(4),
     &               pfebb_ebbee34(4),pfebb_ebbee35(4),pfebb_ebbee36(4),
     &               pfebb_ebbee37(4),pfebb_ebbee38(4),pfebb_ebbee39(4),
     &               pfebb_ebbee40(4),pfebb_ebbee41(4),pfebb_ebbee42(4),
     &               pfebb_ebbee43(4),pfebb_ebbee44(4),pfebb_ebbee45(4),
     &               pfebb_ebbee46(4),pfebb_ebbee47(4),pfebb_ebbee48(4)
      common /amilcd_4f/pfebb_ebbee49(4),pfebb_ebbee50(4),
     &               pfebb_ebbee51(4),pfebb_ebbee52(4),pfebb_ebbee53(4),
     &               pfebb_ebbee54(4),pfebb_ebbee55(4),pfebb_ebbee56(4),
     &               pfebb_ebbee57(4),pfebb_ebbee58(4),pfebb_ebbee59(4),
     &               pfebb_ebbee60(4),pfebb_ebbee61(4),pfebb_ebbee62(4),
     &               pfebb_ebbee63(4)
      common /amilcp_4f/vnebb_ebbee2,vnebb_ebbee3,vnebb_ebbee4,
     &               vnebb_ebbee5,vnebb_ebbee6,vnebb_ebbee7,
     &               vnebb_ebbee8,vnebb_ebbee9,vnebb_ebbee10,
     &               vnebb_ebbee11,vnebb_ebbee12,vnebb_ebbee13,
     &               vnebb_ebbee14,vnebb_ebbee15,vnebb_ebbee16,
     &               vnebb_ebbee17,vnebb_ebbee18,vnebb_ebbee19,
     &               vnebb_ebbee20,vnebb_ebbee21,vnebb_ebbee22,
     &               vnebb_ebbee23,vnebb_ebbee24,vnebb_ebbee25,
     &               vnebb_ebbee26,vnebb_ebbee27,vnebb_ebbee28,
     &               vnebb_ebbee29,vnebb_ebbee30,vnebb_ebbee31,
     &               vnebb_ebbee32,vnebb_ebbee33,vnebb_ebbee34,
     &               vnebb_ebbee35,vnebb_ebbee36,vnebb_ebbee37,
     &               vnebb_ebbee38,vnebb_ebbee39,vnebb_ebbee40,
     &               vnebb_ebbee41,vnebb_ebbee42,vnebb_ebbee43,
     &               vnebb_ebbee44,vnebb_ebbee45,vnebb_ebbee46,
     &               vnebb_ebbee47,vnebb_ebbee48,vnebb_ebbee49
      common /amilcp_4f/vnebb_ebbee50,vnebb_ebbee51,vnebb_ebbee52,
     &               vnebb_ebbee53,vnebb_ebbee54,vnebb_ebbee55,
     &               vnebb_ebbee56,vnebb_ebbee57,vnebb_ebbee58,
     &               vnebb_ebbee59,vnebb_ebbee60,vnebb_ebbee61,
     &               vnebb_ebbee62,vnebb_ebbee63
