*     File ep_eXee/aep_eXeekptbl.f : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aep_eXeekptbl
      implicit real*8(a-h,o-z)

      include 'inclep_eXee1.h'
      include 'inclk.h'
      include 'inclep_eXeep.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfep_eXee2(i) =  + peep_eXee1(i)
        pfep_eXee4(i) =  + peep_eXee2(i)
        pfep_eXee6(i) =  + peep_eXee1(i) + peep_eXee2(i)
        pfep_eXee8(i) =  - peep_eXee3(i)
        pfep_eXee10(i) =  + peep_eXee1(i) - peep_eXee3(i)
        pfep_eXee12(i) =  + peep_eXee2(i) - peep_eXee3(i)
        pfep_eXee14(i) =  + peep_eXee1(i) + peep_eXee2(i) - peep_eXee3(i)
        pfep_eXee16(i) =  - peep_eXee4(i)
        pfep_eXee18(i) =  + peep_eXee1(i) - peep_eXee4(i)
        pfep_eXee20(i) =  + peep_eXee2(i) - peep_eXee4(i)
        pfep_eXee22(i) =  + peep_eXee1(i) + peep_eXee2(i) - peep_eXee4(i)
        pfep_eXee24(i) =  - peep_eXee3(i) - peep_eXee4(i)
        pfep_eXee26(i) =  + peep_eXee1(i) - peep_eXee3(i) - peep_eXee4(i)
        pfep_eXee28(i) =  + peep_eXee2(i) - peep_eXee3(i) - peep_eXee4(i)
        pfep_eXee30(i) =  + peep_eXee5(i) + peep_eXee6(i)
        pfep_eXee32(i) =  - peep_eXee5(i)
        pfep_eXee34(i) =  + peep_eXee1(i) - peep_eXee5(i)
        pfep_eXee36(i) =  + peep_eXee2(i) - peep_eXee5(i)
        pfep_eXee38(i) =  + peep_eXee1(i) + peep_eXee2(i) - peep_eXee5(i)
        pfep_eXee40(i) =  - peep_eXee3(i) - peep_eXee5(i)
        pfep_eXee42(i) =  + peep_eXee1(i) - peep_eXee3(i) - peep_eXee5(i)
        pfep_eXee44(i) =  + peep_eXee2(i) - peep_eXee3(i) - peep_eXee5(i)
        pfep_eXee46(i) =  + peep_eXee4(i) + peep_eXee6(i)
        pfep_eXee48(i) =  - peep_eXee4(i) - peep_eXee5(i)
        pfep_eXee50(i) =  + peep_eXee1(i) - peep_eXee4(i) - peep_eXee5(i)
        pfep_eXee52(i) =  + peep_eXee2(i) - peep_eXee4(i) - peep_eXee5(i)
        pfep_eXee54(i) =  + peep_eXee3(i) + peep_eXee6(i)
        pfep_eXee56(i) =  - peep_eXee3(i) - peep_eXee4(i) - peep_eXee5(i)
        pfep_eXee58(i) =  - peep_eXee2(i) + peep_eXee6(i)
        pfep_eXee60(i) =  - peep_eXee1(i) + peep_eXee6(i)
        pfep_eXee62(i) =  + peep_eXee6(i)

        pfep_eXee3(i) = - pfep_eXee2(i)
        pfep_eXee5(i) = - pfep_eXee4(i)
        pfep_eXee7(i) = - pfep_eXee6(i)
        pfep_eXee9(i) = - pfep_eXee8(i)
        pfep_eXee11(i) = - pfep_eXee10(i)
        pfep_eXee13(i) = - pfep_eXee12(i)
        pfep_eXee15(i) = - pfep_eXee14(i)
        pfep_eXee17(i) = - pfep_eXee16(i)
        pfep_eXee19(i) = - pfep_eXee18(i)
        pfep_eXee21(i) = - pfep_eXee20(i)
        pfep_eXee23(i) = - pfep_eXee22(i)
        pfep_eXee25(i) = - pfep_eXee24(i)
        pfep_eXee27(i) = - pfep_eXee26(i)
        pfep_eXee29(i) = - pfep_eXee28(i)
        pfep_eXee31(i) = - pfep_eXee30(i)
        pfep_eXee33(i) = - pfep_eXee32(i)
        pfep_eXee35(i) = - pfep_eXee34(i)
        pfep_eXee37(i) = - pfep_eXee36(i)
        pfep_eXee39(i) = - pfep_eXee38(i)
        pfep_eXee41(i) = - pfep_eXee40(i)
        pfep_eXee43(i) = - pfep_eXee42(i)
        pfep_eXee45(i) = - pfep_eXee44(i)
        pfep_eXee47(i) = - pfep_eXee46(i)
        pfep_eXee49(i) = - pfep_eXee48(i)
        pfep_eXee51(i) = - pfep_eXee50(i)
        pfep_eXee53(i) = - pfep_eXee52(i)
        pfep_eXee55(i) = - pfep_eXee54(i)
        pfep_eXee57(i) = - pfep_eXee56(i)
        pfep_eXee59(i) = - pfep_eXee58(i)
        pfep_eXee61(i) = - pfep_eXee60(i)
        pfep_eXee63(i) = - pfep_eXee62(i)
  100 continue

      vnep_eXee2 =  + amass2(1)
      vnep_eXee4 =  + amass2(2)
      vnep_eXee6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vnep_eXee8 =  + amass2(3)
      vnep_eXee10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vnep_eXee12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vnep_eXee14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vnep_eXee16 =  + amass2(4)
      vnep_eXee18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vnep_eXee20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vnep_eXee22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vnep_eXee24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vnep_eXee26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vnep_eXee28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vnep_eXee30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vnep_eXee32 =  + amass2(5)
      vnep_eXee34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vnep_eXee36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vnep_eXee38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vnep_eXee40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vnep_eXee42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vnep_eXee44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vnep_eXee46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vnep_eXee48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vnep_eXee50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vnep_eXee52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vnep_eXee54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vnep_eXee56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vnep_eXee58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vnep_eXee60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vnep_eXee62 =  + amass2(6)
      vnep_eXee3 = vnep_eXee2
      vnep_eXee5 = vnep_eXee4
      vnep_eXee7 = vnep_eXee6
      vnep_eXee9 = vnep_eXee8
      vnep_eXee11 = vnep_eXee10
      vnep_eXee13 = vnep_eXee12
      vnep_eXee15 = vnep_eXee14
      vnep_eXee17 = vnep_eXee16
      vnep_eXee19 = vnep_eXee18
      vnep_eXee21 = vnep_eXee20
      vnep_eXee23 = vnep_eXee22
      vnep_eXee25 = vnep_eXee24
      vnep_eXee27 = vnep_eXee26
      vnep_eXee29 = vnep_eXee28
      vnep_eXee31 = vnep_eXee30
      vnep_eXee33 = vnep_eXee32
      vnep_eXee35 = vnep_eXee34
      vnep_eXee37 = vnep_eXee36
      vnep_eXee39 = vnep_eXee38
      vnep_eXee41 = vnep_eXee40
      vnep_eXee43 = vnep_eXee42
      vnep_eXee45 = vnep_eXee44
      vnep_eXee47 = vnep_eXee46
      vnep_eXee49 = vnep_eXee48
      vnep_eXee51 = vnep_eXee50
      vnep_eXee53 = vnep_eXee52
      vnep_eXee55 = vnep_eXee54
      vnep_eXee57 = vnep_eXee56
      vnep_eXee59 = vnep_eXee58
      vnep_eXee61 = vnep_eXee60
      vnep_eXee63 = vnep_eXee62
      return
      end
