*     File ep_eXee/inclep_eXeep.h : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfep_eXee2(4),pfep_eXee3(4),pfep_eXee4(4),
     &               pfep_eXee5(4),pfep_eXee6(4),pfep_eXee7(4),
     &               pfep_eXee8(4),pfep_eXee9(4),pfep_eXee10(4),
     &               pfep_eXee11(4),pfep_eXee12(4),pfep_eXee13(4),
     &               pfep_eXee14(4),pfep_eXee15(4),pfep_eXee16(4),
     &               pfep_eXee17(4),pfep_eXee18(4),pfep_eXee19(4),
     &               pfep_eXee20(4),pfep_eXee21(4),pfep_eXee22(4),
     &               pfep_eXee23(4),pfep_eXee24(4),pfep_eXee25(4),
     &               pfep_eXee26(4),pfep_eXee27(4),pfep_eXee28(4),
     &               pfep_eXee29(4),pfep_eXee30(4),pfep_eXee31(4),
     &               pfep_eXee32(4),pfep_eXee33(4),pfep_eXee34(4),
     &               pfep_eXee35(4),pfep_eXee36(4),pfep_eXee37(4),
     &               pfep_eXee38(4),pfep_eXee39(4),pfep_eXee40(4),
     &               pfep_eXee41(4),pfep_eXee42(4),pfep_eXee43(4),
     &               pfep_eXee44(4),pfep_eXee45(4),pfep_eXee46(4),
     &               pfep_eXee47(4),pfep_eXee48(4),pfep_eXee49(4)
      common /amilcd_4f/pfep_eXee50(4),pfep_eXee51(4),
     &               pfep_eXee52(4),pfep_eXee53(4),pfep_eXee54(4),
     &               pfep_eXee55(4),pfep_eXee56(4),pfep_eXee57(4),
     &               pfep_eXee58(4),pfep_eXee59(4),pfep_eXee60(4),
     &               pfep_eXee61(4),pfep_eXee62(4),pfep_eXee63(4)
      common /amilcp_4f/vnep_eXee2,vnep_eXee3,vnep_eXee4,vnep_eXee5,
     &               vnep_eXee6,vnep_eXee7,vnep_eXee8,vnep_eXee9,
     &               vnep_eXee10,vnep_eXee11,vnep_eXee12,vnep_eXee13,
     &               vnep_eXee14,vnep_eXee15,vnep_eXee16,vnep_eXee17,
     &               vnep_eXee18,vnep_eXee19,vnep_eXee20,vnep_eXee21,
     &               vnep_eXee22,vnep_eXee23,vnep_eXee24,vnep_eXee25,
     &               vnep_eXee26,vnep_eXee27,vnep_eXee28,vnep_eXee29,
     &               vnep_eXee30,vnep_eXee31,vnep_eXee32,vnep_eXee33,
     &               vnep_eXee34,vnep_eXee35,vnep_eXee36,vnep_eXee37,
     &               vnep_eXee38,vnep_eXee39,vnep_eXee40,vnep_eXee41,
     &               vnep_eXee42,vnep_eXee43,vnep_eXee44,vnep_eXee45,
     &               vnep_eXee46,vnep_eXee47,vnep_eXee48,vnep_eXee49,
     &               vnep_eXee50,vnep_eXee51,vnep_eXee52,vnep_eXee53,
     &               vnep_eXee54,vnep_eXee55,vnep_eXee56,vnep_eXee57,
     &               vnep_eXee58,vnep_eXee59,vnep_eXee60,vnep_eXee61,
     &               vnep_eXee62,vnep_eXee63
