*     File ep_eXmm/aep_eXmmkptbl.f : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aep_eXmmkptbl
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfep_eXmm2(i) =  + peep_eXmm1(i)
        pfep_eXmm4(i) =  + peep_eXmm2(i)
        pfep_eXmm6(i) =  + peep_eXmm1(i) + peep_eXmm2(i)
        pfep_eXmm8(i) =  - peep_eXmm3(i)
        pfep_eXmm10(i) =  + peep_eXmm1(i) - peep_eXmm3(i)
        pfep_eXmm12(i) =  + peep_eXmm2(i) - peep_eXmm3(i)
        pfep_eXmm14(i) =  + peep_eXmm1(i) + peep_eXmm2(i) - peep_eXmm3(i)
        pfep_eXmm16(i) =  - peep_eXmm4(i)
        pfep_eXmm18(i) =  + peep_eXmm1(i) - peep_eXmm4(i)
        pfep_eXmm20(i) =  + peep_eXmm2(i) - peep_eXmm4(i)
        pfep_eXmm22(i) =  + peep_eXmm1(i) + peep_eXmm2(i) - peep_eXmm4(i)
        pfep_eXmm24(i) =  - peep_eXmm3(i) - peep_eXmm4(i)
        pfep_eXmm26(i) =  + peep_eXmm1(i) - peep_eXmm3(i) - peep_eXmm4(i)
        pfep_eXmm28(i) =  + peep_eXmm2(i) - peep_eXmm3(i) - peep_eXmm4(i)
        pfep_eXmm30(i) =  + peep_eXmm5(i) + peep_eXmm6(i)
        pfep_eXmm32(i) =  - peep_eXmm5(i)
        pfep_eXmm34(i) =  + peep_eXmm1(i) - peep_eXmm5(i)
        pfep_eXmm36(i) =  + peep_eXmm2(i) - peep_eXmm5(i)
        pfep_eXmm38(i) =  + peep_eXmm1(i) + peep_eXmm2(i) - peep_eXmm5(i)
        pfep_eXmm40(i) =  - peep_eXmm3(i) - peep_eXmm5(i)
        pfep_eXmm42(i) =  + peep_eXmm1(i) - peep_eXmm3(i) - peep_eXmm5(i)
        pfep_eXmm44(i) =  + peep_eXmm2(i) - peep_eXmm3(i) - peep_eXmm5(i)
        pfep_eXmm46(i) =  + peep_eXmm4(i) + peep_eXmm6(i)
        pfep_eXmm48(i) =  - peep_eXmm4(i) - peep_eXmm5(i)
        pfep_eXmm50(i) =  + peep_eXmm1(i) - peep_eXmm4(i) - peep_eXmm5(i)
        pfep_eXmm52(i) =  + peep_eXmm2(i) - peep_eXmm4(i) - peep_eXmm5(i)
        pfep_eXmm54(i) =  + peep_eXmm3(i) + peep_eXmm6(i)
        pfep_eXmm56(i) =  - peep_eXmm3(i) - peep_eXmm4(i) - peep_eXmm5(i)
        pfep_eXmm58(i) =  - peep_eXmm2(i) + peep_eXmm6(i)
        pfep_eXmm60(i) =  - peep_eXmm1(i) + peep_eXmm6(i)
        pfep_eXmm62(i) =  + peep_eXmm6(i)

        pfep_eXmm3(i) = - pfep_eXmm2(i)
        pfep_eXmm5(i) = - pfep_eXmm4(i)
        pfep_eXmm7(i) = - pfep_eXmm6(i)
        pfep_eXmm9(i) = - pfep_eXmm8(i)
        pfep_eXmm11(i) = - pfep_eXmm10(i)
        pfep_eXmm13(i) = - pfep_eXmm12(i)
        pfep_eXmm15(i) = - pfep_eXmm14(i)
        pfep_eXmm17(i) = - pfep_eXmm16(i)
        pfep_eXmm19(i) = - pfep_eXmm18(i)
        pfep_eXmm21(i) = - pfep_eXmm20(i)
        pfep_eXmm23(i) = - pfep_eXmm22(i)
        pfep_eXmm25(i) = - pfep_eXmm24(i)
        pfep_eXmm27(i) = - pfep_eXmm26(i)
        pfep_eXmm29(i) = - pfep_eXmm28(i)
        pfep_eXmm31(i) = - pfep_eXmm30(i)
        pfep_eXmm33(i) = - pfep_eXmm32(i)
        pfep_eXmm35(i) = - pfep_eXmm34(i)
        pfep_eXmm37(i) = - pfep_eXmm36(i)
        pfep_eXmm39(i) = - pfep_eXmm38(i)
        pfep_eXmm41(i) = - pfep_eXmm40(i)
        pfep_eXmm43(i) = - pfep_eXmm42(i)
        pfep_eXmm45(i) = - pfep_eXmm44(i)
        pfep_eXmm47(i) = - pfep_eXmm46(i)
        pfep_eXmm49(i) = - pfep_eXmm48(i)
        pfep_eXmm51(i) = - pfep_eXmm50(i)
        pfep_eXmm53(i) = - pfep_eXmm52(i)
        pfep_eXmm55(i) = - pfep_eXmm54(i)
        pfep_eXmm57(i) = - pfep_eXmm56(i)
        pfep_eXmm59(i) = - pfep_eXmm58(i)
        pfep_eXmm61(i) = - pfep_eXmm60(i)
        pfep_eXmm63(i) = - pfep_eXmm62(i)
  100 continue

      vnep_eXmm2 =  + amass2(1)
      vnep_eXmm4 =  + amass2(2)
      vnep_eXmm6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vnep_eXmm8 =  + amass2(3)
      vnep_eXmm10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vnep_eXmm12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vnep_eXmm14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vnep_eXmm16 =  + amass2(4)
      vnep_eXmm18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vnep_eXmm20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vnep_eXmm22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vnep_eXmm24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vnep_eXmm26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vnep_eXmm28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vnep_eXmm30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vnep_eXmm32 =  + amass2(5)
      vnep_eXmm34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vnep_eXmm36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vnep_eXmm38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vnep_eXmm40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vnep_eXmm42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vnep_eXmm44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vnep_eXmm46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vnep_eXmm48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vnep_eXmm50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vnep_eXmm52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vnep_eXmm54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vnep_eXmm56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vnep_eXmm58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vnep_eXmm60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vnep_eXmm62 =  + amass2(6)
      vnep_eXmm3 = vnep_eXmm2
      vnep_eXmm5 = vnep_eXmm4
      vnep_eXmm7 = vnep_eXmm6
      vnep_eXmm9 = vnep_eXmm8
      vnep_eXmm11 = vnep_eXmm10
      vnep_eXmm13 = vnep_eXmm12
      vnep_eXmm15 = vnep_eXmm14
      vnep_eXmm17 = vnep_eXmm16
      vnep_eXmm19 = vnep_eXmm18
      vnep_eXmm21 = vnep_eXmm20
      vnep_eXmm23 = vnep_eXmm22
      vnep_eXmm25 = vnep_eXmm24
      vnep_eXmm27 = vnep_eXmm26
      vnep_eXmm29 = vnep_eXmm28
      vnep_eXmm31 = vnep_eXmm30
      vnep_eXmm33 = vnep_eXmm32
      vnep_eXmm35 = vnep_eXmm34
      vnep_eXmm37 = vnep_eXmm36
      vnep_eXmm39 = vnep_eXmm38
      vnep_eXmm41 = vnep_eXmm40
      vnep_eXmm43 = vnep_eXmm42
      vnep_eXmm45 = vnep_eXmm44
      vnep_eXmm47 = vnep_eXmm46
      vnep_eXmm49 = vnep_eXmm48
      vnep_eXmm51 = vnep_eXmm50
      vnep_eXmm53 = vnep_eXmm52
      vnep_eXmm55 = vnep_eXmm54
      vnep_eXmm57 = vnep_eXmm56
      vnep_eXmm59 = vnep_eXmm58
      vnep_eXmm61 = vnep_eXmm60
      vnep_eXmm63 = vnep_eXmm62
      return
      end
