*     File ep_eXmm/aep_eXmmmptbl.f : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aep_eXmmmptbl
      implicit real*8(a-h,o-z)
      include 'inclep_eXmm1.h'
      include 'incl2.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      integer     mu
      complex*16  agcr(0:lep_eXmmag-1,4)
       common /RESO/agcr

      jgraph = 0

* External lines
      call smextf(lincom,amp,pfep_eXmm2,ptep_eXmm2v,cfep_eXmm2v)
      exep_eXmm2v(1) = lprtcl
      call smextf(loutgo,amlp(1),pfep_eXmm4,ptep_eXmm4m,cfep_eXmm4m)
      exep_eXmm4m(1) = lantip
      call smextf(loutgo,amass1(3),pfep_eXmm9,ptep_eXmm9x,cfep_eXmm9x)
      exep_eXmm9x(1) = lprtcl
      call smextf(lincom,amlp(1),pfep_eXmm17,ptep_eXmm17m,cfep_eXmm17m)
      exep_eXmm17m(1) = lantip
      call smextf(loutgo,amlp(2),pfep_eXmm33,ptep_eXmm33n,cfep_eXmm33n)
      exep_eXmm33n(1) = lprtcl
      call smextf(lincom,amlp(2),pfep_eXmm62,ptep_eXmm62n,cfep_eXmm62n)
      exep_eXmm62n(1) = lantip


* Buffer clear for amplitude
      do 200 ih = 0 , lep_eXmmag-1
         agc(ih) = (0.0d0,0.0d0)
         do mu=1,4
           agcr(ih,mu) = (0.0d0,0.0d0)
         enddo
  200 continue


      call aep_eXmmmpt0

      return
      end
************************************************************************
      subroutine aep_eXmmmpt0
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'incl2.h'
      include 'inclk.h'
*-----------------------------------------------------------------------
      if(jselg(1) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 1
        call aep_eXmmg1
      endif

      if(jselg(2) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 2
        call aep_eXmmg2
      endif

      if(jselg(3) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 3
        call aep_eXmmg3
      endif

      if(jselg(4) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 4
        call aep_eXmmg4
      endif

      if(jselg(5) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 5
        call aep_eXmmg5
      endif

      if(jselg(6) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 6
        call aep_eXmmg6
      endif

      if(jselg(7) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 7
        call aep_eXmmg7
      endif

      if(jselg(8) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 8
        call aep_eXmmg8
      endif

      return
      end
