*     File et_etmm/inclet_etmmp.h : Sat Mar 18 19:45:06 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfet_etmm2(4),pfet_etmm3(4),pfet_etmm4(4),
     &               pfet_etmm5(4),pfet_etmm6(4),pfet_etmm7(4),
     &               pfet_etmm8(4),pfet_etmm9(4),pfet_etmm10(4),
     &               pfet_etmm11(4),pfet_etmm12(4),pfet_etmm13(4),
     &               pfet_etmm14(4),pfet_etmm15(4),pfet_etmm16(4),
     &               pfet_etmm17(4),pfet_etmm18(4),pfet_etmm19(4),
     &               pfet_etmm20(4),pfet_etmm21(4),pfet_etmm22(4),
     &               pfet_etmm23(4),pfet_etmm24(4),pfet_etmm25(4),
     &               pfet_etmm26(4),pfet_etmm27(4),pfet_etmm28(4),
     &               pfet_etmm29(4),pfet_etmm30(4),pfet_etmm31(4),
     &               pfet_etmm32(4),pfet_etmm33(4),pfet_etmm34(4),
     &               pfet_etmm35(4),pfet_etmm36(4),pfet_etmm37(4),
     &               pfet_etmm38(4),pfet_etmm39(4),pfet_etmm40(4),
     &               pfet_etmm41(4),pfet_etmm42(4),pfet_etmm43(4),
     &               pfet_etmm44(4),pfet_etmm45(4),pfet_etmm46(4),
     &               pfet_etmm47(4),pfet_etmm48(4),pfet_etmm49(4)
      common /amilcd_4f/pfet_etmm50(4),pfet_etmm51(4),
     &               pfet_etmm52(4),pfet_etmm53(4),pfet_etmm54(4),
     &               pfet_etmm55(4),pfet_etmm56(4),pfet_etmm57(4),
     &               pfet_etmm58(4),pfet_etmm59(4),pfet_etmm60(4),
     &               pfet_etmm61(4),pfet_etmm62(4),pfet_etmm63(4)
      common /amilcp_4f/vnet_etmm2,vnet_etmm3,vnet_etmm4,vnet_etmm5,
     &               vnet_etmm6,vnet_etmm7,vnet_etmm8,vnet_etmm9,
     &               vnet_etmm10,vnet_etmm11,vnet_etmm12,vnet_etmm13,
     &               vnet_etmm14,vnet_etmm15,vnet_etmm16,vnet_etmm17,
     &               vnet_etmm18,vnet_etmm19,vnet_etmm20,vnet_etmm21,
     &               vnet_etmm22,vnet_etmm23,vnet_etmm24,vnet_etmm25,
     &               vnet_etmm26,vnet_etmm27,vnet_etmm28,vnet_etmm29,
     &               vnet_etmm30,vnet_etmm31,vnet_etmm32,vnet_etmm33,
     &               vnet_etmm34,vnet_etmm35,vnet_etmm36,vnet_etmm37,
     &               vnet_etmm38,vnet_etmm39,vnet_etmm40,vnet_etmm41,
     &               vnet_etmm42,vnet_etmm43,vnet_etmm44,vnet_etmm45,
     &               vnet_etmm46,vnet_etmm47,vnet_etmm48,vnet_etmm49,
     &               vnet_etmm50,vnet_etmm51,vnet_etmm52,vnet_etmm53,
     &               vnet_etmm54,vnet_etmm55,vnet_etmm56,vnet_etmm57,
     &               vnet_etmm58,vnet_etmm59,vnet_etmm60,vnet_etmm61,
     &               vnet_etmm62,vnet_etmm63
