*     File es_estt/incles_esttp.h : Sat Mar 18 19:45:02 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfes_estt2(4),pfes_estt3(4),pfes_estt4(4),
     &               pfes_estt5(4),pfes_estt6(4),pfes_estt7(4),
     &               pfes_estt8(4),pfes_estt9(4),pfes_estt10(4),
     &               pfes_estt11(4),pfes_estt12(4),pfes_estt13(4),
     &               pfes_estt14(4),pfes_estt15(4),pfes_estt16(4),
     &               pfes_estt17(4),pfes_estt18(4),pfes_estt19(4),
     &               pfes_estt20(4),pfes_estt21(4),pfes_estt22(4),
     &               pfes_estt23(4),pfes_estt24(4),pfes_estt25(4),
     &               pfes_estt26(4),pfes_estt27(4),pfes_estt28(4),
     &               pfes_estt29(4),pfes_estt30(4),pfes_estt31(4),
     &               pfes_estt32(4),pfes_estt33(4),pfes_estt34(4),
     &               pfes_estt35(4),pfes_estt36(4),pfes_estt37(4),
     &               pfes_estt38(4),pfes_estt39(4),pfes_estt40(4),
     &               pfes_estt41(4),pfes_estt42(4),pfes_estt43(4),
     &               pfes_estt44(4),pfes_estt45(4),pfes_estt46(4),
     &               pfes_estt47(4),pfes_estt48(4),pfes_estt49(4)
      common /amilcd_4f/pfes_estt50(4),pfes_estt51(4),
     &               pfes_estt52(4),pfes_estt53(4),pfes_estt54(4),
     &               pfes_estt55(4),pfes_estt56(4),pfes_estt57(4),
     &               pfes_estt58(4),pfes_estt59(4),pfes_estt60(4),
     &               pfes_estt61(4),pfes_estt62(4),pfes_estt63(4)
      common /amilcp_4f/vnes_estt2,vnes_estt3,vnes_estt4,vnes_estt5,
     &               vnes_estt6,vnes_estt7,vnes_estt8,vnes_estt9,
     &               vnes_estt10,vnes_estt11,vnes_estt12,vnes_estt13,
     &               vnes_estt14,vnes_estt15,vnes_estt16,vnes_estt17,
     &               vnes_estt18,vnes_estt19,vnes_estt20,vnes_estt21,
     &               vnes_estt22,vnes_estt23,vnes_estt24,vnes_estt25,
     &               vnes_estt26,vnes_estt27,vnes_estt28,vnes_estt29,
     &               vnes_estt30,vnes_estt31,vnes_estt32,vnes_estt33,
     &               vnes_estt34,vnes_estt35,vnes_estt36,vnes_estt37,
     &               vnes_estt38,vnes_estt39,vnes_estt40,vnes_estt41,
     &               vnes_estt42,vnes_estt43,vnes_estt44,vnes_estt45,
     &               vnes_estt46,vnes_estt47,vnes_estt48,vnes_estt49,
     &               vnes_estt50,vnes_estt51,vnes_estt52,vnes_estt53,
     &               vnes_estt54,vnes_estt55,vnes_estt56,vnes_estt57,
     &               vnes_estt58,vnes_estt59,vnes_estt60,vnes_estt61,
     &               vnes_estt62,vnes_estt63
