*     File ecb_ecbmm/inclecb_ecbmm1.h : Sat Mar 18 19:45:04 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (necb_ecbmmgraph =35)
      parameter (necb_ecbmmextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (lecb_ecbmmag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (necb_ecbmmgrpsq = necb_ecbmmgraph*necb_ecbmmgraph)
      common /aecb_ecbmmmslct/jselg(necb_ecbmmgraph),jgraph,jgluon,
     &               jhiggs

* Color string information
      common /aecb_ecbmmmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aecb_ecbmmmgrph/agcwrk(0:lecb_ecbmmag-1),agc(0:lecb_ecbmmag-1),
     &              aprop,ancp(necb_ecbmmgraph),ansp(0:necb_ecbmmgraph)
     &             ,cfmtx
      common /aecb_ecbmmmgrpi/igraph(necb_ecbmmgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aecb_ecbmmmextr/peecb_ecbmm1(4),peecb_ecbmm2(4),
     &               peecb_ecbmm3(4),peecb_ecbmm4(4),peecb_ecbmm5(4),
     &               peecb_ecbmm6(4),
     &               prod(necb_ecbmmextn, necb_ecbmmextn)

      common /aecb_ecbmmmextp/ptecb_ecbmm2q,execb_ecbmm2q,cfecb_ecbmm2q,
     &               ptecb_ecbmm4m,execb_ecbmm4m,cfecb_ecbmm4m,
     &               ptecb_ecbmm9q,execb_ecbmm9q,cfecb_ecbmm9q,
     &               ptecb_ecbmm17m,execb_ecbmm17m,cfecb_ecbmm17m,
     &               ptecb_ecbmm33n,execb_ecbmm33n,cfecb_ecbmm33n,
     &               ptecb_ecbmm62n,execb_ecbmm62n,cfecb_ecbmm62n

      real*8     ptecb_ecbmm2q(4,2), execb_ecbmm2q(1)
      complex*16 cfecb_ecbmm2q(2,2)
      real*8     ptecb_ecbmm4m(4,2), execb_ecbmm4m(1)
      complex*16 cfecb_ecbmm4m(2,2)
      real*8     ptecb_ecbmm9q(4,2), execb_ecbmm9q(1)
      complex*16 cfecb_ecbmm9q(2,2)
      real*8     ptecb_ecbmm17m(4,2), execb_ecbmm17m(1)
      complex*16 cfecb_ecbmm17m(2,2)
      real*8     ptecb_ecbmm33n(4,2), execb_ecbmm33n(1)
      complex*16 cfecb_ecbmm33n(2,2)
      real*8     ptecb_ecbmm62n(4,2), execb_ecbmm62n(1)
      complex*16 cfecb_ecbmm62n(2,2)

* Normalization
      common /aecb_ecbmmmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aecb_ecbmmmatbl/av, lt, indexg
      complex*16 av(0:lecb_ecbmmag-1)
      integer    lt(0:necb_ecbmmextn), indexg(necb_ecbmmextn)

* Spin average
      common/aecb_ecbmmmspin/aspin,aident,jhs(necb_ecbmmextn),
     &               jhe(necb_ecbmmextn),jcpol(necb_ecbmmextn),
     &               kperm(necb_ecbmmextn)
