*     File ep_eXmm/aep_eXmmmps.f : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
*             Graph No. 1 - 1
*         Generated No. 1
************************************************************************
      subroutine aep_eXmmg1
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm15m,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm15m,
     &               ptep_eXmm15m,evep_eXmm31d,eqep_eXmm31d
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm15m(2),ptep_eXmm15m(4,3),
     &           evep_eXmm31d(lepina),eqep_eXmm31d(4,lepina)
      complex*16 cfep_eXmm15m(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lintrn*lextrn*lepina)
      complex*16 av8(lextrn*lintrn*lepina)
      complex*16 av9(lextrn*lextrn*lepina)
      complex*16 av10(lextrn*lextrn*lintrn*lextrn)
      complex*16 av11(lextrn*lepina*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm15,
     &      amlp(1)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm31,
     &      ama**2,0.0d0)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(1),pfep_eXmm15,vnep_eXmm15,exep_eXmm15m,
     &            ptep_eXmm15m,cfep_eXmm15m)
      call smintv(lepina,ama,pfep_eXmm31,eqep_eXmm31d,evep_eXmm31d,
     &            vnep_eXmm31,igauab)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm4 electron
*     7(1): pfep_eXmm15 electron
*     7(2): pfep_eXmm11 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm15m,exep_eXmm4m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm15m,cfep_eXmm4m,
     &           ptep_eXmm15m,ptep_eXmm4m,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm15 electron
*     8(1): pfep_eXmm17 electron
*     8(2): pfep_eXmm31 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm17m,exep_eXmm15m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm17m,cfep_eXmm15m,
     &           ptep_eXmm17m,ptep_eXmm15m,eqep_eXmm31d,lt8,av8)

*     9(0): pfep_eXmm33 muon
*     9(1): pfep_eXmm62 muon
*     9(2): pfep_eXmm31 photon
      call smffv(lextrn,lextrn,lepina,exep_eXmm62n,exep_eXmm33n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm62n,cfep_eXmm33n,
     &           ptep_eXmm62n,ptep_eXmm33n,eqep_eXmm31d,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,exep_eXmm15m,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm31d,av9,av11,lt,av)

      indexg(1) = 6
      indexg(2) = 5
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 2

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 2 - 1
*         Generated No. 2
************************************************************************
      subroutine aep_eXmmg2
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm15m,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm15m,
     &               ptep_eXmm15m,evep_eXmm31c,eqep_eXmm31c
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm15m(2),ptep_eXmm15m(4,3),
     &           evep_eXmm31c(lepinv),eqep_eXmm31c(4,lepinv)
      complex*16 cfep_eXmm15m(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lintrn*lextrn*lepina)
      complex*16 av8(lextrn*lintrn*lepinv)
      complex*16 av9(lextrn*lextrn*lepinv)
      complex*16 av10(lextrn*lextrn*lintrn*lextrn)
      complex*16 av11(lextrn*lepinv*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm15,
     &      amlp(1)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm31,
     &      amz**2,amz*agz)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(1),pfep_eXmm15,vnep_eXmm15,exep_eXmm15m,
     &            ptep_eXmm15m,cfep_eXmm15m)
      call smintv(lepinv,amz,pfep_eXmm31,eqep_eXmm31c,evep_eXmm31c,
     &            vnep_eXmm31,igauzb)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm4 electron
*     7(1): pfep_eXmm15 electron
*     7(2): pfep_eXmm11 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm15m,exep_eXmm4m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm15m,cfep_eXmm4m,
     &           ptep_eXmm15m,ptep_eXmm4m,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm15 electron
*     8(1): pfep_eXmm17 electron
*     8(2): pfep_eXmm31 z
      call smffv(lextrn,lintrn,lepinv,exep_eXmm17m,exep_eXmm15m,amlp(1),
     &           amlp(1),czll(1,1),cfep_eXmm17m,cfep_eXmm15m,
     &           ptep_eXmm17m,ptep_eXmm15m,eqep_eXmm31c,lt8,av8)

*     9(0): pfep_eXmm33 muon
*     9(1): pfep_eXmm62 muon
*     9(2): pfep_eXmm31 z
      call smffv(lextrn,lextrn,lepinv,exep_eXmm62n,exep_eXmm33n,amlp(2),
     &           amlp(2),czll(1,2),cfep_eXmm62n,cfep_eXmm33n,
     &           ptep_eXmm62n,ptep_eXmm33n,eqep_eXmm31c,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,exep_eXmm15m,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm31c,av9,av11,lt,av)

      indexg(1) = 6
      indexg(2) = 5
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 2

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 3 - 1
*         Generated No. 3
************************************************************************
      subroutine aep_eXmmg3
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm26m,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm26m,
     &               ptep_eXmm26m,evep_eXmm31d,eqep_eXmm31d
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm26m(2),ptep_eXmm26m(4,3),
     &           evep_eXmm31d(lepina),eqep_eXmm31d(4,lepina)
      complex*16 cfep_eXmm26m(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lextrn*lintrn*lepina)
      complex*16 av8(lintrn*lextrn*lepina)
      complex*16 av9(lextrn*lextrn*lepina)
      complex*16 av10(lextrn*lextrn*lextrn*lintrn)
      complex*16 av11(lextrn*lepina*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm26,
     &      amlp(1)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm31,
     &      ama**2,0.0d0)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(1),pfep_eXmm26,vnep_eXmm26,exep_eXmm26m,
     &            ptep_eXmm26m,cfep_eXmm26m)
      call smintv(lepina,ama,pfep_eXmm31,eqep_eXmm31d,evep_eXmm31d,
     &            vnep_eXmm31,igauab)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm26 electron
*     7(1): pfep_eXmm17 electron
*     7(2): pfep_eXmm11 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm17m,exep_eXmm26m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm17m,cfep_eXmm26m,
     &           ptep_eXmm17m,ptep_eXmm26m,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm4 electron
*     8(1): pfep_eXmm26 electron
*     8(2): pfep_eXmm31 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm26m,exep_eXmm4m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm26m,cfep_eXmm4m,
     &           ptep_eXmm26m,ptep_eXmm4m,eqep_eXmm31d,lt8,av8)

*     9(0): pfep_eXmm33 muon
*     9(1): pfep_eXmm62 muon
*     9(2): pfep_eXmm31 photon
      call smffv(lextrn,lextrn,lepina,exep_eXmm62n,exep_eXmm33n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm62n,cfep_eXmm33n,
     &           ptep_eXmm62n,ptep_eXmm33n,eqep_eXmm31d,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,exep_eXmm26m,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm31d,av9,av11,lt,av)

      indexg(1) = 6
      indexg(2) = 5
      indexg(3) = 2
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 4

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 4 - 1
*         Generated No. 4
************************************************************************
      subroutine aep_eXmmg4
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm26m,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm26m,
     &               ptep_eXmm26m,evep_eXmm31c,eqep_eXmm31c
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm26m(2),ptep_eXmm26m(4,3),
     &           evep_eXmm31c(lepinv),eqep_eXmm31c(4,lepinv)
      complex*16 cfep_eXmm26m(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lextrn*lintrn*lepina)
      complex*16 av8(lintrn*lextrn*lepinv)
      complex*16 av9(lextrn*lextrn*lepinv)
      complex*16 av10(lextrn*lextrn*lextrn*lintrn)
      complex*16 av11(lextrn*lepinv*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm26,
     &      amlp(1)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm31,
     &      amz**2,amz*agz)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(1),pfep_eXmm26,vnep_eXmm26,exep_eXmm26m,
     &            ptep_eXmm26m,cfep_eXmm26m)
      call smintv(lepinv,amz,pfep_eXmm31,eqep_eXmm31c,evep_eXmm31c,
     &            vnep_eXmm31,igauzb)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm26 electron
*     7(1): pfep_eXmm17 electron
*     7(2): pfep_eXmm11 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm17m,exep_eXmm26m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm17m,cfep_eXmm26m,
     &           ptep_eXmm17m,ptep_eXmm26m,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm4 electron
*     8(1): pfep_eXmm26 electron
*     8(2): pfep_eXmm31 z
      call smffv(lintrn,lextrn,lepinv,exep_eXmm26m,exep_eXmm4m,amlp(1),
     &           amlp(1),czll(1,1),cfep_eXmm26m,cfep_eXmm4m,
     &           ptep_eXmm26m,ptep_eXmm4m,eqep_eXmm31c,lt8,av8)

*     9(0): pfep_eXmm33 muon
*     9(1): pfep_eXmm62 muon
*     9(2): pfep_eXmm31 z
      call smffv(lextrn,lextrn,lepinv,exep_eXmm62n,exep_eXmm33n,amlp(2),
     &           amlp(2),czll(1,2),cfep_eXmm62n,cfep_eXmm33n,
     &           ptep_eXmm62n,ptep_eXmm33n,eqep_eXmm31c,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,exep_eXmm26m,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm31c,av9,av11,lt,av)

      indexg(1) = 6
      indexg(2) = 5
      indexg(3) = 2
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 4

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 5 - 1
*         Generated No. 5
************************************************************************
      subroutine aep_eXmmg5
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm43n,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm43n,
     &               ptep_eXmm43n,evep_eXmm20d,eqep_eXmm20d
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm43n(2),ptep_eXmm43n(4,3),
     &           evep_eXmm20d(lepina),eqep_eXmm20d(4,lepina)
      complex*16 cfep_eXmm43n(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lintrn*lextrn*lepina)
      complex*16 av8(lextrn*lintrn*lepina)
      complex*16 av9(lextrn*lextrn*lepina)
      complex*16 av10(lextrn*lextrn*lintrn*lextrn)
      complex*16 av11(lextrn*lepina*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm43,
     &      amlp(2)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm20,
     &      ama**2,0.0d0)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(2),pfep_eXmm43,vnep_eXmm43,exep_eXmm43n,
     &            ptep_eXmm43n,cfep_eXmm43n)
      call smintv(lepina,ama,pfep_eXmm20,eqep_eXmm20d,evep_eXmm20d,
     &            vnep_eXmm20,igauab)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm33 muon
*     7(1): pfep_eXmm43 muon
*     7(2): pfep_eXmm11 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm43n,exep_eXmm33n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm43n,cfep_eXmm33n,
     &           ptep_eXmm43n,ptep_eXmm33n,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm43 muon
*     8(1): pfep_eXmm62 muon
*     8(2): pfep_eXmm20 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm62n,exep_eXmm43n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm62n,cfep_eXmm43n,
     &           ptep_eXmm62n,ptep_eXmm43n,eqep_eXmm20d,lt8,av8)

*     9(0): pfep_eXmm4 electron
*     9(1): pfep_eXmm17 electron
*     9(2): pfep_eXmm20 photon
      call smffv(lextrn,lextrn,lepina,exep_eXmm17m,exep_eXmm4m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm17m,cfep_eXmm4m,
     &           ptep_eXmm17m,ptep_eXmm4m,eqep_eXmm20d,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,exep_eXmm43n,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm20d,av9,av11,lt,av)

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 5

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 6 - 1
*         Generated No. 6
************************************************************************
      subroutine aep_eXmmg6
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm43n,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm43n,
     &               ptep_eXmm43n,evep_eXmm20c,eqep_eXmm20c
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm43n(2),ptep_eXmm43n(4,3),
     &           evep_eXmm20c(lepinv),eqep_eXmm20c(4,lepinv)
      complex*16 cfep_eXmm43n(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lintrn*lextrn*lepina)
      complex*16 av8(lextrn*lintrn*lepinv)
      complex*16 av9(lextrn*lextrn*lepinv)
      complex*16 av10(lextrn*lextrn*lintrn*lextrn)
      complex*16 av11(lextrn*lepinv*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm43,
     &      amlp(2)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm20,
     &      amz**2,amz*agz)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(2),pfep_eXmm43,vnep_eXmm43,exep_eXmm43n,
     &            ptep_eXmm43n,cfep_eXmm43n)
      call smintv(lepinv,amz,pfep_eXmm20,eqep_eXmm20c,evep_eXmm20c,
     &            vnep_eXmm20,igauzb)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm33 muon
*     7(1): pfep_eXmm43 muon
*     7(2): pfep_eXmm11 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm43n,exep_eXmm33n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm43n,cfep_eXmm33n,
     &           ptep_eXmm43n,ptep_eXmm33n,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm43 muon
*     8(1): pfep_eXmm62 muon
*     8(2): pfep_eXmm20 z
      call smffv(lextrn,lintrn,lepinv,exep_eXmm62n,exep_eXmm43n,amlp(2),
     &           amlp(2),czll(1,2),cfep_eXmm62n,cfep_eXmm43n,
     &           ptep_eXmm62n,ptep_eXmm43n,eqep_eXmm20c,lt8,av8)

*     9(0): pfep_eXmm4 electron
*     9(1): pfep_eXmm17 electron
*     9(2): pfep_eXmm20 z
      call smffv(lextrn,lextrn,lepinv,exep_eXmm17m,exep_eXmm4m,amlp(1),
     &           amlp(1),czll(1,1),cfep_eXmm17m,cfep_eXmm4m,
     &           ptep_eXmm17m,ptep_eXmm4m,eqep_eXmm20c,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,exep_eXmm43n,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm20c,av9,av11,lt,av)

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 5

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 7 - 1
*         Generated No. 7
************************************************************************
      subroutine aep_eXmmg7
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm53n,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm53n,
     &               ptep_eXmm53n,evep_eXmm20d,eqep_eXmm20d
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm53n(2),ptep_eXmm53n(4,3),
     &           evep_eXmm20d(lepina),eqep_eXmm20d(4,lepina)
      complex*16 cfep_eXmm53n(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lextrn*lintrn*lepina)
      complex*16 av8(lintrn*lextrn*lepina)
      complex*16 av9(lextrn*lextrn*lepina)
      complex*16 av10(lextrn*lextrn*lextrn*lintrn)
      complex*16 av11(lextrn*lepina*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm53,
     &      amlp(2)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm20,
     &      ama**2,0.0d0)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(2),pfep_eXmm53,vnep_eXmm53,exep_eXmm53n,
     &            ptep_eXmm53n,cfep_eXmm53n)
      call smintv(lepina,ama,pfep_eXmm20,eqep_eXmm20d,evep_eXmm20d,
     &            vnep_eXmm20,igauab)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm53 muon
*     7(1): pfep_eXmm62 muon
*     7(2): pfep_eXmm11 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm62n,exep_eXmm53n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm62n,cfep_eXmm53n,
     &           ptep_eXmm62n,ptep_eXmm53n,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm33 muon
*     8(1): pfep_eXmm53 muon
*     8(2): pfep_eXmm20 photon
      call smffv(lintrn,lextrn,lepina,exep_eXmm53n,exep_eXmm33n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm53n,cfep_eXmm33n,
     &           ptep_eXmm53n,ptep_eXmm33n,eqep_eXmm20d,lt8,av8)

*     9(0): pfep_eXmm4 electron
*     9(1): pfep_eXmm17 electron
*     9(2): pfep_eXmm20 photon
      call smffv(lextrn,lextrn,lepina,exep_eXmm17m,exep_eXmm4m,amlp(1),
     &           amlp(1),call(1,1),cfep_eXmm17m,cfep_eXmm4m,
     &           ptep_eXmm17m,ptep_eXmm4m,eqep_eXmm20d,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,exep_eXmm53n,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm20d,av9,av11,lt,av)

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 5
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 6

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
************************************************************************
*             Graph No. 8 - 1
*         Generated No. 8
************************************************************************
      subroutine aep_eXmmg8
      implicit real*8(a-h,o-z)

      include 'inclep_eXmm1.h'
      include 'inclk.h'
      include 'inclep_eXmmp.h'
*-----------------------------------------------------------------------
      common /amwork/cfep_eXmm53n,av6,av7,av8,av9,av10,av11,
     &               evep_eXmm11d,eqep_eXmm11d,exep_eXmm53n,
     &               ptep_eXmm53n,evep_eXmm20c,eqep_eXmm20c
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3632 (3632) + 108 (108) bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      real*8     evep_eXmm11d(lepina),eqep_eXmm11d(4,lepina),
     &           exep_eXmm53n(2),ptep_eXmm53n(4,3),
     &           evep_eXmm20c(lepinv),eqep_eXmm20c(4,lepinv)
      complex*16 cfep_eXmm53n(2,4)
      complex*16 av6(lextrn*lextrn*lepina)
      complex*16 av7(lextrn*lintrn*lepina)
      complex*16 av8(lintrn*lextrn*lepinv)
      complex*16 av9(lextrn*lextrn*lepinv)
      complex*16 av10(lextrn*lextrn*lextrn*lintrn)
      complex*16 av11(lextrn*lepinv*lextrn*lextrn*lextrn)
      complex*16 atmp

      complex*16  av6r(lextrn*lextrn*lepina,4)
      integer     mu,ih
      complex*16     agcr(0:lep_eXmmag-1,4)
       common /RESO/ agcr

*-----------------------------------------------------------------------

* Denominators of propagators
      aprop = 1.0d0
      call snprpd(pphase,aprop,vnep_eXmm11,
     &      ama**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm53,
     &      amlp(2)**2,0.0d0)
      call snprpd(pphase,aprop,vnep_eXmm20,
     &      amz**2,amz*agz)

* Internal momenta
      call smintv(lepina,ama,pfep_eXmm11,eqep_eXmm11d,evep_eXmm11d,
     &            vnep_eXmm11,igauab)
      call smintf(amlp(2),pfep_eXmm53,vnep_eXmm53,exep_eXmm53n,
     &            ptep_eXmm53n,cfep_eXmm53n)
      call smintv(lepinv,amz,pfep_eXmm20,eqep_eXmm20c,evep_eXmm20c,
     &            vnep_eXmm20,igauzb)

* Vertices (10)

*     6(0): pfep_eXmm9 xxx
*     6(1): pfep_eXmm2 p
*     6(2): pfep_eXmm11 photon
      call stpxv(2212,lextrn,amp,pfep_eXmm2,+1,vnep_eXmm2,exep_eXmm2v,
     &            cfep_eXmm2v,ptep_eXmm2v,2212,lextrn,amp,pfep_eXmm9,-1,
     &            vnep_eXmm9,exep_eXmm9x,cfep_eXmm9x,ptep_eXmm9x,22,
     &            lepina,ama,pfep_eXmm11,+1,vnep_eXmm11,exep_eXmm11d,
     &            eqep_eXmm11d,capx,lt6,av6r)

*     7(0): pfep_eXmm53 muon
*     7(1): pfep_eXmm62 muon
*     7(2): pfep_eXmm11 photon
      call smffv(lextrn,lintrn,lepina,exep_eXmm62n,exep_eXmm53n,amlp(2),
     &           amlp(2),call(1,2),cfep_eXmm62n,cfep_eXmm53n,
     &           ptep_eXmm62n,ptep_eXmm53n,eqep_eXmm11d,lt7,av7)

*     8(0): pfep_eXmm33 muon
*     8(1): pfep_eXmm53 muon
*     8(2): pfep_eXmm20 z
      call smffv(lintrn,lextrn,lepinv,exep_eXmm53n,exep_eXmm33n,amlp(2),
     &           amlp(2),czll(1,2),cfep_eXmm53n,cfep_eXmm33n,
     &           ptep_eXmm53n,ptep_eXmm33n,eqep_eXmm20c,lt8,av8)

*     9(0): pfep_eXmm4 electron
*     9(1): pfep_eXmm17 electron
*     9(2): pfep_eXmm20 z
      call smffv(lextrn,lextrn,lepinv,exep_eXmm17m,exep_eXmm4m,amlp(1),
     &           amlp(1),czll(1,1),cfep_eXmm17m,cfep_eXmm4m,
     &           ptep_eXmm17m,ptep_eXmm4m,eqep_eXmm20c,lt9,av9)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      do 4000 mu=1,4   !!!!!!!!!!!!!!!!!!!!!!!!! 

      do ih = 1, lextrn*lextrn*lepina
        av6(ih) = av6r(ih,mu)
      enddo

      call smconv(lt6,lt7,3,3,evep_eXmm11d,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,exep_eXmm53n,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,evep_eXmm20c,av9,av11,lt,av)

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 5
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 6

      call aep_eXmmmpord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lep_eXmmag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih) = agc(ih) + atmp
         agcr(ih,mu) = agcr(ih,mu) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

 4000 continue         !!!!!!!!!!!!!!!!!!!!!!!!! 

      return
      end
