*     File ep_eXmm/inclep_eXmmp.h : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfep_eXmm2(4),pfep_eXmm3(4),pfep_eXmm4(4),
     &               pfep_eXmm5(4),pfep_eXmm6(4),pfep_eXmm7(4),
     &               pfep_eXmm8(4),pfep_eXmm9(4),pfep_eXmm10(4),
     &               pfep_eXmm11(4),pfep_eXmm12(4),pfep_eXmm13(4),
     &               pfep_eXmm14(4),pfep_eXmm15(4),pfep_eXmm16(4),
     &               pfep_eXmm17(4),pfep_eXmm18(4),pfep_eXmm19(4),
     &               pfep_eXmm20(4),pfep_eXmm21(4),pfep_eXmm22(4),
     &               pfep_eXmm23(4),pfep_eXmm24(4),pfep_eXmm25(4),
     &               pfep_eXmm26(4),pfep_eXmm27(4),pfep_eXmm28(4),
     &               pfep_eXmm29(4),pfep_eXmm30(4),pfep_eXmm31(4),
     &               pfep_eXmm32(4),pfep_eXmm33(4),pfep_eXmm34(4),
     &               pfep_eXmm35(4),pfep_eXmm36(4),pfep_eXmm37(4),
     &               pfep_eXmm38(4),pfep_eXmm39(4),pfep_eXmm40(4),
     &               pfep_eXmm41(4),pfep_eXmm42(4),pfep_eXmm43(4),
     &               pfep_eXmm44(4),pfep_eXmm45(4),pfep_eXmm46(4),
     &               pfep_eXmm47(4),pfep_eXmm48(4),pfep_eXmm49(4)
      common /amilcd_4f/pfep_eXmm50(4),pfep_eXmm51(4),
     &               pfep_eXmm52(4),pfep_eXmm53(4),pfep_eXmm54(4),
     &               pfep_eXmm55(4),pfep_eXmm56(4),pfep_eXmm57(4),
     &               pfep_eXmm58(4),pfep_eXmm59(4),pfep_eXmm60(4),
     &               pfep_eXmm61(4),pfep_eXmm62(4),pfep_eXmm63(4)
      common /amilcp_4f/vnep_eXmm2,vnep_eXmm3,vnep_eXmm4,vnep_eXmm5,
     &               vnep_eXmm6,vnep_eXmm7,vnep_eXmm8,vnep_eXmm9,
     &               vnep_eXmm10,vnep_eXmm11,vnep_eXmm12,vnep_eXmm13,
     &               vnep_eXmm14,vnep_eXmm15,vnep_eXmm16,vnep_eXmm17,
     &               vnep_eXmm18,vnep_eXmm19,vnep_eXmm20,vnep_eXmm21,
     &               vnep_eXmm22,vnep_eXmm23,vnep_eXmm24,vnep_eXmm25,
     &               vnep_eXmm26,vnep_eXmm27,vnep_eXmm28,vnep_eXmm29,
     &               vnep_eXmm30,vnep_eXmm31,vnep_eXmm32,vnep_eXmm33,
     &               vnep_eXmm34,vnep_eXmm35,vnep_eXmm36,vnep_eXmm37,
     &               vnep_eXmm38,vnep_eXmm39,vnep_eXmm40,vnep_eXmm41,
     &               vnep_eXmm42,vnep_eXmm43,vnep_eXmm44,vnep_eXmm45,
     &               vnep_eXmm46,vnep_eXmm47,vnep_eXmm48,vnep_eXmm49,
     &               vnep_eXmm50,vnep_eXmm51,vnep_eXmm52,vnep_eXmm53,
     &               vnep_eXmm54,vnep_eXmm55,vnep_eXmm56,vnep_eXmm57,
     &               vnep_eXmm58,vnep_eXmm59,vnep_eXmm60,vnep_eXmm61,
     &               vnep_eXmm62,vnep_eXmm63
