*     File eb_ebmm/aeb_ebmmkptbl.f : Sat Mar 18 19:45:05 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aeb_ebmmkptbl
      implicit real*8(a-h,o-z)

      include 'incleb_ebmm1.h'
      include 'inclk.h'
      include 'incleb_ebmmp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfeb_ebmm2(i) =  + peeb_ebmm1(i)
        pfeb_ebmm4(i) =  + peeb_ebmm2(i)
        pfeb_ebmm6(i) =  + peeb_ebmm1(i) + peeb_ebmm2(i)
        pfeb_ebmm8(i) =  - peeb_ebmm3(i)
        pfeb_ebmm10(i) =  + peeb_ebmm1(i) - peeb_ebmm3(i)
        pfeb_ebmm12(i) =  + peeb_ebmm2(i) - peeb_ebmm3(i)
        pfeb_ebmm14(i) =  + peeb_ebmm1(i) + peeb_ebmm2(i) - peeb_ebmm3(i)
        pfeb_ebmm16(i) =  - peeb_ebmm4(i)
        pfeb_ebmm18(i) =  + peeb_ebmm1(i) - peeb_ebmm4(i)
        pfeb_ebmm20(i) =  + peeb_ebmm2(i) - peeb_ebmm4(i)
        pfeb_ebmm22(i) =  + peeb_ebmm1(i) + peeb_ebmm2(i) - peeb_ebmm4(i)
        pfeb_ebmm24(i) =  - peeb_ebmm3(i) - peeb_ebmm4(i)
        pfeb_ebmm26(i) =  + peeb_ebmm1(i) - peeb_ebmm3(i) - peeb_ebmm4(i)
        pfeb_ebmm28(i) =  + peeb_ebmm2(i) - peeb_ebmm3(i) - peeb_ebmm4(i)
        pfeb_ebmm30(i) =  + peeb_ebmm5(i) + peeb_ebmm6(i)
        pfeb_ebmm32(i) =  - peeb_ebmm5(i)
        pfeb_ebmm34(i) =  + peeb_ebmm1(i) - peeb_ebmm5(i)
        pfeb_ebmm36(i) =  + peeb_ebmm2(i) - peeb_ebmm5(i)
        pfeb_ebmm38(i) =  + peeb_ebmm1(i) + peeb_ebmm2(i) - peeb_ebmm5(i)
        pfeb_ebmm40(i) =  - peeb_ebmm3(i) - peeb_ebmm5(i)
        pfeb_ebmm42(i) =  + peeb_ebmm1(i) - peeb_ebmm3(i) - peeb_ebmm5(i)
        pfeb_ebmm44(i) =  + peeb_ebmm2(i) - peeb_ebmm3(i) - peeb_ebmm5(i)
        pfeb_ebmm46(i) =  + peeb_ebmm4(i) + peeb_ebmm6(i)
        pfeb_ebmm48(i) =  - peeb_ebmm4(i) - peeb_ebmm5(i)
        pfeb_ebmm50(i) =  + peeb_ebmm1(i) - peeb_ebmm4(i) - peeb_ebmm5(i)
        pfeb_ebmm52(i) =  + peeb_ebmm2(i) - peeb_ebmm4(i) - peeb_ebmm5(i)
        pfeb_ebmm54(i) =  + peeb_ebmm3(i) + peeb_ebmm6(i)
        pfeb_ebmm56(i) =  - peeb_ebmm3(i) - peeb_ebmm4(i) - peeb_ebmm5(i)
        pfeb_ebmm58(i) =  - peeb_ebmm2(i) + peeb_ebmm6(i)
        pfeb_ebmm60(i) =  - peeb_ebmm1(i) + peeb_ebmm6(i)
        pfeb_ebmm62(i) =  + peeb_ebmm6(i)

        pfeb_ebmm3(i) = - pfeb_ebmm2(i)
        pfeb_ebmm5(i) = - pfeb_ebmm4(i)
        pfeb_ebmm7(i) = - pfeb_ebmm6(i)
        pfeb_ebmm9(i) = - pfeb_ebmm8(i)
        pfeb_ebmm11(i) = - pfeb_ebmm10(i)
        pfeb_ebmm13(i) = - pfeb_ebmm12(i)
        pfeb_ebmm15(i) = - pfeb_ebmm14(i)
        pfeb_ebmm17(i) = - pfeb_ebmm16(i)
        pfeb_ebmm19(i) = - pfeb_ebmm18(i)
        pfeb_ebmm21(i) = - pfeb_ebmm20(i)
        pfeb_ebmm23(i) = - pfeb_ebmm22(i)
        pfeb_ebmm25(i) = - pfeb_ebmm24(i)
        pfeb_ebmm27(i) = - pfeb_ebmm26(i)
        pfeb_ebmm29(i) = - pfeb_ebmm28(i)
        pfeb_ebmm31(i) = - pfeb_ebmm30(i)
        pfeb_ebmm33(i) = - pfeb_ebmm32(i)
        pfeb_ebmm35(i) = - pfeb_ebmm34(i)
        pfeb_ebmm37(i) = - pfeb_ebmm36(i)
        pfeb_ebmm39(i) = - pfeb_ebmm38(i)
        pfeb_ebmm41(i) = - pfeb_ebmm40(i)
        pfeb_ebmm43(i) = - pfeb_ebmm42(i)
        pfeb_ebmm45(i) = - pfeb_ebmm44(i)
        pfeb_ebmm47(i) = - pfeb_ebmm46(i)
        pfeb_ebmm49(i) = - pfeb_ebmm48(i)
        pfeb_ebmm51(i) = - pfeb_ebmm50(i)
        pfeb_ebmm53(i) = - pfeb_ebmm52(i)
        pfeb_ebmm55(i) = - pfeb_ebmm54(i)
        pfeb_ebmm57(i) = - pfeb_ebmm56(i)
        pfeb_ebmm59(i) = - pfeb_ebmm58(i)
        pfeb_ebmm61(i) = - pfeb_ebmm60(i)
        pfeb_ebmm63(i) = - pfeb_ebmm62(i)
  100 continue

      vneb_ebmm2 =  + amass2(1)
      vneb_ebmm4 =  + amass2(2)
      vneb_ebmm6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vneb_ebmm8 =  + amass2(3)
      vneb_ebmm10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vneb_ebmm12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vneb_ebmm14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vneb_ebmm16 =  + amass2(4)
      vneb_ebmm18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vneb_ebmm20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vneb_ebmm22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vneb_ebmm24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vneb_ebmm26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vneb_ebmm28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vneb_ebmm30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vneb_ebmm32 =  + amass2(5)
      vneb_ebmm34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vneb_ebmm36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vneb_ebmm38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vneb_ebmm40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vneb_ebmm42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vneb_ebmm44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vneb_ebmm46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vneb_ebmm48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vneb_ebmm50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vneb_ebmm52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vneb_ebmm54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vneb_ebmm56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vneb_ebmm58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vneb_ebmm60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vneb_ebmm62 =  + amass2(6)
      vneb_ebmm3 = vneb_ebmm2
      vneb_ebmm5 = vneb_ebmm4
      vneb_ebmm7 = vneb_ebmm6
      vneb_ebmm9 = vneb_ebmm8
      vneb_ebmm11 = vneb_ebmm10
      vneb_ebmm13 = vneb_ebmm12
      vneb_ebmm15 = vneb_ebmm14
      vneb_ebmm17 = vneb_ebmm16
      vneb_ebmm19 = vneb_ebmm18
      vneb_ebmm21 = vneb_ebmm20
      vneb_ebmm23 = vneb_ebmm22
      vneb_ebmm25 = vneb_ebmm24
      vneb_ebmm27 = vneb_ebmm26
      vneb_ebmm29 = vneb_ebmm28
      vneb_ebmm31 = vneb_ebmm30
      vneb_ebmm33 = vneb_ebmm32
      vneb_ebmm35 = vneb_ebmm34
      vneb_ebmm37 = vneb_ebmm36
      vneb_ebmm39 = vneb_ebmm38
      vneb_ebmm41 = vneb_ebmm40
      vneb_ebmm43 = vneb_ebmm42
      vneb_ebmm45 = vneb_ebmm44
      vneb_ebmm47 = vneb_ebmm46
      vneb_ebmm49 = vneb_ebmm48
      vneb_ebmm51 = vneb_ebmm50
      vneb_ebmm53 = vneb_ebmm52
      vneb_ebmm55 = vneb_ebmm54
      vneb_ebmm57 = vneb_ebmm56
      vneb_ebmm59 = vneb_ebmm58
      vneb_ebmm61 = vneb_ebmm60
      vneb_ebmm63 = vneb_ebmm62
      return
      end
