*     File ebb_ebbmm/inclebb_ebbmmp.h : Sat Mar 18 19:45:06 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfebb_ebbmm2(4),pfebb_ebbmm3(4),
     &               pfebb_ebbmm4(4),pfebb_ebbmm5(4),pfebb_ebbmm6(4),
     &               pfebb_ebbmm7(4),pfebb_ebbmm8(4),pfebb_ebbmm9(4),
     &               pfebb_ebbmm10(4),pfebb_ebbmm11(4),pfebb_ebbmm12(4),
     &               pfebb_ebbmm13(4),pfebb_ebbmm14(4),pfebb_ebbmm15(4),
     &               pfebb_ebbmm16(4),pfebb_ebbmm17(4),pfebb_ebbmm18(4),
     &               pfebb_ebbmm19(4),pfebb_ebbmm20(4),pfebb_ebbmm21(4),
     &               pfebb_ebbmm22(4),pfebb_ebbmm23(4),pfebb_ebbmm24(4),
     &               pfebb_ebbmm25(4),pfebb_ebbmm26(4),pfebb_ebbmm27(4),
     &               pfebb_ebbmm28(4),pfebb_ebbmm29(4),pfebb_ebbmm30(4),
     &               pfebb_ebbmm31(4),pfebb_ebbmm32(4),pfebb_ebbmm33(4),
     &               pfebb_ebbmm34(4),pfebb_ebbmm35(4),pfebb_ebbmm36(4),
     &               pfebb_ebbmm37(4),pfebb_ebbmm38(4),pfebb_ebbmm39(4),
     &               pfebb_ebbmm40(4),pfebb_ebbmm41(4),pfebb_ebbmm42(4),
     &               pfebb_ebbmm43(4),pfebb_ebbmm44(4),pfebb_ebbmm45(4),
     &               pfebb_ebbmm46(4),pfebb_ebbmm47(4),pfebb_ebbmm48(4)
      common /amilcd_4f/pfebb_ebbmm49(4),pfebb_ebbmm50(4),
     &               pfebb_ebbmm51(4),pfebb_ebbmm52(4),pfebb_ebbmm53(4),
     &               pfebb_ebbmm54(4),pfebb_ebbmm55(4),pfebb_ebbmm56(4),
     &               pfebb_ebbmm57(4),pfebb_ebbmm58(4),pfebb_ebbmm59(4),
     &               pfebb_ebbmm60(4),pfebb_ebbmm61(4),pfebb_ebbmm62(4),
     &               pfebb_ebbmm63(4)
      common /amilcp_4f/vnebb_ebbmm2,vnebb_ebbmm3,vnebb_ebbmm4,
     &               vnebb_ebbmm5,vnebb_ebbmm6,vnebb_ebbmm7,
     &               vnebb_ebbmm8,vnebb_ebbmm9,vnebb_ebbmm10,
     &               vnebb_ebbmm11,vnebb_ebbmm12,vnebb_ebbmm13,
     &               vnebb_ebbmm14,vnebb_ebbmm15,vnebb_ebbmm16,
     &               vnebb_ebbmm17,vnebb_ebbmm18,vnebb_ebbmm19,
     &               vnebb_ebbmm20,vnebb_ebbmm21,vnebb_ebbmm22,
     &               vnebb_ebbmm23,vnebb_ebbmm24,vnebb_ebbmm25,
     &               vnebb_ebbmm26,vnebb_ebbmm27,vnebb_ebbmm28,
     &               vnebb_ebbmm29,vnebb_ebbmm30,vnebb_ebbmm31,
     &               vnebb_ebbmm32,vnebb_ebbmm33,vnebb_ebbmm34,
     &               vnebb_ebbmm35,vnebb_ebbmm36,vnebb_ebbmm37,
     &               vnebb_ebbmm38,vnebb_ebbmm39,vnebb_ebbmm40,
     &               vnebb_ebbmm41,vnebb_ebbmm42,vnebb_ebbmm43,
     &               vnebb_ebbmm44,vnebb_ebbmm45,vnebb_ebbmm46,
     &               vnebb_ebbmm47,vnebb_ebbmm48,vnebb_ebbmm49
      common /amilcp_4f/vnebb_ebbmm50,vnebb_ebbmm51,vnebb_ebbmm52,
     &               vnebb_ebbmm53,vnebb_ebbmm54,vnebb_ebbmm55,
     &               vnebb_ebbmm56,vnebb_ebbmm57,vnebb_ebbmm58,
     &               vnebb_ebbmm59,vnebb_ebbmm60,vnebb_ebbmm61,
     &               vnebb_ebbmm62,vnebb_ebbmm63
