*     File esb_esbtt/inclesb_esbtt1.h : Sat Mar 18 19:45:02 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (nesb_esbttgraph =25)
      parameter (nesb_esbttextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (lesb_esbttag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (nesb_esbttgrpsq = nesb_esbttgraph*nesb_esbttgraph)
      common /aesb_esbttmslct/jselg(nesb_esbttgraph),jgraph,jgluon,
     &               jhiggs

* Color string information
      common /aesb_esbttmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aesb_esbttmgrph/agcwrk(0:lesb_esbttag-1),agc(0:lesb_esbttag-1),
     &              aprop,ancp(nesb_esbttgraph),ansp(0:nesb_esbttgraph)
     &             ,cfmtx
      common /aesb_esbttmgrpi/igraph(nesb_esbttgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aesb_esbttmextr/peesb_esbtt1(4),peesb_esbtt2(4),
     &               peesb_esbtt3(4),peesb_esbtt4(4),peesb_esbtt5(4),
     &               peesb_esbtt6(4),
     &               prod(nesb_esbttextn, nesb_esbttextn)

      common /aesb_esbttmextp/ptesb_esbtt2t,exesb_esbtt2t,cfesb_esbtt2t,
     &               ptesb_esbtt4m,exesb_esbtt4m,cfesb_esbtt4m,
     &               ptesb_esbtt9t,exesb_esbtt9t,cfesb_esbtt9t,
     &               ptesb_esbtt17m,exesb_esbtt17m,cfesb_esbtt17m,
     &               ptesb_esbtt33o,exesb_esbtt33o,cfesb_esbtt33o,
     &               ptesb_esbtt62o,exesb_esbtt62o,cfesb_esbtt62o

      real*8     ptesb_esbtt2t(4,2), exesb_esbtt2t(1)
      complex*16 cfesb_esbtt2t(2,2)
      real*8     ptesb_esbtt4m(4,2), exesb_esbtt4m(1)
      complex*16 cfesb_esbtt4m(2,2)
      real*8     ptesb_esbtt9t(4,2), exesb_esbtt9t(1)
      complex*16 cfesb_esbtt9t(2,2)
      real*8     ptesb_esbtt17m(4,2), exesb_esbtt17m(1)
      complex*16 cfesb_esbtt17m(2,2)
      real*8     ptesb_esbtt33o(4,2), exesb_esbtt33o(1)
      complex*16 cfesb_esbtt33o(2,2)
      real*8     ptesb_esbtt62o(4,2), exesb_esbtt62o(1)
      complex*16 cfesb_esbtt62o(2,2)

* Normalization
      common /aesb_esbttmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aesb_esbttmatbl/av, lt, indexg
      complex*16 av(0:lesb_esbttag-1)
      integer    lt(0:nesb_esbttextn), indexg(nesb_esbttextn)

* Spin average
      common/aesb_esbttmspin/aspin,aident,jhs(nesb_esbttextn),
     &               jhe(nesb_esbttextn),jcpol(nesb_esbttextn),
     &               kperm(nesb_esbttextn)
