*     File es_esee/incles_esee1.h : Sat Mar 18 19:45:01 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (nes_eseegraph =48)
      parameter (nes_eseeextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (les_eseeag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (nes_eseegrpsq = nes_eseegraph*nes_eseegraph)
      common /aes_eseemslct/jselg(nes_eseegraph),jgraph,jgluon,jhiggs

* Color string information
      common /aes_eseemcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aes_eseemgrph/agcwrk(0:les_eseeag-1),agc(0:les_eseeag-1),
     &              aprop,ancp(nes_eseegraph),ansp(0:nes_eseegraph)
     &             ,cfmtx
      common /aes_eseemgrpi/igraph(nes_eseegraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aes_eseemextr/pees_esee1(4),pees_esee2(4),pees_esee3(4),
     &               pees_esee4(4),pees_esee5(4),pees_esee6(4),
     &               prod(nes_eseeextn, nes_eseeextn)

      common /aes_eseemextp/ptes_esee2t,exes_esee2t,cfes_esee2t,
     &               ptes_esee4m,exes_esee4m,cfes_esee4m,ptes_esee9t,
     &               exes_esee9t,cfes_esee9t,ptes_esee17m,exes_esee17m,
     &               cfes_esee17m,ptes_esee33m,exes_esee33m,
     &               cfes_esee33m,ptes_esee62m,exes_esee62m,
     &               cfes_esee62m

      real*8     ptes_esee2t(4,2), exes_esee2t(1)
      complex*16 cfes_esee2t(2,2)
      real*8     ptes_esee4m(4,2), exes_esee4m(1)
      complex*16 cfes_esee4m(2,2)
      real*8     ptes_esee9t(4,2), exes_esee9t(1)
      complex*16 cfes_esee9t(2,2)
      real*8     ptes_esee17m(4,2), exes_esee17m(1)
      complex*16 cfes_esee17m(2,2)
      real*8     ptes_esee33m(4,2), exes_esee33m(1)
      complex*16 cfes_esee33m(2,2)
      real*8     ptes_esee62m(4,2), exes_esee62m(1)
      complex*16 cfes_esee62m(2,2)

* Normalization
      common /aes_eseemdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aes_eseematbl/av, lt, indexg
      complex*16 av(0:les_eseeag-1)
      integer    lt(0:nes_eseeextn), indexg(nes_eseeextn)

* Spin average
      common/aes_eseemspin/aspin,aident,jhs(nes_eseeextn),
     &               jhe(nes_eseeextn),jcpol(nes_eseeextn),
     &               kperm(nes_eseeextn)
