*     File es_esee/incles_eseep.h : Sat Mar 18 19:45:01 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfes_esee2(4),pfes_esee3(4),pfes_esee4(4),
     &               pfes_esee5(4),pfes_esee6(4),pfes_esee7(4),
     &               pfes_esee8(4),pfes_esee9(4),pfes_esee10(4),
     &               pfes_esee11(4),pfes_esee12(4),pfes_esee13(4),
     &               pfes_esee14(4),pfes_esee15(4),pfes_esee16(4),
     &               pfes_esee17(4),pfes_esee18(4),pfes_esee19(4),
     &               pfes_esee20(4),pfes_esee21(4),pfes_esee22(4),
     &               pfes_esee23(4),pfes_esee24(4),pfes_esee25(4),
     &               pfes_esee26(4),pfes_esee27(4),pfes_esee28(4),
     &               pfes_esee29(4),pfes_esee30(4),pfes_esee31(4),
     &               pfes_esee32(4),pfes_esee33(4),pfes_esee34(4),
     &               pfes_esee35(4),pfes_esee36(4),pfes_esee37(4),
     &               pfes_esee38(4),pfes_esee39(4),pfes_esee40(4),
     &               pfes_esee41(4),pfes_esee42(4),pfes_esee43(4),
     &               pfes_esee44(4),pfes_esee45(4),pfes_esee46(4),
     &               pfes_esee47(4),pfes_esee48(4),pfes_esee49(4)
      common /amilcd_4f/pfes_esee50(4),pfes_esee51(4),
     &               pfes_esee52(4),pfes_esee53(4),pfes_esee54(4),
     &               pfes_esee55(4),pfes_esee56(4),pfes_esee57(4),
     &               pfes_esee58(4),pfes_esee59(4),pfes_esee60(4),
     &               pfes_esee61(4),pfes_esee62(4),pfes_esee63(4)
      common /amilcp_4f/vnes_esee2,vnes_esee3,vnes_esee4,vnes_esee5,
     &               vnes_esee6,vnes_esee7,vnes_esee8,vnes_esee9,
     &               vnes_esee10,vnes_esee11,vnes_esee12,vnes_esee13,
     &               vnes_esee14,vnes_esee15,vnes_esee16,vnes_esee17,
     &               vnes_esee18,vnes_esee19,vnes_esee20,vnes_esee21,
     &               vnes_esee22,vnes_esee23,vnes_esee24,vnes_esee25,
     &               vnes_esee26,vnes_esee27,vnes_esee28,vnes_esee29,
     &               vnes_esee30,vnes_esee31,vnes_esee32,vnes_esee33,
     &               vnes_esee34,vnes_esee35,vnes_esee36,vnes_esee37,
     &               vnes_esee38,vnes_esee39,vnes_esee40,vnes_esee41,
     &               vnes_esee42,vnes_esee43,vnes_esee44,vnes_esee45,
     &               vnes_esee46,vnes_esee47,vnes_esee48,vnes_esee49,
     &               vnes_esee50,vnes_esee51,vnes_esee52,vnes_esee53,
     &               vnes_esee54,vnes_esee55,vnes_esee56,vnes_esee57,
     &               vnes_esee58,vnes_esee59,vnes_esee60,vnes_esee61,
     &               vnes_esee62,vnes_esee63
