*     File esb_esbee/inclesb_esbee1.h : Sat Mar 18 19:45:02 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (nesb_esbeegraph =48)
      parameter (nesb_esbeeextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (lesb_esbeeag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (nesb_esbeegrpsq = nesb_esbeegraph*nesb_esbeegraph)
      common /aesb_esbeemslct/jselg(nesb_esbeegraph),jgraph,jgluon,
     &               jhiggs

* Color string information
      common /aesb_esbeemcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aesb_esbeemgrph/agcwrk(0:lesb_esbeeag-1),agc(0:lesb_esbeeag-1),
     &              aprop,ancp(nesb_esbeegraph),ansp(0:nesb_esbeegraph)
     &             ,cfmtx
      common /aesb_esbeemgrpi/igraph(nesb_esbeegraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aesb_esbeemextr/peesb_esbee1(4),peesb_esbee2(4),
     &               peesb_esbee3(4),peesb_esbee4(4),peesb_esbee5(4),
     &               peesb_esbee6(4),
     &               prod(nesb_esbeeextn, nesb_esbeeextn)

      common /aesb_esbeemextp/ptesb_esbee2t,exesb_esbee2t,cfesb_esbee2t,
     &               ptesb_esbee4m,exesb_esbee4m,cfesb_esbee4m,
     &               ptesb_esbee9t,exesb_esbee9t,cfesb_esbee9t,
     &               ptesb_esbee17m,exesb_esbee17m,cfesb_esbee17m,
     &               ptesb_esbee33m,exesb_esbee33m,cfesb_esbee33m,
     &               ptesb_esbee62m,exesb_esbee62m,cfesb_esbee62m

      real*8     ptesb_esbee2t(4,2), exesb_esbee2t(1)
      complex*16 cfesb_esbee2t(2,2)
      real*8     ptesb_esbee4m(4,2), exesb_esbee4m(1)
      complex*16 cfesb_esbee4m(2,2)
      real*8     ptesb_esbee9t(4,2), exesb_esbee9t(1)
      complex*16 cfesb_esbee9t(2,2)
      real*8     ptesb_esbee17m(4,2), exesb_esbee17m(1)
      complex*16 cfesb_esbee17m(2,2)
      real*8     ptesb_esbee33m(4,2), exesb_esbee33m(1)
      complex*16 cfesb_esbee33m(2,2)
      real*8     ptesb_esbee62m(4,2), exesb_esbee62m(1)
      complex*16 cfesb_esbee62m(2,2)

* Normalization
      common /aesb_esbeemdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aesb_esbeematbl/av, lt, indexg
      complex*16 av(0:lesb_esbeeag-1)
      integer    lt(0:nesb_esbeeextn), indexg(nesb_esbeeextn)

* Spin average
      common/aesb_esbeemspin/aspin,aident,jhs(nesb_esbeeextn),
     &               jhe(nesb_esbeeextn),jcpol(nesb_esbeeextn),
     &               kperm(nesb_esbeeextn)
