*     File ebb_ebbtt/aebb_ebbttkptbl.f : Sat Mar 18 19:45:06 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aebb_ebbttkptbl
      implicit real*8(a-h,o-z)

      include 'inclebb_ebbtt1.h'
      include 'inclk.h'
      include 'inclebb_ebbttp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfebb_ebbtt2(i) =  + peebb_ebbtt1(i)
        pfebb_ebbtt4(i) =  + peebb_ebbtt2(i)
        pfebb_ebbtt6(i) =  + peebb_ebbtt1(i) + peebb_ebbtt2(i)
        pfebb_ebbtt8(i) =  - peebb_ebbtt3(i)
        pfebb_ebbtt10(i) =  + peebb_ebbtt1(i) - peebb_ebbtt3(i)
        pfebb_ebbtt12(i) =  + peebb_ebbtt2(i) - peebb_ebbtt3(i)
        pfebb_ebbtt14(i) =  + peebb_ebbtt1(i) + peebb_ebbtt2(i) - peebb_ebbtt3(i)
        pfebb_ebbtt16(i) =  - peebb_ebbtt4(i)
        pfebb_ebbtt18(i) =  + peebb_ebbtt1(i) - peebb_ebbtt4(i)
        pfebb_ebbtt20(i) =  + peebb_ebbtt2(i) - peebb_ebbtt4(i)
        pfebb_ebbtt22(i) =  + peebb_ebbtt1(i) + peebb_ebbtt2(i) - peebb_ebbtt4(i)
        pfebb_ebbtt24(i) =  - peebb_ebbtt3(i) - peebb_ebbtt4(i)
        pfebb_ebbtt26(i) =  + peebb_ebbtt1(i) - peebb_ebbtt3(i) - peebb_ebbtt4(i)
        pfebb_ebbtt28(i) =  + peebb_ebbtt2(i) - peebb_ebbtt3(i) - peebb_ebbtt4(i)
        pfebb_ebbtt30(i) =  + peebb_ebbtt5(i) + peebb_ebbtt6(i)
        pfebb_ebbtt32(i) =  - peebb_ebbtt5(i)
        pfebb_ebbtt34(i) =  + peebb_ebbtt1(i) - peebb_ebbtt5(i)
        pfebb_ebbtt36(i) =  + peebb_ebbtt2(i) - peebb_ebbtt5(i)
        pfebb_ebbtt38(i) =  + peebb_ebbtt1(i) + peebb_ebbtt2(i) - peebb_ebbtt5(i)
        pfebb_ebbtt40(i) =  - peebb_ebbtt3(i) - peebb_ebbtt5(i)
        pfebb_ebbtt42(i) =  + peebb_ebbtt1(i) - peebb_ebbtt3(i) - peebb_ebbtt5(i)
        pfebb_ebbtt44(i) =  + peebb_ebbtt2(i) - peebb_ebbtt3(i) - peebb_ebbtt5(i)
        pfebb_ebbtt46(i) =  + peebb_ebbtt4(i) + peebb_ebbtt6(i)
        pfebb_ebbtt48(i) =  - peebb_ebbtt4(i) - peebb_ebbtt5(i)
        pfebb_ebbtt50(i) =  + peebb_ebbtt1(i) - peebb_ebbtt4(i) - peebb_ebbtt5(i)
        pfebb_ebbtt52(i) =  + peebb_ebbtt2(i) - peebb_ebbtt4(i) - peebb_ebbtt5(i)
        pfebb_ebbtt54(i) =  + peebb_ebbtt3(i) + peebb_ebbtt6(i)
        pfebb_ebbtt56(i) =  - peebb_ebbtt3(i) - peebb_ebbtt4(i) - peebb_ebbtt5(i)
        pfebb_ebbtt58(i) =  - peebb_ebbtt2(i) + peebb_ebbtt6(i)
        pfebb_ebbtt60(i) =  - peebb_ebbtt1(i) + peebb_ebbtt6(i)
        pfebb_ebbtt62(i) =  + peebb_ebbtt6(i)

        pfebb_ebbtt3(i) = - pfebb_ebbtt2(i)
        pfebb_ebbtt5(i) = - pfebb_ebbtt4(i)
        pfebb_ebbtt7(i) = - pfebb_ebbtt6(i)
        pfebb_ebbtt9(i) = - pfebb_ebbtt8(i)
        pfebb_ebbtt11(i) = - pfebb_ebbtt10(i)
        pfebb_ebbtt13(i) = - pfebb_ebbtt12(i)
        pfebb_ebbtt15(i) = - pfebb_ebbtt14(i)
        pfebb_ebbtt17(i) = - pfebb_ebbtt16(i)
        pfebb_ebbtt19(i) = - pfebb_ebbtt18(i)
        pfebb_ebbtt21(i) = - pfebb_ebbtt20(i)
        pfebb_ebbtt23(i) = - pfebb_ebbtt22(i)
        pfebb_ebbtt25(i) = - pfebb_ebbtt24(i)
        pfebb_ebbtt27(i) = - pfebb_ebbtt26(i)
        pfebb_ebbtt29(i) = - pfebb_ebbtt28(i)
        pfebb_ebbtt31(i) = - pfebb_ebbtt30(i)
        pfebb_ebbtt33(i) = - pfebb_ebbtt32(i)
        pfebb_ebbtt35(i) = - pfebb_ebbtt34(i)
        pfebb_ebbtt37(i) = - pfebb_ebbtt36(i)
        pfebb_ebbtt39(i) = - pfebb_ebbtt38(i)
        pfebb_ebbtt41(i) = - pfebb_ebbtt40(i)
        pfebb_ebbtt43(i) = - pfebb_ebbtt42(i)
        pfebb_ebbtt45(i) = - pfebb_ebbtt44(i)
        pfebb_ebbtt47(i) = - pfebb_ebbtt46(i)
        pfebb_ebbtt49(i) = - pfebb_ebbtt48(i)
        pfebb_ebbtt51(i) = - pfebb_ebbtt50(i)
        pfebb_ebbtt53(i) = - pfebb_ebbtt52(i)
        pfebb_ebbtt55(i) = - pfebb_ebbtt54(i)
        pfebb_ebbtt57(i) = - pfebb_ebbtt56(i)
        pfebb_ebbtt59(i) = - pfebb_ebbtt58(i)
        pfebb_ebbtt61(i) = - pfebb_ebbtt60(i)
        pfebb_ebbtt63(i) = - pfebb_ebbtt62(i)
  100 continue

      vnebb_ebbtt2 =  + amass2(1)
      vnebb_ebbtt4 =  + amass2(2)
      vnebb_ebbtt6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vnebb_ebbtt8 =  + amass2(3)
      vnebb_ebbtt10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vnebb_ebbtt12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vnebb_ebbtt14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vnebb_ebbtt16 =  + amass2(4)
      vnebb_ebbtt18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vnebb_ebbtt20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vnebb_ebbtt22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vnebb_ebbtt24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vnebb_ebbtt26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vnebb_ebbtt28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vnebb_ebbtt30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vnebb_ebbtt32 =  + amass2(5)
      vnebb_ebbtt34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vnebb_ebbtt36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vnebb_ebbtt38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vnebb_ebbtt40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vnebb_ebbtt42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vnebb_ebbtt44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vnebb_ebbtt46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vnebb_ebbtt48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vnebb_ebbtt50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vnebb_ebbtt52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vnebb_ebbtt54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vnebb_ebbtt56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vnebb_ebbtt58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vnebb_ebbtt60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vnebb_ebbtt62 =  + amass2(6)
      vnebb_ebbtt3 = vnebb_ebbtt2
      vnebb_ebbtt5 = vnebb_ebbtt4
      vnebb_ebbtt7 = vnebb_ebbtt6
      vnebb_ebbtt9 = vnebb_ebbtt8
      vnebb_ebbtt11 = vnebb_ebbtt10
      vnebb_ebbtt13 = vnebb_ebbtt12
      vnebb_ebbtt15 = vnebb_ebbtt14
      vnebb_ebbtt17 = vnebb_ebbtt16
      vnebb_ebbtt19 = vnebb_ebbtt18
      vnebb_ebbtt21 = vnebb_ebbtt20
      vnebb_ebbtt23 = vnebb_ebbtt22
      vnebb_ebbtt25 = vnebb_ebbtt24
      vnebb_ebbtt27 = vnebb_ebbtt26
      vnebb_ebbtt29 = vnebb_ebbtt28
      vnebb_ebbtt31 = vnebb_ebbtt30
      vnebb_ebbtt33 = vnebb_ebbtt32
      vnebb_ebbtt35 = vnebb_ebbtt34
      vnebb_ebbtt37 = vnebb_ebbtt36
      vnebb_ebbtt39 = vnebb_ebbtt38
      vnebb_ebbtt41 = vnebb_ebbtt40
      vnebb_ebbtt43 = vnebb_ebbtt42
      vnebb_ebbtt45 = vnebb_ebbtt44
      vnebb_ebbtt47 = vnebb_ebbtt46
      vnebb_ebbtt49 = vnebb_ebbtt48
      vnebb_ebbtt51 = vnebb_ebbtt50
      vnebb_ebbtt53 = vnebb_ebbtt52
      vnebb_ebbtt55 = vnebb_ebbtt54
      vnebb_ebbtt57 = vnebb_ebbtt56
      vnebb_ebbtt59 = vnebb_ebbtt58
      vnebb_ebbtt61 = vnebb_ebbtt60
      vnebb_ebbtt63 = vnebb_ebbtt62
      return
      end
