*     File ep_eXee/aep_eXeempsum.f : Sat Mar 18 19:45:45 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
*     CF version 
************************************************************************
      subroutine aep_eXeempsum(ans)
      implicit real*8(a-h,o-z)
      include 'inclep_eXee1.h'
      include 'inclk.h'
      real*8     ans
      complex*16 anc

      complex*16     agcr(0:lep_eXeeag-1,4)
       common /RESO/ agcr
      real*8     www
       external  www
      integer     mu,nu
      complex*16  anc_www
      include 'inclep_eXeep.h'

*-----------------------------------------------------------------------
      jsum = 1
      do 10 ie = 1, nep_eXeeextn
        jsum = jsum*(jhe(ie) - jhs(ie) + 1)
   10 continue

      anc = 0

*     sum over helicities
      call AgcPol(agcr(1,1))
      call AgcPol(agcr(1,2))
      call AgcPol(agcr(1,3))
      call AgcPol(agcr(1,4))
      do 100 ind = 0, jsum - 1

*       sum over color bases

        do mu=1,4
          anc_www = dble( agcr(ind,mu)*conjg(agcr(ind,mu)) )
     &                * www(mu,mu, abs(vnep_eXee10),amass1(3),
     &                    pfep_eXee2,pfep_eXee11, kcharg(1)/3,amass1(1))
          anc = anc + anc_www

          if ((mu.GT.1).AND.(mu.LT.4)) then
             do nu=1,mu-1
               anc_www = 2.D0*dble( agcr(ind,mu)*conjg(agcr(ind,nu)) )
     &                    *www(mu,nu, abs(vnep_eXee10),amass1(3),
     &                       pfep_eXee2,pfep_eXee11,
     &                       kcharg(1)/3,amass1(1))
               anc = anc + anc_www
             enddo
           elseif (mu.EQ.4) then
             do nu=1,mu-1
               anc_www = 2.D0*dble( agcr(ind,mu)*conjg(agcr(ind,nu)) )
     &                    *www(mu,nu, abs(vnep_eXee10),amass1(3),
     &                       pfep_eXee2,pfep_eXee11,
     &                       kcharg(1)/3,amass1(1))
               anc = anc - anc_www
             enddo
          endif
        enddo

  100 continue
      ans = cfmtx*anc
*     ans = anc

      ans = ans * 4.D0*pi*amass1(1) * (4*pi*alpha) /2.D0

      return
      end

