*     File ep_epmm/inclep_epmm1.h : Sat Mar 18 19:44:58 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (nep_epmmgraph =8)
      parameter (nep_epmmextn  =6)


* number of all helicity states
      parameter (lep_epmmag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (nep_epmmgrpsq = nep_epmmgraph*nep_epmmgraph)
      common /aep_epmmmslct/jselg(nep_epmmgraph),jgraph,jgluon,jhiggs

* Color string information
      common /aep_epmmmcsti/ kmcbas, kmcbmx, icinfo(6), icolst
      common /aep_epmmmgrph/agcwrk(0:lep_epmmag-1),agc(0:lep_epmmag-1),
     &              aprop,ancp(nep_epmmgraph),ansp(0:nep_epmmgraph)
     &             ,cfmtx
      common /aep_epmmmgrpi/igraph(nep_epmmgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aep_epmmmextr/peep_epmm1(4),peep_epmm2(4),peep_epmm3(4),
     &               peep_epmm4(4),peep_epmm5(4),peep_epmm6(4),
     &               prod(nep_epmmextn, nep_epmmextn)

      common /aep_epmmmextp/ptep_epmm2v,exep_epmm2v,cfep_epmm2v,
     &               ptep_epmm4m,exep_epmm4m,cfep_epmm4m,ptep_epmm9v,
     &               exep_epmm9v,cfep_epmm9v,ptep_epmm17m,exep_epmm17m,
     &               cfep_epmm17m,ptep_epmm33n,exep_epmm33n,
     &               cfep_epmm33n,ptep_epmm62n,exep_epmm62n,
     &               cfep_epmm62n

      real*8     ptep_epmm2v(4,2), exep_epmm2v(1)
      complex*16 cfep_epmm2v(2,2)
      real*8     ptep_epmm4m(4,2), exep_epmm4m(1)
      complex*16 cfep_epmm4m(2,2)
      real*8     ptep_epmm9v(4,2), exep_epmm9v(1)
      complex*16 cfep_epmm9v(2,2)
      real*8     ptep_epmm17m(4,2), exep_epmm17m(1)
      complex*16 cfep_epmm17m(2,2)
      real*8     ptep_epmm33n(4,2), exep_epmm33n(1)
      complex*16 cfep_epmm33n(2,2)
      real*8     ptep_epmm62n(4,2), exep_epmm62n(1)
      complex*16 cfep_epmm62n(2,2)

* Normalization
      common /aep_epmmmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aep_epmmmatbl/av, lt, indexg
      complex*16 av(0:lep_epmmag-1)
      integer    lt(0:nep_epmmextn), indexg(nep_epmmextn)

* Spin average
      common/aep_epmmmspin/aspin,aident,jhs(nep_epmmextn),
     &               jhe(nep_epmmextn),jcpol(nep_epmmextn),
     &               kperm(nep_epmmextn)
