*     File ep_epmm/inclep_epmmp.h : Sat Mar 18 19:44:58 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfep_epmm2(4),pfep_epmm3(4),pfep_epmm4(4),
     &               pfep_epmm5(4),pfep_epmm6(4),pfep_epmm7(4),
     &               pfep_epmm8(4),pfep_epmm9(4),pfep_epmm10(4),
     &               pfep_epmm11(4),pfep_epmm12(4),pfep_epmm13(4),
     &               pfep_epmm14(4),pfep_epmm15(4),pfep_epmm16(4),
     &               pfep_epmm17(4),pfep_epmm18(4),pfep_epmm19(4),
     &               pfep_epmm20(4),pfep_epmm21(4),pfep_epmm22(4),
     &               pfep_epmm23(4),pfep_epmm24(4),pfep_epmm25(4),
     &               pfep_epmm26(4),pfep_epmm27(4),pfep_epmm28(4),
     &               pfep_epmm29(4),pfep_epmm30(4),pfep_epmm31(4),
     &               pfep_epmm32(4),pfep_epmm33(4),pfep_epmm34(4),
     &               pfep_epmm35(4),pfep_epmm36(4),pfep_epmm37(4),
     &               pfep_epmm38(4),pfep_epmm39(4),pfep_epmm40(4),
     &               pfep_epmm41(4),pfep_epmm42(4),pfep_epmm43(4),
     &               pfep_epmm44(4),pfep_epmm45(4),pfep_epmm46(4),
     &               pfep_epmm47(4),pfep_epmm48(4),pfep_epmm49(4)
      common /amilcd_4f/pfep_epmm50(4),pfep_epmm51(4),
     &               pfep_epmm52(4),pfep_epmm53(4),pfep_epmm54(4),
     &               pfep_epmm55(4),pfep_epmm56(4),pfep_epmm57(4),
     &               pfep_epmm58(4),pfep_epmm59(4),pfep_epmm60(4),
     &               pfep_epmm61(4),pfep_epmm62(4),pfep_epmm63(4)
      common /amilcp_4f/vnep_epmm2,vnep_epmm3,vnep_epmm4,vnep_epmm5,
     &               vnep_epmm6,vnep_epmm7,vnep_epmm8,vnep_epmm9,
     &               vnep_epmm10,vnep_epmm11,vnep_epmm12,vnep_epmm13,
     &               vnep_epmm14,vnep_epmm15,vnep_epmm16,vnep_epmm17,
     &               vnep_epmm18,vnep_epmm19,vnep_epmm20,vnep_epmm21,
     &               vnep_epmm22,vnep_epmm23,vnep_epmm24,vnep_epmm25,
     &               vnep_epmm26,vnep_epmm27,vnep_epmm28,vnep_epmm29,
     &               vnep_epmm30,vnep_epmm31,vnep_epmm32,vnep_epmm33,
     &               vnep_epmm34,vnep_epmm35,vnep_epmm36,vnep_epmm37,
     &               vnep_epmm38,vnep_epmm39,vnep_epmm40,vnep_epmm41,
     &               vnep_epmm42,vnep_epmm43,vnep_epmm44,vnep_epmm45,
     &               vnep_epmm46,vnep_epmm47,vnep_epmm48,vnep_epmm49,
     &               vnep_epmm50,vnep_epmm51,vnep_epmm52,vnep_epmm53,
     &               vnep_epmm54,vnep_epmm55,vnep_epmm56,vnep_epmm57,
     &               vnep_epmm58,vnep_epmm59,vnep_epmm60,vnep_epmm61,
     &               vnep_epmm62,vnep_epmm63
