*     File es_estt/aes_esttmptbl.f : Sat Mar 18 19:45:02 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aes_esttmptbl
      implicit real*8(a-h,o-z)
      include 'incles_estt1.h'
      include 'incl2.h'
      include 'inclk.h'
      include 'incles_esttp.h'
*-----------------------------------------------------------------------
      jgraph = 0

* External lines
      call smextf(lincom,amdq(2),pfes_estt2,ptes_estt2t,cfes_estt2t)
      exes_estt2t(1) = lprtcl
      call smextf(loutgo,amlp(1),pfes_estt4,ptes_estt4m,cfes_estt4m)
      exes_estt4m(1) = lantip
      call smextf(loutgo,amdq(2),pfes_estt9,ptes_estt9t,cfes_estt9t)
      exes_estt9t(1) = lprtcl
      call smextf(lincom,amlp(1),pfes_estt17,ptes_estt17m,cfes_estt17m)
      exes_estt17m(1) = lantip
      call smextf(loutgo,amlp(3),pfes_estt33,ptes_estt33o,cfes_estt33o)
      exes_estt33o(1) = lprtcl
      call smextf(lincom,amlp(3),pfes_estt62,ptes_estt62o,cfes_estt62o)
      exes_estt62o(1) = lantip


* Buffer clear for amplitude
      do 200 ih = 0 , les_esttag-1
         agc(ih) = (0.0d0,0.0d0)
  200 continue

      call aes_esttmpt0

      return
      end
************************************************************************
      subroutine aes_esttmpt0
      implicit real*8(a-h,o-z)

      include 'incles_estt1.h'
      include 'incl2.h'
      include 'inclk.h'
*-----------------------------------------------------------------------
      if(jselg(1) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 1
        call aes_esttg1
      endif

      if(jselg(2) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 2
        call aes_esttg2
      endif

      if(jselg(3) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 3
        call aes_esttg3
      endif

      if(jselg(4) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 4
        call aes_esttg4
      endif

      if(jselg(5) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 5
        call aes_esttg5
      endif

      if(jselg(6) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 6
        call aes_esttg6
      endif

      if(jselg(7) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 7
        call aes_esttg7
      endif

      if(jselg(8) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 8
        call aes_esttg8
      endif

      if(jselg(9) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 9
        call aes_esttg9
      endif

      if(jselg(10) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 10
        call aes_esttg10
      endif

      if(jselg(11) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 11
        call aes_esttg11
      endif

      if(jselg(12) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 12
        call aes_esttg12
      endif

      if(jselg(13) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 13
        call aes_esttg13
      endif

      if(jselg(14) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 14
        call aes_esttg14
      endif

      if(jselg(15) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 15
        call aes_esttg15
      endif

      if(jselg(16) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 16
        call aes_esttg16
      endif

      if(jhiggs .ne. 0) then
      if(jselg(17) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 17
        call aes_esttg17
      endif
      endif

      if(jselg(18) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 18
        call aes_esttg18
      endif

      if(jselg(19) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 19
        call aes_esttg19
      endif

      if(jselg(20) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 20
        call aes_esttg20
      endif

      if(jselg(21) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 21
        call aes_esttg21
      endif

      if(jselg(22) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 22
        call aes_esttg22
      endif

      if(jselg(23) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 23
        call aes_esttg23
      endif

      if(jselg(24) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 24
        call aes_esttg24
      endif

      if(jselg(25) .ne. 0) then
        jgraph = jgraph + 1
        igraph(jgraph) = 25
        call aes_esttg25
      endif

      return
      end
