*     File esb_esbtt/spesb_esbttdetc.f : Sat Mar 18 19:45:02 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine spesb_esbttdetc
*-----------------------------------------------------------------------
*     Selection of Color State
*        output:icolst (0->ncbase-1)
*-----------------------------------------------------------------------
      implicit real*8 (a-h,o-z)

      return
      end
