*     File ec_ecmm/inclec_ecmm1.h : Sat Mar 18 19:45:03 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (nec_ecmmgraph =35)
      parameter (nec_ecmmextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (lec_ecmmag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (nec_ecmmgrpsq = nec_ecmmgraph*nec_ecmmgraph)
      common /aec_ecmmmslct/jselg(nec_ecmmgraph),jgraph,jgluon,jhiggs

* Color string information
      common /aec_ecmmmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aec_ecmmmgrph/agcwrk(0:lec_ecmmag-1),agc(0:lec_ecmmag-1),
     &              aprop,ancp(nec_ecmmgraph),ansp(0:nec_ecmmgraph)
     &             ,cfmtx
      common /aec_ecmmmgrpi/igraph(nec_ecmmgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aec_ecmmmextr/peec_ecmm1(4),peec_ecmm2(4),peec_ecmm3(4),
     &               peec_ecmm4(4),peec_ecmm5(4),peec_ecmm6(4),
     &               prod(nec_ecmmextn, nec_ecmmextn)

      common /aec_ecmmmextp/ptec_ecmm2q,exec_ecmm2q,cfec_ecmm2q,
     &               ptec_ecmm4m,exec_ecmm4m,cfec_ecmm4m,ptec_ecmm9q,
     &               exec_ecmm9q,cfec_ecmm9q,ptec_ecmm17m,exec_ecmm17m,
     &               cfec_ecmm17m,ptec_ecmm33n,exec_ecmm33n,
     &               cfec_ecmm33n,ptec_ecmm62n,exec_ecmm62n,
     &               cfec_ecmm62n

      real*8     ptec_ecmm2q(4,2), exec_ecmm2q(1)
      complex*16 cfec_ecmm2q(2,2)
      real*8     ptec_ecmm4m(4,2), exec_ecmm4m(1)
      complex*16 cfec_ecmm4m(2,2)
      real*8     ptec_ecmm9q(4,2), exec_ecmm9q(1)
      complex*16 cfec_ecmm9q(2,2)
      real*8     ptec_ecmm17m(4,2), exec_ecmm17m(1)
      complex*16 cfec_ecmm17m(2,2)
      real*8     ptec_ecmm33n(4,2), exec_ecmm33n(1)
      complex*16 cfec_ecmm33n(2,2)
      real*8     ptec_ecmm62n(4,2), exec_ecmm62n(1)
      complex*16 cfec_ecmm62n(2,2)

* Normalization
      common /aec_ecmmmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aec_ecmmmatbl/av, lt, indexg
      complex*16 av(0:lec_ecmmag-1)
      integer    lt(0:nec_ecmmextn), indexg(nec_ecmmextn)

* Spin average
      common/aec_ecmmmspin/aspin,aident,jhs(nec_ecmmextn),
     &               jhe(nec_ecmmextn),jcpol(nec_ecmmextn),
     &               kperm(nec_ecmmextn)
