*     File ec_ecmm/inclec_ecmmp.h : Sat Mar 18 19:45:03 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfec_ecmm2(4),pfec_ecmm3(4),pfec_ecmm4(4),
     &               pfec_ecmm5(4),pfec_ecmm6(4),pfec_ecmm7(4),
     &               pfec_ecmm8(4),pfec_ecmm9(4),pfec_ecmm10(4),
     &               pfec_ecmm11(4),pfec_ecmm12(4),pfec_ecmm13(4),
     &               pfec_ecmm14(4),pfec_ecmm15(4),pfec_ecmm16(4),
     &               pfec_ecmm17(4),pfec_ecmm18(4),pfec_ecmm19(4),
     &               pfec_ecmm20(4),pfec_ecmm21(4),pfec_ecmm22(4),
     &               pfec_ecmm23(4),pfec_ecmm24(4),pfec_ecmm25(4),
     &               pfec_ecmm26(4),pfec_ecmm27(4),pfec_ecmm28(4),
     &               pfec_ecmm29(4),pfec_ecmm30(4),pfec_ecmm31(4),
     &               pfec_ecmm32(4),pfec_ecmm33(4),pfec_ecmm34(4),
     &               pfec_ecmm35(4),pfec_ecmm36(4),pfec_ecmm37(4),
     &               pfec_ecmm38(4),pfec_ecmm39(4),pfec_ecmm40(4),
     &               pfec_ecmm41(4),pfec_ecmm42(4),pfec_ecmm43(4),
     &               pfec_ecmm44(4),pfec_ecmm45(4),pfec_ecmm46(4),
     &               pfec_ecmm47(4),pfec_ecmm48(4),pfec_ecmm49(4)
      common /amilcd_4f/pfec_ecmm50(4),pfec_ecmm51(4),
     &               pfec_ecmm52(4),pfec_ecmm53(4),pfec_ecmm54(4),
     &               pfec_ecmm55(4),pfec_ecmm56(4),pfec_ecmm57(4),
     &               pfec_ecmm58(4),pfec_ecmm59(4),pfec_ecmm60(4),
     &               pfec_ecmm61(4),pfec_ecmm62(4),pfec_ecmm63(4)
      common /amilcp_4f/vnec_ecmm2,vnec_ecmm3,vnec_ecmm4,vnec_ecmm5,
     &               vnec_ecmm6,vnec_ecmm7,vnec_ecmm8,vnec_ecmm9,
     &               vnec_ecmm10,vnec_ecmm11,vnec_ecmm12,vnec_ecmm13,
     &               vnec_ecmm14,vnec_ecmm15,vnec_ecmm16,vnec_ecmm17,
     &               vnec_ecmm18,vnec_ecmm19,vnec_ecmm20,vnec_ecmm21,
     &               vnec_ecmm22,vnec_ecmm23,vnec_ecmm24,vnec_ecmm25,
     &               vnec_ecmm26,vnec_ecmm27,vnec_ecmm28,vnec_ecmm29,
     &               vnec_ecmm30,vnec_ecmm31,vnec_ecmm32,vnec_ecmm33,
     &               vnec_ecmm34,vnec_ecmm35,vnec_ecmm36,vnec_ecmm37,
     &               vnec_ecmm38,vnec_ecmm39,vnec_ecmm40,vnec_ecmm41,
     &               vnec_ecmm42,vnec_ecmm43,vnec_ecmm44,vnec_ecmm45,
     &               vnec_ecmm46,vnec_ecmm47,vnec_ecmm48,vnec_ecmm49,
     &               vnec_ecmm50,vnec_ecmm51,vnec_ecmm52,vnec_ecmm53,
     &               vnec_ecmm54,vnec_ecmm55,vnec_ecmm56,vnec_ecmm57,
     &               vnec_ecmm58,vnec_ecmm59,vnec_ecmm60,vnec_ecmm61,
     &               vnec_ecmm62,vnec_ecmm63
