*     File inclm.h : Sat Mar 18 19:44:57 2000
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
* masses and width of particles
      common /smmass/amw      ,amz      ,ama      ,amg      ,amh      ,
     &               amx      ,amy      ,amnu  (3),amlp  (3),amuq  (3),
     &               amdq  (3),amp      ,amn      ,amcp     ,amcm     ,
     &               amcz     ,amca     ,amcg     ,amjp1s   ,amjp2s   ,
     &               amjp37   ,amjp40   ,amjp41   ,amjp44   ,amyy1s   ,
     &               amyy2s   ,amyy3s   ,amyy4s   ,amyy10   ,amyy11
      common /smmas2/     amw2,     amz2,     ama2,     amg2,     amh2,
     &                    amx2,     amy2,  amnu2(3),  amlp2(3),
     &                 amuq2(3),  amdq2(3),     amp2,     amn2,
     &                   amcp2,    amcm2,    amcz2,    amca2,    amcg2,
     &                 amjp1s2,  amjp2s2,  amjp372,  amjp402,  amjp412,
     &                 amjp442,  amyy1s2,  amyy2s2,  amyy3s2,  amyy4s2,
     &                 amyy102,  amyy112
      common /smgmma/      agw,      agz,      agh,      agx,      agy,
     &                 aguq(3),  agdq(3),     agcp,     agcm,     agcz,
     &                  agjp1s,   agjp2s,   agjp37,   agjp40,   agjp41,
     &                  agjp44,   agyy1s,   agyy2s,   agyy3s,   agyy4s,
     &                  agyy10,   agyy11
* amprtl, agprtl : kfcode --> mass, width
      common /smkfms/ amprtl(2212), agprtl(2212)
** defined in all.fin
      common /smcnst/ pi, pi2, rad, gevpb, alpha, alphas, alpha0
