*     File edb_edbee/incledb_edbeep.h : Sat Mar 18 19:45:01 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfedb_edbee2(4),pfedb_edbee3(4),
     &               pfedb_edbee4(4),pfedb_edbee5(4),pfedb_edbee6(4),
     &               pfedb_edbee7(4),pfedb_edbee8(4),pfedb_edbee9(4),
     &               pfedb_edbee10(4),pfedb_edbee11(4),pfedb_edbee12(4),
     &               pfedb_edbee13(4),pfedb_edbee14(4),pfedb_edbee15(4),
     &               pfedb_edbee16(4),pfedb_edbee17(4),pfedb_edbee18(4),
     &               pfedb_edbee19(4),pfedb_edbee20(4),pfedb_edbee21(4),
     &               pfedb_edbee22(4),pfedb_edbee23(4),pfedb_edbee24(4),
     &               pfedb_edbee25(4),pfedb_edbee26(4),pfedb_edbee27(4),
     &               pfedb_edbee28(4),pfedb_edbee29(4),pfedb_edbee30(4),
     &               pfedb_edbee31(4),pfedb_edbee32(4),pfedb_edbee33(4),
     &               pfedb_edbee34(4),pfedb_edbee35(4),pfedb_edbee36(4),
     &               pfedb_edbee37(4),pfedb_edbee38(4),pfedb_edbee39(4),
     &               pfedb_edbee40(4),pfedb_edbee41(4),pfedb_edbee42(4),
     &               pfedb_edbee43(4),pfedb_edbee44(4),pfedb_edbee45(4),
     &               pfedb_edbee46(4),pfedb_edbee47(4),pfedb_edbee48(4)
      common /amilcd_4f/pfedb_edbee49(4),pfedb_edbee50(4),
     &               pfedb_edbee51(4),pfedb_edbee52(4),pfedb_edbee53(4),
     &               pfedb_edbee54(4),pfedb_edbee55(4),pfedb_edbee56(4),
     &               pfedb_edbee57(4),pfedb_edbee58(4),pfedb_edbee59(4),
     &               pfedb_edbee60(4),pfedb_edbee61(4),pfedb_edbee62(4),
     &               pfedb_edbee63(4)
      common /amilcp_4f/vnedb_edbee2,vnedb_edbee3,vnedb_edbee4,
     &               vnedb_edbee5,vnedb_edbee6,vnedb_edbee7,
     &               vnedb_edbee8,vnedb_edbee9,vnedb_edbee10,
     &               vnedb_edbee11,vnedb_edbee12,vnedb_edbee13,
     &               vnedb_edbee14,vnedb_edbee15,vnedb_edbee16,
     &               vnedb_edbee17,vnedb_edbee18,vnedb_edbee19,
     &               vnedb_edbee20,vnedb_edbee21,vnedb_edbee22,
     &               vnedb_edbee23,vnedb_edbee24,vnedb_edbee25,
     &               vnedb_edbee26,vnedb_edbee27,vnedb_edbee28,
     &               vnedb_edbee29,vnedb_edbee30,vnedb_edbee31,
     &               vnedb_edbee32,vnedb_edbee33,vnedb_edbee34,
     &               vnedb_edbee35,vnedb_edbee36,vnedb_edbee37,
     &               vnedb_edbee38,vnedb_edbee39,vnedb_edbee40,
     &               vnedb_edbee41,vnedb_edbee42,vnedb_edbee43,
     &               vnedb_edbee44,vnedb_edbee45,vnedb_edbee46,
     &               vnedb_edbee47,vnedb_edbee48,vnedb_edbee49
      common /amilcp_4f/vnedb_edbee50,vnedb_edbee51,vnedb_edbee52,
     &               vnedb_edbee53,vnedb_edbee54,vnedb_edbee55,
     &               vnedb_edbee56,vnedb_edbee57,vnedb_edbee58,
     &               vnedb_edbee59,vnedb_edbee60,vnedb_edbee61,
     &               vnedb_edbee62,vnedb_edbee63
