*     File ec_ecee/inclec_eceep.h : Sat Mar 18 19:45:03 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfec_ecee2(4),pfec_ecee3(4),pfec_ecee4(4),
     &               pfec_ecee5(4),pfec_ecee6(4),pfec_ecee7(4),
     &               pfec_ecee8(4),pfec_ecee9(4),pfec_ecee10(4),
     &               pfec_ecee11(4),pfec_ecee12(4),pfec_ecee13(4),
     &               pfec_ecee14(4),pfec_ecee15(4),pfec_ecee16(4),
     &               pfec_ecee17(4),pfec_ecee18(4),pfec_ecee19(4),
     &               pfec_ecee20(4),pfec_ecee21(4),pfec_ecee22(4),
     &               pfec_ecee23(4),pfec_ecee24(4),pfec_ecee25(4),
     &               pfec_ecee26(4),pfec_ecee27(4),pfec_ecee28(4),
     &               pfec_ecee29(4),pfec_ecee30(4),pfec_ecee31(4),
     &               pfec_ecee32(4),pfec_ecee33(4),pfec_ecee34(4),
     &               pfec_ecee35(4),pfec_ecee36(4),pfec_ecee37(4),
     &               pfec_ecee38(4),pfec_ecee39(4),pfec_ecee40(4),
     &               pfec_ecee41(4),pfec_ecee42(4),pfec_ecee43(4),
     &               pfec_ecee44(4),pfec_ecee45(4),pfec_ecee46(4),
     &               pfec_ecee47(4),pfec_ecee48(4),pfec_ecee49(4)
      common /amilcd_4f/pfec_ecee50(4),pfec_ecee51(4),
     &               pfec_ecee52(4),pfec_ecee53(4),pfec_ecee54(4),
     &               pfec_ecee55(4),pfec_ecee56(4),pfec_ecee57(4),
     &               pfec_ecee58(4),pfec_ecee59(4),pfec_ecee60(4),
     &               pfec_ecee61(4),pfec_ecee62(4),pfec_ecee63(4)
      common /amilcp_4f/vnec_ecee2,vnec_ecee3,vnec_ecee4,vnec_ecee5,
     &               vnec_ecee6,vnec_ecee7,vnec_ecee8,vnec_ecee9,
     &               vnec_ecee10,vnec_ecee11,vnec_ecee12,vnec_ecee13,
     &               vnec_ecee14,vnec_ecee15,vnec_ecee16,vnec_ecee17,
     &               vnec_ecee18,vnec_ecee19,vnec_ecee20,vnec_ecee21,
     &               vnec_ecee22,vnec_ecee23,vnec_ecee24,vnec_ecee25,
     &               vnec_ecee26,vnec_ecee27,vnec_ecee28,vnec_ecee29,
     &               vnec_ecee30,vnec_ecee31,vnec_ecee32,vnec_ecee33,
     &               vnec_ecee34,vnec_ecee35,vnec_ecee36,vnec_ecee37,
     &               vnec_ecee38,vnec_ecee39,vnec_ecee40,vnec_ecee41,
     &               vnec_ecee42,vnec_ecee43,vnec_ecee44,vnec_ecee45,
     &               vnec_ecee46,vnec_ecee47,vnec_ecee48,vnec_ecee49,
     &               vnec_ecee50,vnec_ecee51,vnec_ecee52,vnec_ecee53,
     &               vnec_ecee54,vnec_ecee55,vnec_ecee56,vnec_ecee57,
     &               vnec_ecee58,vnec_ecee59,vnec_ecee60,vnec_ecee61,
     &               vnec_ecee62,vnec_ecee63
