*     File eub_eubmm/incleub_eubmm1.h : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (neub_eubmmgraph =25)
      parameter (neub_eubmmextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (leub_eubmmag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (neub_eubmmgrpsq = neub_eubmmgraph*neub_eubmmgraph)
      common /aeub_eubmmmslct/jselg(neub_eubmmgraph),jgraph,jgluon,
     &               jhiggs

* Color string information
      common /aeub_eubmmmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aeub_eubmmmgrph/agcwrk(0:leub_eubmmag-1),agc(0:leub_eubmmag-1),
     &              aprop,ancp(neub_eubmmgraph),ansp(0:neub_eubmmgraph)
     &             ,cfmtx
      common /aeub_eubmmmgrpi/igraph(neub_eubmmgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aeub_eubmmmextr/peeub_eubmm1(4),peeub_eubmm2(4),
     &               peeub_eubmm3(4),peeub_eubmm4(4),peeub_eubmm5(4),
     &               peeub_eubmm6(4),
     &               prod(neub_eubmmextn, neub_eubmmextn)

      common /aeub_eubmmmextp/pteub_eubmm2p,exeub_eubmm2p,cfeub_eubmm2p,
     &               pteub_eubmm4m,exeub_eubmm4m,cfeub_eubmm4m,
     &               pteub_eubmm9p,exeub_eubmm9p,cfeub_eubmm9p,
     &               pteub_eubmm17m,exeub_eubmm17m,cfeub_eubmm17m,
     &               pteub_eubmm33n,exeub_eubmm33n,cfeub_eubmm33n,
     &               pteub_eubmm62n,exeub_eubmm62n,cfeub_eubmm62n

      real*8     pteub_eubmm2p(4,2), exeub_eubmm2p(1)
      complex*16 cfeub_eubmm2p(2,2)
      real*8     pteub_eubmm4m(4,2), exeub_eubmm4m(1)
      complex*16 cfeub_eubmm4m(2,2)
      real*8     pteub_eubmm9p(4,2), exeub_eubmm9p(1)
      complex*16 cfeub_eubmm9p(2,2)
      real*8     pteub_eubmm17m(4,2), exeub_eubmm17m(1)
      complex*16 cfeub_eubmm17m(2,2)
      real*8     pteub_eubmm33n(4,2), exeub_eubmm33n(1)
      complex*16 cfeub_eubmm33n(2,2)
      real*8     pteub_eubmm62n(4,2), exeub_eubmm62n(1)
      complex*16 cfeub_eubmm62n(2,2)

* Normalization
      common /aeub_eubmmmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aeub_eubmmmatbl/av, lt, indexg
      complex*16 av(0:leub_eubmmag-1)
      integer    lt(0:neub_eubmmextn), indexg(neub_eubmmextn)

* Spin average
      common/aeub_eubmmmspin/aspin,aident,jhs(neub_eubmmextn),
     &               jhe(neub_eubmmextn),jcpol(neub_eubmmextn),
     &               kperm(neub_eubmmextn)
