*     File eb_ebtt/incleb_ebttp.h : Sat Mar 18 19:45:05 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
      common /amilcd_4f/pfeb_ebtt2(4),pfeb_ebtt3(4),pfeb_ebtt4(4),
     &               pfeb_ebtt5(4),pfeb_ebtt6(4),pfeb_ebtt7(4),
     &               pfeb_ebtt8(4),pfeb_ebtt9(4),pfeb_ebtt10(4),
     &               pfeb_ebtt11(4),pfeb_ebtt12(4),pfeb_ebtt13(4),
     &               pfeb_ebtt14(4),pfeb_ebtt15(4),pfeb_ebtt16(4),
     &               pfeb_ebtt17(4),pfeb_ebtt18(4),pfeb_ebtt19(4),
     &               pfeb_ebtt20(4),pfeb_ebtt21(4),pfeb_ebtt22(4),
     &               pfeb_ebtt23(4),pfeb_ebtt24(4),pfeb_ebtt25(4),
     &               pfeb_ebtt26(4),pfeb_ebtt27(4),pfeb_ebtt28(4),
     &               pfeb_ebtt29(4),pfeb_ebtt30(4),pfeb_ebtt31(4),
     &               pfeb_ebtt32(4),pfeb_ebtt33(4),pfeb_ebtt34(4),
     &               pfeb_ebtt35(4),pfeb_ebtt36(4),pfeb_ebtt37(4),
     &               pfeb_ebtt38(4),pfeb_ebtt39(4),pfeb_ebtt40(4),
     &               pfeb_ebtt41(4),pfeb_ebtt42(4),pfeb_ebtt43(4),
     &               pfeb_ebtt44(4),pfeb_ebtt45(4),pfeb_ebtt46(4),
     &               pfeb_ebtt47(4),pfeb_ebtt48(4),pfeb_ebtt49(4)
      common /amilcd_4f/pfeb_ebtt50(4),pfeb_ebtt51(4),
     &               pfeb_ebtt52(4),pfeb_ebtt53(4),pfeb_ebtt54(4),
     &               pfeb_ebtt55(4),pfeb_ebtt56(4),pfeb_ebtt57(4),
     &               pfeb_ebtt58(4),pfeb_ebtt59(4),pfeb_ebtt60(4),
     &               pfeb_ebtt61(4),pfeb_ebtt62(4),pfeb_ebtt63(4)
      common /amilcp_4f/vneb_ebtt2,vneb_ebtt3,vneb_ebtt4,vneb_ebtt5,
     &               vneb_ebtt6,vneb_ebtt7,vneb_ebtt8,vneb_ebtt9,
     &               vneb_ebtt10,vneb_ebtt11,vneb_ebtt12,vneb_ebtt13,
     &               vneb_ebtt14,vneb_ebtt15,vneb_ebtt16,vneb_ebtt17,
     &               vneb_ebtt18,vneb_ebtt19,vneb_ebtt20,vneb_ebtt21,
     &               vneb_ebtt22,vneb_ebtt23,vneb_ebtt24,vneb_ebtt25,
     &               vneb_ebtt26,vneb_ebtt27,vneb_ebtt28,vneb_ebtt29,
     &               vneb_ebtt30,vneb_ebtt31,vneb_ebtt32,vneb_ebtt33,
     &               vneb_ebtt34,vneb_ebtt35,vneb_ebtt36,vneb_ebtt37,
     &               vneb_ebtt38,vneb_ebtt39,vneb_ebtt40,vneb_ebtt41,
     &               vneb_ebtt42,vneb_ebtt43,vneb_ebtt44,vneb_ebtt45,
     &               vneb_ebtt46,vneb_ebtt47,vneb_ebtt48,vneb_ebtt49,
     &               vneb_ebtt50,vneb_ebtt51,vneb_ebtt52,vneb_ebtt53,
     &               vneb_ebtt54,vneb_ebtt55,vneb_ebtt56,vneb_ebtt57,
     &               vneb_ebtt58,vneb_ebtt59,vneb_ebtt60,vneb_ebtt61,
     &               vneb_ebtt62,vneb_ebtt63
