*     File eu_eumm/aeu_eummkptbl.f : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*
************************************************************************
      subroutine aeu_eummkptbl
      implicit real*8(a-h,o-z)

      include 'incleu_eumm1.h'
      include 'inclk.h'
      include 'incleu_eummp.h'
*-----------------------------------------------------------------------
      do 100 i = 1, 4
        pfeu_eumm2(i) =  + peeu_eumm1(i)
        pfeu_eumm4(i) =  + peeu_eumm2(i)
        pfeu_eumm6(i) =  + peeu_eumm1(i) + peeu_eumm2(i)
        pfeu_eumm8(i) =  - peeu_eumm3(i)
        pfeu_eumm10(i) =  + peeu_eumm1(i) - peeu_eumm3(i)
        pfeu_eumm12(i) =  + peeu_eumm2(i) - peeu_eumm3(i)
        pfeu_eumm14(i) =  + peeu_eumm1(i) + peeu_eumm2(i) - peeu_eumm3(i)
        pfeu_eumm16(i) =  - peeu_eumm4(i)
        pfeu_eumm18(i) =  + peeu_eumm1(i) - peeu_eumm4(i)
        pfeu_eumm20(i) =  + peeu_eumm2(i) - peeu_eumm4(i)
        pfeu_eumm22(i) =  + peeu_eumm1(i) + peeu_eumm2(i) - peeu_eumm4(i)
        pfeu_eumm24(i) =  - peeu_eumm3(i) - peeu_eumm4(i)
        pfeu_eumm26(i) =  + peeu_eumm1(i) - peeu_eumm3(i) - peeu_eumm4(i)
        pfeu_eumm28(i) =  + peeu_eumm2(i) - peeu_eumm3(i) - peeu_eumm4(i)
        pfeu_eumm30(i) =  + peeu_eumm5(i) + peeu_eumm6(i)
        pfeu_eumm32(i) =  - peeu_eumm5(i)
        pfeu_eumm34(i) =  + peeu_eumm1(i) - peeu_eumm5(i)
        pfeu_eumm36(i) =  + peeu_eumm2(i) - peeu_eumm5(i)
        pfeu_eumm38(i) =  + peeu_eumm1(i) + peeu_eumm2(i) - peeu_eumm5(i)
        pfeu_eumm40(i) =  - peeu_eumm3(i) - peeu_eumm5(i)
        pfeu_eumm42(i) =  + peeu_eumm1(i) - peeu_eumm3(i) - peeu_eumm5(i)
        pfeu_eumm44(i) =  + peeu_eumm2(i) - peeu_eumm3(i) - peeu_eumm5(i)
        pfeu_eumm46(i) =  + peeu_eumm4(i) + peeu_eumm6(i)
        pfeu_eumm48(i) =  - peeu_eumm4(i) - peeu_eumm5(i)
        pfeu_eumm50(i) =  + peeu_eumm1(i) - peeu_eumm4(i) - peeu_eumm5(i)
        pfeu_eumm52(i) =  + peeu_eumm2(i) - peeu_eumm4(i) - peeu_eumm5(i)
        pfeu_eumm54(i) =  + peeu_eumm3(i) + peeu_eumm6(i)
        pfeu_eumm56(i) =  - peeu_eumm3(i) - peeu_eumm4(i) - peeu_eumm5(i)
        pfeu_eumm58(i) =  - peeu_eumm2(i) + peeu_eumm6(i)
        pfeu_eumm60(i) =  - peeu_eumm1(i) + peeu_eumm6(i)
        pfeu_eumm62(i) =  + peeu_eumm6(i)

        pfeu_eumm3(i) = - pfeu_eumm2(i)
        pfeu_eumm5(i) = - pfeu_eumm4(i)
        pfeu_eumm7(i) = - pfeu_eumm6(i)
        pfeu_eumm9(i) = - pfeu_eumm8(i)
        pfeu_eumm11(i) = - pfeu_eumm10(i)
        pfeu_eumm13(i) = - pfeu_eumm12(i)
        pfeu_eumm15(i) = - pfeu_eumm14(i)
        pfeu_eumm17(i) = - pfeu_eumm16(i)
        pfeu_eumm19(i) = - pfeu_eumm18(i)
        pfeu_eumm21(i) = - pfeu_eumm20(i)
        pfeu_eumm23(i) = - pfeu_eumm22(i)
        pfeu_eumm25(i) = - pfeu_eumm24(i)
        pfeu_eumm27(i) = - pfeu_eumm26(i)
        pfeu_eumm29(i) = - pfeu_eumm28(i)
        pfeu_eumm31(i) = - pfeu_eumm30(i)
        pfeu_eumm33(i) = - pfeu_eumm32(i)
        pfeu_eumm35(i) = - pfeu_eumm34(i)
        pfeu_eumm37(i) = - pfeu_eumm36(i)
        pfeu_eumm39(i) = - pfeu_eumm38(i)
        pfeu_eumm41(i) = - pfeu_eumm40(i)
        pfeu_eumm43(i) = - pfeu_eumm42(i)
        pfeu_eumm45(i) = - pfeu_eumm44(i)
        pfeu_eumm47(i) = - pfeu_eumm46(i)
        pfeu_eumm49(i) = - pfeu_eumm48(i)
        pfeu_eumm51(i) = - pfeu_eumm50(i)
        pfeu_eumm53(i) = - pfeu_eumm52(i)
        pfeu_eumm55(i) = - pfeu_eumm54(i)
        pfeu_eumm57(i) = - pfeu_eumm56(i)
        pfeu_eumm59(i) = - pfeu_eumm58(i)
        pfeu_eumm61(i) = - pfeu_eumm60(i)
        pfeu_eumm63(i) = - pfeu_eumm62(i)
  100 continue

      vneu_eumm2 =  + amass2(1)
      vneu_eumm4 =  + amass2(2)
      vneu_eumm6 =  + 2.0d0*prod(1,2) + amass2(1) + amass2(2)
      vneu_eumm8 =  + amass2(3)
      vneu_eumm10 =  - 2.0d0*prod(1,3) + amass2(1) + amass2(3)
      vneu_eumm12 =  - 2.0d0*prod(2,3) + amass2(2) + amass2(3)
      vneu_eumm14 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,3) - 2.0d0*
     &      prod(2,3) + amass2(1) + amass2(2) + amass2(3)
      vneu_eumm16 =  + amass2(4)
      vneu_eumm18 =  - 2.0d0*prod(1,4) + amass2(1) + amass2(4)
      vneu_eumm20 =  - 2.0d0*prod(2,4) + amass2(2) + amass2(4)
      vneu_eumm22 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,4) - 2.0d0*
     &      prod(2,4) + amass2(1) + amass2(2) + amass2(4)
      vneu_eumm24 =  + 2.0d0*prod(3,4) + amass2(3) + amass2(4)
      vneu_eumm26 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,4) + 2.0d0*
     &      prod(3,4) + amass2(1) + amass2(3) + amass2(4)
      vneu_eumm28 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,4) + 2.0d0*
     &      prod(3,4) + amass2(2) + amass2(3) + amass2(4)
      vneu_eumm30 =  + 2.0d0*prod(5,6) + amass2(5) + amass2(6)
      vneu_eumm32 =  + amass2(5)
      vneu_eumm34 =  - 2.0d0*prod(1,5) + amass2(1) + amass2(5)
      vneu_eumm36 =  - 2.0d0*prod(2,5) + amass2(2) + amass2(5)
      vneu_eumm38 =  + 2.0d0*prod(1,2) - 2.0d0*prod(1,5) - 2.0d0*
     &      prod(2,5) + amass2(1) + amass2(2) + amass2(5)
      vneu_eumm40 =  + 2.0d0*prod(3,5) + amass2(3) + amass2(5)
      vneu_eumm42 =  - 2.0d0*prod(1,3) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(3,5) + amass2(1) + amass2(3) + amass2(5)
      vneu_eumm44 =  - 2.0d0*prod(2,3) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(3,5) + amass2(2) + amass2(3) + amass2(5)
      vneu_eumm46 =  + 2.0d0*prod(4,6) + amass2(4) + amass2(6)
      vneu_eumm48 =  + 2.0d0*prod(4,5) + amass2(4) + amass2(5)
      vneu_eumm50 =  - 2.0d0*prod(1,4) - 2.0d0*prod(1,5) + 2.0d0*
     &      prod(4,5) + amass2(1) + amass2(4) + amass2(5)
      vneu_eumm52 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*
     &      prod(4,5) + amass2(2) + amass2(4) + amass2(5)
      vneu_eumm54 =  + 2.0d0*prod(3,6) + amass2(3) + amass2(6)
      vneu_eumm56 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*
     &      prod(4,5) + amass2(3) + amass2(4) + amass2(5)
      vneu_eumm58 =  - 2.0d0*prod(2,6) + amass2(2) + amass2(6)
      vneu_eumm60 =  - 2.0d0*prod(1,6) + amass2(1) + amass2(6)
      vneu_eumm62 =  + amass2(6)
      vneu_eumm3 = vneu_eumm2
      vneu_eumm5 = vneu_eumm4
      vneu_eumm7 = vneu_eumm6
      vneu_eumm9 = vneu_eumm8
      vneu_eumm11 = vneu_eumm10
      vneu_eumm13 = vneu_eumm12
      vneu_eumm15 = vneu_eumm14
      vneu_eumm17 = vneu_eumm16
      vneu_eumm19 = vneu_eumm18
      vneu_eumm21 = vneu_eumm20
      vneu_eumm23 = vneu_eumm22
      vneu_eumm25 = vneu_eumm24
      vneu_eumm27 = vneu_eumm26
      vneu_eumm29 = vneu_eumm28
      vneu_eumm31 = vneu_eumm30
      vneu_eumm33 = vneu_eumm32
      vneu_eumm35 = vneu_eumm34
      vneu_eumm37 = vneu_eumm36
      vneu_eumm39 = vneu_eumm38
      vneu_eumm41 = vneu_eumm40
      vneu_eumm43 = vneu_eumm42
      vneu_eumm45 = vneu_eumm44
      vneu_eumm47 = vneu_eumm46
      vneu_eumm49 = vneu_eumm48
      vneu_eumm51 = vneu_eumm50
      vneu_eumm53 = vneu_eumm52
      vneu_eumm55 = vneu_eumm54
      vneu_eumm57 = vneu_eumm56
      vneu_eumm59 = vneu_eumm58
      vneu_eumm61 = vneu_eumm60
      vneu_eumm63 = vneu_eumm62
      return
      end
