*     File eu_eumm/incleu_eumm1.h : Sat Mar 18 19:44:59 2000
*
*     Generated by GRACE (Fortran source code generator)
*         Ver.2.1.5(2) 1998/05/11
*
*     (c)copyright 1990-1998 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*

      include 'inclc.h'
      include 'inclg.h'

      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexv =  3)
      parameter (lepina =  4, lepinv =  4)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (neu_eummgraph =25)
      parameter (neu_eummextn  =6)


* number of color base
      parameter (ncbase =1)

* number of all helicity states
      parameter (leu_eummag    =64)

      common /amprck/kmngr,  kmnext, kmlag
      common /amprcs/smpref, smproc
      character*80   smpref, smproc

      parameter (neu_eummgrpsq = neu_eummgraph*neu_eummgraph)
      common /aeu_eummmslct/jselg(neu_eummgraph),jgraph,jgluon,jhiggs

* Color string information
      common /aeu_eummmcsti/ kmcbas, kmcbmx, kmcstr(2), icinfo(6), icolst
      common /aeu_eummmgrph/agcwrk(0:leu_eummag-1),agc(0:leu_eummag-1),
     &              aprop,ancp(neu_eummgraph),ansp(0:neu_eummgraph)
     &             ,cfmtx
      common /aeu_eummmgrpi/igraph(neu_eummgraph)
      complex*16 agc, agcwrk, aprop

* Momenta of external particles
      common /aeu_eummmextr/peeu_eumm1(4),peeu_eumm2(4),peeu_eumm3(4),
     &               peeu_eumm4(4),peeu_eumm5(4),peeu_eumm6(4),
     &               prod(neu_eummextn, neu_eummextn)

      common /aeu_eummmextp/pteu_eumm2p,exeu_eumm2p,cfeu_eumm2p,
     &               pteu_eumm4m,exeu_eumm4m,cfeu_eumm4m,pteu_eumm9p,
     &               exeu_eumm9p,cfeu_eumm9p,pteu_eumm17m,exeu_eumm17m,
     &               cfeu_eumm17m,pteu_eumm33n,exeu_eumm33n,
     &               cfeu_eumm33n,pteu_eumm62n,exeu_eumm62n,
     &               cfeu_eumm62n

      real*8     pteu_eumm2p(4,2), exeu_eumm2p(1)
      complex*16 cfeu_eumm2p(2,2)
      real*8     pteu_eumm4m(4,2), exeu_eumm4m(1)
      complex*16 cfeu_eumm4m(2,2)
      real*8     pteu_eumm9p(4,2), exeu_eumm9p(1)
      complex*16 cfeu_eumm9p(2,2)
      real*8     pteu_eumm17m(4,2), exeu_eumm17m(1)
      complex*16 cfeu_eumm17m(2,2)
      real*8     pteu_eumm33n(4,2), exeu_eumm33n(1)
      complex*16 cfeu_eumm33n(2,2)
      real*8     pteu_eumm62n(4,2), exeu_eumm62n(1)
      complex*16 cfeu_eumm62n(2,2)

* Normalization
      common /aeu_eummmdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /aeu_eummmatbl/av, lt, indexg
      complex*16 av(0:leu_eummag-1)
      integer    lt(0:neu_eummextn), indexg(neu_eummextn)

* Spin average
      common/aeu_eummmspin/aspin,aident,jhs(neu_eummextn),
     &               jhe(neu_eummextn),jcpol(neu_eummextn),
     &               kperm(neu_eummextn)
